### ISSUE TITLE
Contract call from Demo Test App is failing

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1778]
User was testing Pr:https://github.com/blockstack/stacks-wallet-web/pull/1777
User then wanted to test the contracl call via Testnet Demo
User noticed the first two contract call failed in the web wallet
<img width="446" alt="Screen Shot 2021-10-05 at 5 03 18 PM" src="https://user-images.githubusercontent.com/38872890/136115196-3ff3737f-421b-4bdf-8369-d51e4ca4fd7e.png">
<img width="447" alt="Screen Shot 2021-10-05 at 5 03 29 PM" src="https://user-images.githubusercontent.com/38872890/136115199-b2d5f9a6-61ed-4e7f-b5a8-eca697b5e519.png">

This ticket was created in order to investigate why the contract call failed
cc @fbwoolf @beguene

**Comment by fbwoolf** [comment]
@beguene hoping you can look at this in the morning. It was found when testing my fix for the queued transactions not filtering correctly, but these failures are not because of that change. My fix was merged into main and it was found there. I went back to the commit of the previous release and the contract calls in the test-app were failing then too, so I'm not sure what is causing them to fail now. I haven't been able to identify the problem yet so hoping your fresh eyes on it can find something!

**Comment by beguene** [comment]
Sure I will check it out.
