### ISSUE TITLE
Fix decryption permission issue upon entering password

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#1902]
My personal Chrome installation of the wallet extension began pending intermably upon password entry, both with my existing Secret Key and with new ones, and even after uninstalling and reinstalling again via the Chrome Web Store.

![image](https://user-images.githubusercontent.com/28991/140306244-9f37ae2b-abe8-4d95-8c23-17e1d27e1f98.png)

Upon inspection of the background page's console, @kyranjamie and I found this error:

> Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (decryption-worker.js:18)
    at decryption-worker.js:18

He says it appears the browser is blocking the permission needed for decrypting the password, though it's unclear why any such permission would be needed specifically.

Note that while I can't get past the password screen, I _can_ see my accounts for selection when trying to authenticate an application. This is unexpected since I would expect to see the password prompt here as well:

<img width="997" alt="Screen Shot 2021-11-04 at 12 26 35" src="https://user-images.githubusercontent.com/28991/140306310-c67c99a1-f714-4682-9c48-dc14ccab0e66.png">

We should perhaps path this UI discrepancy as well while resolving the underlying decryption issue.

I haven't personally seen other users report this issue, but we should capture incidences here in case it's a more widespread issue than just my own installation.

**Comment by markmhendrickson** [comment]
@kyranjamie is there any permissions setting I can change as a workaround for this while it's fixed?

**Comment by kyranjamie** [comment]
> is there any permissions setting I can change as a workaround for this while it's fixed?

No, this is a CSP rule that isn't configurable. The easy fix is to rerelease the wallet with the `'wasm-eval'` CSP exception re-added. 

Though, per [WebWorker CSP docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#content_security_policy), this shouldn't be necessary. Workers have their own context and `eval` is allowed, even with an otherwise strict CSP. Which is why I removed it when I added the worker.

Could you try again with the latest [dev build](https://github.com/hirosystems/stacks-wallet-web/releases) and see if it behaves the same?

**Comment by markmhendrickson** [comment]
Same issue with the latest dev build

**Comment by kyranjamie** [comment]
Just tried creating wallet from new install with latest dev build `v2.20.1-dev.9`, Chrome `Version 95.0.4638.69 (Official Build) (x86_64)`, no issues 🤔

**Comment by markmhendrickson** [comment]
I'm going to test this on my laptop to see if I still get them. They seem unique to my desktop computer so far.

**Comment by markmhendrickson** [comment]
I was able to unblock myself here by adding `'unsafe-eval'` to my manifest file locally per https://stackoverflow.com/questions/48523118/wasm-module-compile-error-in-chrome-extension

**Comment by kyranjamie** [comment]
`wasm-eval` should achieve the same, but as I say, still shouldn't be necessary. This is a really weird one. 

@fbwoolf @beguene have either of you come across this before?

**Comment by fbwoolf** [comment]
> 
> @fbwoolf @beguene have either of you come across this before?

Nope, I couldn't reproduce this one. I tried when Mark first reported it in Discord.

**Comment by beguene** [comment]
> `wasm-eval` should achieve the same, but as I say, still shouldn't be necessary. This is a really weird one.
> 
> @fbwoolf @beguene have either of you come across this before?

No I've never seen that before

**Comment by jdhartley** [comment]
I am glad to see this issue reported since I could not figure this out! I see the same CSP error on the background page.

I am seeing this issue on Chrome `96.0.4664.35 (Official Build) beta (64-bit)`

I am NOT seeing this issue on Chrome `95.0.4638.69 (Official Build) (64-bit)`

Can anyone else confirm their chrome version?

Anecdotally, I _believe_ this issue started to occur for me when Chrome 96 beta was released a few weeks ago, but don't have the paper trail to confirm this

**Comment by markmhendrickson** [comment]
I've been using a beta release, which appears affected as in your case:

![image](https://user-images.githubusercontent.com/28991/141118023-be412634-beeb-4d04-b743-0c517a963eee.png)

@kyranjamie has tracked this down as a bug in Chrome itself: https://bugs.chromium.org/p/chromium/issues/detail?id=1268576 and merged PR https://github.com/hirosystems/stacks-wallet-web/pull/1911 which appears to resolve this issue starting with the next release.
