### ISSUE TITLE
Two (or more) transactions exist at the same time with one nonce

### ISSUE THREAD

**Issue by bogachevanton** [blockstack/blockstack-app#1930]
I have a slippage in the [blockchain explorer](https://explorer.stacks.co/) and [hiro wallet chrome extension](https://www.hiro.so/wallet/install-web)
There are also several transactions at the same time, with one nonce (421):

https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0xb6bd96cfd0b42b0980c36670c6b4ed3919a5f9829b82928647ff400174727371
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x3a2df4343501bf3b93f8a93413cc86044502db303bd3a4a2f2e3ab6aa22e947f

and these two transactions exist at the same time

![Video_2021-11-12_095313](https://user-images.githubusercontent.com/90133006/141485288-487289a6-b0c3-474f-93e3-2a3092c12f75.gif)

**Comment by bogachevanton** [comment]
Closed all these stuck transactions - with higher fee transfer transactions

![image](https://user-images.githubusercontent.com/90133006/141492419-87ade7cd-37e2-49d6-b432-89035051ab19.png)

**Comment by 314159265359879** [comment]
it looks like an issue with the frontend I have also seen this on occasion. Transactions blinking in an out of the explorer and the same with the activities tab of the web wallet. 

I think when you use replace by fee the old transaction will still be in the mempool, the miner is just not going to pick it up when there is a transaction with the same nonce and a higher fee. I think the idea is that "replaced" transactions should not be shown in the explorer/activities tab instead of this "blinking" behaviour. 

It is a problem however because if the webwallet is not aware of a pending transactions it can send a new transaction with a nonce that is already in the mempool.

**Comment by bogachevanton** [comment]
> It is a problem however because if the webwallet is not aware of a pending transactions it can send a new transaction with a nonce that is already in the mempool.

yes, I think that's exactly what happened
at the same time, the hiro web wallet offers periodically different nonce values
the problem seems to be much deeper than it initially appears

@markmhx @fbwoolf @kyranjamie

**Comment by 314159265359879** [comment]
One more observation this seems to occur more often when there are a lot of API calls to explorer.stacks.co and or when there is a lot of activity on the network. Such as due to Arkadiko re-enabling swaps/farming and second citycoin launch yesterday.

Here is a picture of the current mempool, more transactions send = more API calls by the web wallet and explorer:
![image](https://user-images.githubusercontent.com/33360391/141537889-addfcd54-5d71-40d1-a1a4-abf03aa814ba.png)

**Comment by markmhendrickson** [comment]
Thanks for the report. Have either of you seen this particular behavior on more than one occasion?

**Comment by 314159265359879** [comment]
Yes more than once. Yesterday I saw it again, that could have been the fifth instance I have seen. 
This time there was even a transaction that showed confirmed and then it didn't and then it did etc. The transaction was confirmed in a block that was not shown by the explorer at that time, I checked on explorer.stacks.co and explorer.syvita.org but it could still have been due to a syncing problem? 
This occurred with block #38118, I am afraid I have lost track of the exact transaction. But I remember the transaction said confirmed ~20 minutes ago while the block confirmed list (explorer home page) showed "1 minute ago" for the same block at some time. After it showed in the explorer it no longer blinked in an out of the activities tab of the Hiro wallet.

**Comment by 314159265359879** [comment]
Here is someone I just helped on Telegram, could be due to the same flikkering, if the web extension doesn't have a full view of pending transactions you get the wrong nonces: he has the weirdest nonces on pending transactions:
The account nonce is 9 - SP2A6F802MTTNE4P2Z6WG8SXMKBH4JXMX5JR2CZB6 (nonces in red)
![image](https://user-images.githubusercontent.com/33360391/142241527-ca00e77b-55d0-449b-b077-4488fed09f28.png)

**Comment by bogachevanton** [comment]
So, another one.

Wallet: SP779SC9CDWQVMTRXT0HZCEHSDBXCHNGG7BC1H9B
TX1: https://explorer.stacks.co/txid/0xdada5e8647d9a39e4af00216f088e7cf9b77bad11271c8611a5404765705e8a7?chain=mainnet
TX2: https://explorer.stacks.co/txid/0x017032bac3fe53dd4fecc65f54c21f21505721d35596c5333f862718bd5ebfcc?chain=mainnet

**Explorer**

![Video_2021-11-22_184447](https://user-images.githubusercontent.com/90133006/142893071-0604c56a-827c-417a-a95f-76dc0904fdc3.gif)

**Wallet**
![Video_2021-11-22_185234](https://user-images.githubusercontent.com/90133006/142893107-6df6092a-787d-4028-8460-92939f590840.gif)

**Comment by markmhendrickson** [comment]
@beguene to investigate

**Comment by beguene** [comment]
Thanks @bogachevanton and @314159265359879 for the report.
There are 2 issues I see here
1. The display of transactions are changing in a 'blink' for both the wallet and explorer
2. The wallet use an incorrect nonce when the last pending transaction has not been seen yet by the api

Regarding 2.

The issue we have is that we rely on the api data to have an external view on the blockchain and mempool state.
If the api or the blockchain nodes have any issue to sync or some delay, then it will be reflected in the UI.
If there is a sync issue, the nonce calculation which is based on the api's view on the current blockchain and mempool state will be inaccurate.

### Logic 1: 
We could try to favour the locally incremented nonce but this also will lead to other kind of problems. For example user submit a tx with nonce = 100,
it's propagated but somehow it's dropped from the mempool some time later. The api will return that the next possible nonce is 100 (which is correct) but our local increment would be 101, and the user will be stuck.

### Logic 2: 
If we rely on the api (which we do currently), we are most of the time correct, but the times where there is a sync issue, delay or congestion, then the nonce returned by the api will be inaccurate.

---

I think the most common issue with incorrect nonce happens when multiple tx are submitted in the wallet but not picked up yet by the api/mempool, mainly because the transaction are sent by the users one after the other pretty quickly AND the api is somehow slower (which is uncommon)
One solution could be to query the state of the api / mempool congestion (if there is a way to do that) before the user sends a new transactions or try to know if there is a sync issue.
We can then either ask the user to wait a bit, delay the transaction submission or suggest a locally incremented nonce but with warning that there is a chance that it will not work.
We can also give a hint to the user if he edits the nonce, but we should always use the external source, in our case the api which has the better visibility on the state of the blockchain and mempool.

Ultimately I think we should wait for the following issues to be resolved before implementing something more complex on our side.
Related
https://github.com/blockstack/stacks-blockchain/issues/2193
https://github.com/hirosystems/stacks-blockchain-api/issues/765
https://github.com/hirosystems/stacks-wallet-web/issues/1723

Regarding 1, we are just displaying the result of the api, @zone117x or @rafaelcr do you have any idea ?

**Comment by SarkarAbhijoy** [comment]
A similar issue reported by a friend. Reposting here from Discord: https://discord.com/channels/621759717756370964/745197302255321108/932015324008706068

A duplicate transaction was broadcasted with same nonce and different fees but the txn with lower fees got confirmed, and the higher fees one is pending. 
 
Event log: He was sending STX to an account with low fee setting. Then he pressed the speed up button. As he clicked the button, the original transaction was confirmed while the speedup transaction with same nonce was broadcasted.
 
Confirmed txn with nonce 0 - https://explorer.stacks.co/txid/0x8d8d3c723774025f6f7f8322b9debe21b44b6f72d15f225d66dd2fc4c9330667?chain=mainnet 
Unconfirmed txn with nonce 0 - https://explorer.stacks.co/txid/0xafb6b8c382cb7d4be7498cc95626540d515b9861fa4d96d292c3e46328980383?chain=mainnet 
 
As a result no another transaction can now be broadcasted until the pending txn is dropped after 256 blocks. Hiro wallet does not let any other transaction confirm with nonce 1, as according to it nonce 0 is still pending. Classic catch 22 since he is also unable to do a manual RBF as Hiro wallet says the transaction is already confirmed.

**Comment by beguene** [comment]
@SarkarAbhijoy Even if there is a transaction with the same nonce but one got confirmed, you can still broadcast another transaction (nonce = previous nonce + 1) and this new transaction and all subsequent transactions will be working fine. Only the pending transaction with a duplicated nonce (here nonce = 0) will be seen as pending for ~42 hours and then dropped from the mempool. You can just ignore this transaction. 
Nonetheless this can mislead the user if he sees a 'pending' transaction in the activity list. Many users will try to do something while they should do nothing.
There is a task for this already here https://github.com/hirosystems/stacks-wallet-web/issues/2067#issuecomment-1019976710

**Comment by bogachevanton** [comment]
Here is another example of a transaction that has been hanging in the explorer for a month and periodically appears

https://user-images.githubusercontent.com/90133006/150810973-c73c0126-5914-42a8-ac34-dd2574087daf.mp4

**Comment by markmhendrickson** [comment]
@beguene Should we revisit this now that the three issues you link from https://github.com/hirosystems/stacks-wallet-web/issues/1930#issuecomment-1011055425 have been resolved?

**Comment by beguene** [comment]
@markmhx Yes we can revisit this, but the answer will be the same as in [#1930](https://github.com/hirosystems/stacks-wallet-web/issues/1930#issuecomment-1011055425) and my comment above.

**Comment by markmhendrickson** [comment]
@bogachevanton @SarkarAbhijoy @314159265359879 have you seen this behavior again recently?

**Comment by SarkarAbhijoy** [comment]
> @bogachevanton @SarkarAbhijoy @314159265359879 have you seen this behavior again recently?

No, I haven't
