### ISSUE TITLE
NFT purchase has been pending for 2 days, 15 STX fee and still no progress

### ISSUE THREAD

**Issue by Meh-taverse** [blockstack/blockstack-app#1935]
I bought a Punk NFT Thursday and all my transactions are still pending, I increased the fees on all transaction. The first transaction i raised to 15 stx and still nothing hours later. 

any idea what I could do to help?

trans Id:0xfe34a6336fdf73364beef0dd2ecc574199daa620e00effb84767434e11aa49d7

**Comment by 314159265359879** [comment]
This transaction is send with a nonce 0
![image](https://user-images.githubusercontent.com/33360391/141660507-e7567e8b-7a8c-4d6b-8176-19576cdddbed.png)

Whereas the wallet nonce is now at 2
![image](https://user-images.githubusercontent.com/33360391/141660515-68a931d1-959d-4c1d-9b9a-d9effbe5f591.png)

Could be due to this bug: #1930 normally your wallet should not send transactions with a nonce that has already been send. nonces are used so miners know in what order to process your transactions and have to follow one by one. This transaction can never be mined. 

I also see you have several name pre-orders on the same account. You can only register one name to an account so you will have to transfer the name out of the account before you register the next one. It is easier to pre-order/register one name per public address.

**Comment by markmhendrickson** [comment]
It appears as though the transaction has confirmed by now: https://explorer.stacks.co/txid/0xfe34a6336fdf73364beef0dd2ecc574199daa620e00effb84767434e11aa49d7?chain=mainnet
