### ISSUE TITLE
Custom fee lower than 'Low' Fee Bug

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1944]
Related to PR:https://github.com/hirosystems/stacks-wallet-web/issues/1728
User was testing the Fee estimate PR
User wanted a custom fee which is lower than the 'Low' setting fee displayed
User was able to send the tx with the lower fee but when user wanted to send another tx,the standard fee was displayed as the first tx custom fee value which was 0.000072 STX as opposed to the standard actual fee which is 0.012876 STX
User was not able to select 'Preview 'icon as well 
Attaching the error console log and video for perusal

https://user-images.githubusercontent.com/38872890/141829163-d3eb33b1-c6e2-48f4-ac69-b8eccb38e8aa.mov

<img width="557" alt="Screen Shot 2021-11-14 at 9 29 42 PM" src="https://user-images.githubusercontent.com/38872890/141829214-de89ab4f-2720-4b89-a8a2-5aaab0705690.png">
<img width="1367" alt="Screen Shot 2021-11-14 at 9 30 36 PM" src="https://user-images.githubusercontent.com/38872890/141829216-0a9b166b-3445-433b-a3a4-8581631275d8.png">

**Comment by Eshwari007** [comment]
cc @fbwoolf

**Comment by fbwoolf** [comment]
@Eshwari007 I am not sure I understand this issue? It is expected behavior that a user can send a tx lower than the lowest estimate, so that is ok. A warning should just popup letting the user know it might fail. After sending that tx, you would not end up back at the send form. You would end up on the activity list, did that happen for you?

**Comment by Eshwari007** [comment]
@fbwoolf Yes,the tx went to the activity list so the first tx is all good .
This was the second tx after the first use case mentioned above,when I wanted to send a normal tx,noticed the standard fee was changed to my previous custom fee (seemed like cached) and the preview button didnt work.

**Comment by fbwoolf** [comment]
@Eshwari007 got it, thx for clarifying, so the state must not have cleared from the first tx ...I will take a look.

**Comment by fbwoolf** [comment]
@Eshwari007 I fixed this locally, how should I handle the issue on a feature branch? Should I just close it or keep it open and move to QA again once I push up the fix?

**Comment by andresgalante** [comment]
@fbwoolf Since the issue is open, I'd move it to QA to be retest before merging the PR #1857 

@Eshwari007 since the issue is directly related to the feature that we are building, I think it might be better make to write a comment on the same thread as the original PR so we can keep things in one place and they are easy to follow. I'd only open a new issue if it's unrelated. what do you think?

**Comment by fbwoolf** [comment]
> 
> I'd only open a new issue if it's unrelated. what do you think?

I agree, this would be easier for me as a dev bc typically the fixes are pretty minor if found bc of the new feature work.

**Comment by Eshwari007** [comment]
@andresgalante @fbwoolf sounds good.I love the idea of tracking it in one original PR,as it helps to identify /locate any recurring bugs in future as well.

**Comment by Eshwari007** [comment]
The issue was not able to be reproduced hence will be closing the ticket
cc @fbwoolf
