### ISSUE TITLE
Apply new app navigation

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#1947]
Testing WW version v2.20.3-dev.3.711
<img width="363" alt="Screen Shot 2021-11-16 at 9 39 22 AM" src="https://user-images.githubusercontent.com/38872890/142005752-b026670a-8d4f-4763-94e3-5d40788ad911.png">
This seems to be an issue when user selects Testnet only

When user navigates to mainnet,the logo is properly aligned
<img width="397" alt="Screen Shot 2021-11-16 at 9 39 51 AM" src="https://user-images.githubusercontent.com/38872890/142005903-d11d3d09-7ee0-4cf6-98ab-5e0b5759d5a3.png">

**Comment by markmhendrickson** [comment]
Good eye, though I suspect this may be desired behavior when there isn't enough horizontal space to show the logo, version and testnet label all side-by-side.

@eugeniadigon what do you think?

Let's also keep new visual bugs out of the backlog initially to start. 🙏

**Comment by ginny-d** [comment]
It seems that this bug _should_ be fixed with the new designs where the UI elements are slightly different and the logo is smaller, so I'm not sure if we want to do a fix for this at the moment:
<img width="489" alt="hover" src="https://user-images.githubusercontent.com/78865845/142266121-43638a2a-9b60-493b-ba97-fb8529528db8.png">

One solution to consider for edge cases would be to transform our logo in a 'responsive' shortened version:

<img width="489" alt="hover-1" src="https://user-images.githubusercontent.com/78865845/142266286-12ab6e9c-001c-423c-b678-658083b47e46.png">

**Comment by markmhendrickson** [comment]
I'm not seeing a separate issue filed already to update the app navigation UI to the latest in Figma, so I'm going to simply convert this one into that task so we can tackle all these changes together.

**Comment by markmhendrickson** [comment]
I'm noticing now that we actually have two new app navigation designs in Figma. This is the other one, and I believe the one intended for implementation since we want to show "useful" data (the currently selected username and address) instead of branding, which is covered by the extension's icon in the browser chrome. But @eugeniadigon perhaps you have a preference for showing branding here?

https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=604%3A10301

![image](https://user-images.githubusercontent.com/28991/144267020-fb7325b0-2d67-45c8-9ee3-04ca4b7317a3.png)

**Comment by ginny-d** [comment]
> I'm noticing now that we actually have two new app navigation designs in Figma. This is the other one, and I believe the one intended for implementation since we want to show "useful" data (the currently selected username and address) instead of branding, which is covered by the extension's icon in the browser chrome. But @eugeniadigon perhaps you have a preference for showing branding here?
> 
> https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%8FSpec?node-id=604%3A10301
> 
> ![image](https://user-images.githubusercontent.com/28991/144267020-fb7325b0-2d67-45c8-9ee3-04ca4b7317a3.png)

I'm not sure what was the line of thinking behind the different two options. 

Personally, I'd prefer a mix of both:
- Keeping the account and address big on top
- Adding fiat values only on each token balance

Not sure what's the value prop of having the big fiat value in USD on top - I relate that feature with portfolio kind of apps where users care the most about tracking their earnings and reading their portfolio total value on fiat. For a wallet, not saying it's not useful, but shouldn't be the main thing IMO. Open to discussion, though!

**Comment by markmhendrickson** [comment]
That makes sense to me. I'm putting in the design column so you can update this along those lines in Figma whenever you have a chance.

**Comment by markmhendrickson** [comment]
@eugeniadigon would you prefer @landitus took over here with the above Figma updates?

**Comment by ginny-d** [comment]
> @eugeniadigon would you prefer @landitus took over here with the above Figma updates?

Sure!
