### ISSUE TITLE
Prevent white screen

### ISSUE THREAD

**Issue by muhammad-usman56** [blockstack/blockstack-app#1986]
- https://user-images.githubusercontent.com/47473401/143281227-617a6d3c-863d-4f32-9ae3-fd7588ed5f1a.mp4

**Comment by markmhendrickson** [comment]
@Eshwari007 @timstackblock ever seen something like this by chance?

**Comment by Eshwari007** [comment]
@markmhx We have a few sec white screen when Send is selected -believe its related to the '`suspense`' according to Dev but will test this scenario out

**Comment by fbwoolf** [comment]
This isn't the send button, but the user is running a localhost app. We would need more information unless other users are reporting this issue?

**Comment by Eshwari007** [comment]
I tested the issue with STXNFT and the wallet worked just fine

**Comment by timstackblock** [comment]
I believe this is the white screen issue we saw earlier I was able to generate it on several instances not just send. I happens when I switch accounts and also appears briefly before contract calls. See my screen shot below of it appearing before a contract call if goes away after 1 second the use above is getting it for a longer period of time though.

<img width="1130" alt="Screen Shot 2021-11-30 at 12 33 45 PM" src="https://user-images.githubusercontent.com/49165468/144098320-c5c9decc-c474-4cde-9dd1-fabdc6510250.png">

**Comment by Eshwari007** [comment]
Yes,I am seeing it in todays build as I am looking into a PR and testing with testnet demo app
<img width="1100" alt="Screen Shot 2021-11-30 at 12 44 21 PM" src="https://user-images.githubusercontent.com/38872890/144100158-ebd7a07d-51eb-4abc-a397-82e59c68fdb0.png">
