### ISSUE TITLE
Improve unlocking time performance

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2014]
As reported by the Stackswap team as affecting lots of users. Could be several minutes. Happens in Firefox and Chrome across OS's. Happens intermittently, so perhaps a server-side issue?

**Comment by kyranjamie** [comment]
Related https://github.com/hirosystems/stacks-wallet-web/issues/1877

**Comment by markmhendrickson** [comment]
@kyranjamie is it your sense here that Gaia is just taking a long time to respond at times?

**Comment by kyranjamie** [comment]
Yeah. It'll work if it fails, but if it's just really slow, it could hang for ages.

**Comment by kyranjamie** [comment]
Made a PR here to track this https://github.com/hirosystems/stacks-wallet-web/pull/2023

**Comment by beguene** [comment]
This is partially addressed. To be picked up later if some users still face this issue.

**Comment by neorrk** [comment]
Still having the same issue.

**Comment by andresgalante** [comment]
@neorrk are you using Firefox or Chrome?

**Comment by neorrk** [comment]
> @neorrk are you using Firefox or Chrome?

Firefox. Every Chromium based browser works fine.

**Comment by markmhendrickson** [comment]
I'll look into the metrics we capture now about the timing we see for Firefox users.

**Comment by beguene** [comment]
@markmhx You can check the events below
- start_unlock
- complete_unlock

**Comment by zommuter** [comment]
Can anyone explain what the issue here is? Why does the unlocking take forever if it works at all on Firefox? This is horrible UX and probably one of the major reasons for a lack of users. Here's a screenshot from the profiler, though I guess you already know that the problem lies in `decryption-worker.js` i.e. src/shared/workers/decryption-worker.ts.

![image](https://user-images.githubusercontent.com/3686260/174955695-9f889432-0476-4eb5-ae3e-064e7126a939.png)

Not sure how reliable the profiler's line reference is, that would mean the `import argon2, { ArgonType } from 'argon2-browser';` already causes the problems 🤷‍♂️

**Comment by markmhendrickson** [comment]
@beguene can better explain the technically issues at play here

As far as [the data](https://mixpanel.com/s/2yNIv), below are the proportional breakdown of unlock durations by unique users for the past 30 days.

Perhaps surprisingly, Firefox actually appears to perform better than Chrome across the board. However, there are many fewer Firefox users than Chrome ones (2%).

## All

![Unlock durations](https://user-images.githubusercontent.com/28991/175057059-994beb94-3703-48e5-b543-4b2538f61b07.png)

## Chrome

![Unlock durations Chrome](https://user-images.githubusercontent.com/28991/175057081-06c4a5c7-ec40-4fd8-9582-237a203075d6.png)

## Firefox

![Unlock durations Firefox](https://user-images.githubusercontent.com/28991/175057103-07d1adaa-ac3c-4fd3-9d8a-65b8f075af49.png)

**Comment by beguene** [comment]
@markmhx The issue is that the unlock duration exists only if the unlock is successful and the user has waited enough time.
Users facing this issue won't be visible in this report. The proportion of users also might be off if most Firefox user gives up or can't complete the unlock.
To find them you can check the unique users with a 'start_unlock' without a 'complete_unlock'.

**Comment by beguene** [comment]
From the technical point of view, we removed the Gaia fetch months ago. Therefore Gaia fetch is not the cause of this slow unlock. 
As I argued before, the variance of the unlock duration between users and browser is due the argon2 lib. Our current parameters could be further tweaked to achieve a better performance for Firefox. We could reduce the iteration and increase the memory to keep the same time-space area and keep at least the same security. The memory allocated to argon2 should be increased to at least 128Mb (currently 32mb) and we could reduce the iteration without compromising security.
For reference the document going into more detail here https://www.notion.so/hiropbc/Argon2-Optimisation-f7132735a496499dbb94b045ccf37b52
As per the implementation strategy, you could do:
1. change the argon2 settings for all users and add a migration specific code
2. change the argon2 settings just for Firefox users and migration specific code for Firefox users only

**Comment by beguene** [comment]
@markmhx You can also create a proof of concept with tweaked param and give them to the affected users before committing anything

**Comment by kyranjamie** [comment]
I revisited this a week or so back and think it's fixed in https://github.com/hirosystems/stacks-wallet-web/pull/2666, which creates a WebWorker once, rather every time it tries to stretch the password

Awaiting team/community QA
