### ISSUE TITLE
tx_status-dropped_replace_by_fee

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/blockstack-app#2029]
In our Dapp domains.paradigma.global, user is preordering a domain name and paid it with the wallet.  Then transaction is not confirmed showing this message: tx_status-dropped_replace_by_fee
Attached file with error.  When trying to follow up the transaction, the transaction is not shown.
![IMG_4886](https://user-images.githubusercontent.com/32182666/144334775-156088a9-87c8-4fed-9be8-daa84d5f5397.jpg)

What kind of error is it? Anything to consider to track it in the dapp?.

**Comment by markmhendrickson** [comment]
Can you paste the exact transaction ID here for easy lookup in the explorer?

Also, what API resource are you using exactly to get and display this transaction status in the app?

**Comment by paradigma-cl** [comment]
We are capturing the resolve from this connect contract call
connect.openContractCall({
            //userSession: stacks_session,
            stxAddress: address,
            contractAddress: bns_contract_address,
            contractName: bns_contract_name,
            functionName: func,
            functionArgs: args,
            validateWithAbi: true,
            network: NETWORK,
            postConditions: post_conditions,
            attachment: attachment ? Buffer.from(attachment, 'binary').toString('hex') : undefined,
            appDetails: stacks_connect_options.appDetails,
            onFinish: resolve,
            //TODO- Uncomment this once onCancel is implemented in Connect. This is
            // removed for now because different places in the app might not expect
            // this behaviour. (There is currently no way to tell if the popup closed,
            // so it is leaving dangling promises for now.)
            //onCancel: reject
        });

This is the reference from the user:
I already registered the failed domains with another account and with the account that gave the error a different one. I presume that if I send you the transaction of the bigger debit you will get to it? (Not to tech savvy). Here is the first one.
https://explorer.stacks.co/txid/0xebc54efa2c23095d54ed6271dc0b6bec11131a623e2f3d3385ebe2310e47f44c?chain=mainnet
https://explorer.stacks.co/txid/0x852eade55f70760739fe36b1d81b118e5cc1c4a9d36c74c28a6cfb78d312eb4b?chain=mainnet

My comment: Not so clear, why the transaction sent that message.  Also the transaction number does not match the one in the picture.

**Comment by alihamze** [comment]
We're also seeing transactions get the `dropped_replace_by_fee` status. There doesn't seem to be any documentation on what actually causes this to happen but based on the naming I assumed it was due to a low fee. However it still occurs even if we 2x the estimated fee returned by `estimateContractFunctionCall`.

Additionally, the name implies the transaction was dropped but here's a transaction that had that status at 2021-12-15T13:56:54Z but has since succeeded. There's no record of the status change nor any way for us to know whether a given transaction with that status will eventually go through or not. https://explorer.stacks.co/txid/0xf2ecf94609f5e8af7e84b2a61ae266d0f62354faef9cf26e77b09dfe1fa8b262?chain=mainnet

This is another transaction that had that status at 2021-12-14T01:13:12Z but is now completed: https://explorer.stacks.co/txid/0x1fd3a3b477f805a6f49043c022423d144f23b24902f349323e9c38959e58c2fd?chain=mainnet

There are other times where the transaction does stay with that status such as `0xc78c5bf00f4c47d4f0820524896f0a5f920bf1014637a2f09d612d5297b12330`, `0x 5f862a697830f4762f879fd9abf98c3e9487fd1d5d90f4e422a49ed2fa4b54c3` (explorer returns a 404 response). This also has no indication of whether or not it will eventually end up going through.

**Comment by markmhendrickson** [comment]
@paradigma-cl @alihamze does this issue remain an active problem at the moment for either of you?

**Comment by alihamze** [comment]
@markmhx no this is no longer an issue for me

**Comment by andresgalante** [comment]
@markmhx I'll close this issue for now. please open it if you feel it's still relevant
