### ISSUE TITLE
Trigger analytics events for transaction signing activity

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2037]
- `view_transaction_signing`: When user views transaction signing screen (assuming not fully functional will basic page tracking already)
- `load_fee_estimates`: When fee estimate values load for screen (with properties `low`, `standard` and `high` with microstacks values as number for each e.g. `3000000` AND properties `low_cap`, `standard_cap`, and `high_cap` with microstacks values for maximum-value caps placed on these values in the UI _if cap is available **and** greater than each estimated value_)
- `submit_fee_for_transaction`: When user submits transaction for broadcast (with properties `fee` in microstacks for fee value used and `type` with string value `low`, `standard`, `high` or `custom` for indicating way in which user selected or set fee in the UI)

**Comment by beguene** [comment]
@Eshwari007 @timstackblock load_fee_estimates is actually now use_fee_estimation and use_fee_estimation_default_simulated if they are the default

**Comment by Eshwari007** [comment]
@beguene Am testing the above in #2150 but cant seem to see Okcoin in the integration
<img width="436" alt="Screen Shot 2022-01-24 at 12 17 27 PM" src="https://user-images.githubusercontent.com/38872890/150832143-3f88666e-4c01-41be-8f1c-a2fd3520af23.png">

**Comment by Eshwari007** [comment]
@beguene Test passed but few clarification:


<img width="530" alt="Screen Shot 2022-01-24 at 3 34 36 PM" src="https://user-images.githubusercontent.com/38872890/150860471-ea6fc9a4-7dc9-4f78-85ab-4c15aa5b4828.png">

- use_fee_estimation_default_simulated did not populated fee values in it raw data such as low 0.5  STX,standard 0.75 STX and high is 2 STX values. Was this intentional?



<img width="1144" alt="Screen Shot 2022-01-24 at 3 32 36 PM" src="https://user-images.githubusercontent.com/38872890/150860667-f700441f-eb48-496b-bd84-764ee7c3eca8.png">


- When a transaction was signed with one tx ( i just send tx between two accounts),noticed several bunch of view_transaction_signing were populated,they were all similar hence was wondering if duplicates were thrown while the tx send activity was performed.

**Comment by beguene** [comment]
@Eshwari007 
1. "use_fee_estimation_default_simulated did not populated fee values in it raw data such as low 0.5 STX,standard 0.75 STX and high is 2 STX values. Was this intentional?" 
Yes since it's the default, I did not add it, we could add it if needed.

2. Yes that is an issue, it's triggered multiple times because the app renders the page multiple times 😞

**Comment by Eshwari007** [comment]
> @Eshwari007
> 
> 1. "use_fee_estimation_default_simulated did not populated fee values in it raw data such as low 0.5 STX,standard 0.75 STX and high is 2 STX values. Was this intentional?"
>    Yes since it's the default, I did not add it, we could add it if needed.
> 2. Yes that is an issue, it's triggered multiple times because the app renders the page multiple times 😞

Thanks @beguene ,will create a ticket for the second issue
