### ISSUE TITLE
Add OkCoin Fiat Onramp

### ISSUE THREAD

**Issue by beguene** [blockstack/blockstack-app#2105]
Now that the production endpoint is ready, this task is to update the code, switch on the config.

**Comment by beguene** [comment]
@Eshwari007 @timstackblock You can try okcoin in production now.

**Comment by Eshwari007** [comment]
Great,will keep you posted with my findings

**Comment by timstackblock** [comment]
Thanks @beguene the link in the upper left corner that says hiro opens to a blank page.

<img width="1140" alt="Screen Shot 2022-01-05 at 11 12 32 AM" src="https://user-images.githubusercontent.com/49165468/148250582-7dfd39e4-a8a3-472a-8c05-958aa609c2f7.png">

<img width="1342" alt="Screen Shot 2022-01-05 at 2 34 19 PM" src="https://user-images.githubusercontent.com/49165468/148277791-21690c89-1226-4224-8c81-63949103c71b.png">

**Comment by timstackblock** [comment]
The summary page doesn't seem to add the fee into the total cost, either I am getting charged $26 for a $1 fee and getting $25 worth of STX or I am getting $24 worth of STX and the $1 dollar fee makes it $25 I can't get charged a $1 fee and still get $25 worth of STX for $25.

<img width="415" alt="Screen Shot 2022-01-05 at 1 23 14 PM" src="https://user-images.githubusercontent.com/49165468/148276960-ee13b335-b68c-4aef-9cf5-340cff3925de.png">

**Comment by timstackblock** [comment]
When I purchase STX I get a link to view my transaction in the explorer but once I click that link it doesn't take me to my transaction I just go to the explorer in general.

Video of the issue https://somup.com/c3VhqvZizx



<img width="1024" alt="Screen Shot 2022-01-05 at 2 16 15 PM" src="https://user-images.githubusercontent.com/49165468/148277483-d17e3d3c-a94c-4a1b-bbf8-ae588b622804.png">


<img width="1324" alt="Screen Shot 2022-01-05 at 2 32 46 PM" src="https://user-images.githubusercontent.com/49165468/148277612-f5e9dc29-8cbb-4305-91c6-a244392a1771.png">

**Comment by Eshwari007** [comment]
> The summary page doesn't seem to add the fee into the total cost, either I am getting charged $26 for a $1 fee and getting $25 worth of STX or I am getting $24 worth of STX and the $1 dollar fee makes it $25 I can't get charged a $1 fee and still get $25 worth of STX for $25.
> 
> <img alt="Screen Shot 2022-01-05 at 1 23 14 PM" width="415" src="https://user-images.githubusercontent.com/49165468/148276960-ee13b335-b68c-4aef-9cf5-340cff3925de.png">

Believe the fee deduction is applied to the Stacks as notice the value in Pending activity differ to the values on
<img width="815" alt="Screen Shot 2022-01-05 at 2 53 53 PM" src="https://user-images.githubusercontent.com/38872890/148280506-91f1e2a4-b5f2-417a-ad79-5ed2735b8036.png">
 STX received on Okcoin

**Comment by Eshwari007** [comment]
**Findings:**

- Yes, agree with the explorer link which brings to general mainnet explorer page rather than the dedicated tx page.
- User with existing google account was able to login to Okcoin smoothly

- New users have issues identifying their identity as USA is missing from country of residence
<img width="735" alt="Screen Shot 2022-01-05 at 3 03 19 PM" src="https://user-images.githubusercontent.com/38872890/148281613-38da6b05-6c01-477f-ba19-0c58fac7bed2.png">

- However when user logs out and sign in back,Okcoin request to set up the account and notice 'United States' listed.This can be cumbersome for new user,we may need to inform Okcoin on the issue.

<img width="1295" alt="Screen Shot 2022-01-05 at 3 05 31 PM" src="https://user-images.githubusercontent.com/38872890/148281884-30155c19-0c92-4ffc-bb4c-5c6379f95854.png">


- Signing in as an user via Telegram work,we may need to link our phone number with our account via authenticator app 

- We may need to reword 'US users can purchase STX quickly with USD' under Okcoin to match up to Transak description

<img width="373" alt="Screen Shot 2022-01-05 at 3 21 18 PM" src="https://user-images.githubusercontent.com/38872890/148283821-aa0ae8b4-a030-458f-8b22-0b4f0434371e.png">

**Comment by timstackblock** [comment]
@GinaAbrams giving you a heads up on some of the things we are seeing on the Okcoin fiat onramp side so far, so you don't get surprised when it goes live next week.

**Comment by Eshwari007** [comment]
Posting the feedback we have received from Okcoin here for visibility:
Please find below our comments:

**1. New users have issues identifying their identity as USA is missing from country of residence**
We cannot support users from US as a country since our payment processor has not onboarded okcoin for US entity. We have plans for integrating with paypal in future after which we will be able to support Hiro wallet for US users.

**2. The fee calculation is not included in the total**
The fee is part of the amount purchased. We have a enhancement filed to remove the total which will be pushed in production by Monday

**3. The explorer link is not working correctly**
Our team has requested guidance to understand how to redirect to the exact transaction. Adding @Tom from our engg team for any further clarifications needed here. **@beguene has already provided the clarification in regards to the explorer link**

**4. Hiro label shall redirect to hiro website**
I believe this is a new request and will be pushed with the Monday release.

**Comment by Eshwari007** [comment]
3.The explorer link is not working correctly
This is yet throwing an error as its directing to https://www.okcoin.com/errorpage.html

4.Hiro label shall redirect to hiro website
This is yet throwing an error as its directing to https://www.okcoin.com/errorpage.html






cc @beguene @timstackblock @andresgalante

**Comment by Eshwari007** [comment]
Tested the links which were provided by Okcoin team
Observations:
Link to Hiro page: The first link to the Hiro page was working fine in their link 

Link to Stacks Explorer: The second link upon the transaction in their page which directs to our explorer, didn't quite worked well : **https://explorer.stacks.co/address/SP2TKT72WAM648KGTH1APMKM33M1CNX8PA63CTZRR?chain=testnet**
`SP` is mainnet and the URL link pointed to testnet instead of mainnet. When I switched the network to mainnet I was able to view the tx and etc details, it did not land on mainnet directly for me.


2 Observation testing with our Fiat Onramp PR:

Link to Hiro:

https://user-images.githubusercontent.com/38872890/149576894-9f68e054-cedb-4801-8fa4-b11ecd22fb33.mov



Link to Explorer:

https://user-images.githubusercontent.com/38872890/149576915-792a0915-ca3f-419f-ac77-07430c50f153.mov

cc @beguene @timstackblock @andresgalante

**Comment by Eshwari007** [comment]
We can definitely send the above video to the Okcoin team or would be glad to sync up over a call to explain the issues that we are seeing from our end. Also used the PR from https://github.com/hirosystems/stacks-wallet-web/pull/2106 to test the scenarios above.

**Comment by beguene** [comment]
Thanks @Eshwari007 I will communicate your findings to them today.

**Comment by beguene** [comment]
@Eshwari007 I just made a fix, can you please check again ?

**Comment by Eshwari007** [comment]
@beguene Tested the Hiro page redirect. Yet receiving a similar error as previous

https://user-images.githubusercontent.com/38872890/149979735-17f06c55-9c0f-4870-9417-0e86b41b23ce.mov

**Comment by beguene** [comment]
@Eshwari007 Can you please check again ? It should work now.
