### ISSUE TITLE
Prevent transactions from remaining in submitted state

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack-app#2115]
Note from user: It happened again, for a different transaction.  So now I see two of them in the "submitted" bucket.  A second attempt gets them to go through, but they don't clear out from the submitted section.

https://explorer.stacks.co/txid/c9923658fcc9627edcdd27a90d45af490f1b20eacc63ec736364a7915ea88c02?chain=mainnet&submitted=true 
https://explorer.stacks.co/txid/3ad4049776a1e99a6bf5c2d7d4081754bcb65968d5760ba3d15249c5ffb1f4b9?chain=mainnet&submit
![image](https://user-images.githubusercontent.com/30627583/148827023-77c060a7-f816-4b8f-9a90-474029e5f325.png)
ted=true

**Comment by beguene** [comment]
Thanks @GinaAbrams, just to clarify, do they always stay in the submitted section or do they stay for some long time then disappear ?
@andresgalante This is also part of the bigger improvement that I talked about yesterday : improving UX for the activity list regarding. see #2119

**Comment by caoer** [comment]
@beguene @GinaAbrams we found the same issue if the transaction is in -13 state. `DroppedStaleGarbageCollect = -13`
tx id in the mempool:
```
0xD469046DD573720DB9384D8D887558412C749AFD55785CDE7038559354405799
0xC0895850599C47A51949A2549E693CE664713B103DCA4C2156F0DCE45F89278C
0x83B4BB531FA153A2BE58BC6BA4ACC69A92FCE15A2B4DA1E4628756D99E43C6B7
0x0ADFF7D3BB44CF3A1E644CD92BE4E358959B00687AC2E8C6CC65BAD7AB3D3248
```

**Comment by sconedrag** [comment]
Got a similar issue trying to push through alex lottery reveals. Transactions submitted with 0.01STX stay "submitted", however the same transaction with the fee set to 0.01001STX goes into the mempool. I alternated between 0.01STX and incrementally higher fees (0.011, 0.0101, 0.01001, etc) and every tx with a fee of 0.01STX stays submitted while all the other ones went into the mempool.

**Comment by 314159265359879** [comment]
I think "stay in submitted" happens when the transaction is send with a fee that is to low. When I try to send a STX transaction with a fee lower than 0.00018 STX the web-wallet will give an error/fail warning. I suspect this validation is missing for (some) contract calls.

![image](https://user-images.githubusercontent.com/33360391/153727188-853a96b6-ed07-47d4-8f2d-20b66edbb3b4.png)

An unsuspecting user can't get any transactions processed after such a "submitted" transaction because the nonce on subsequent transactions will be off. 
Example Account **nonce 66**
First transaction send is with fee 500 uSTX, stays in submitted (**nonce 67**)
Second transaction send with 1000 uSTX does go to the mempool (**nonce 68**)

Now there is a nonce gap (67) in the mempool transactions so 68 and any subsequent transactions can not be processed unless the user knows about the nonce gap and is able to fix it. 
What makes this issue even more of a problem is that it does not expire like a transaction in the mempool. The user will have to clear the cache/reset the wallet.

**Comment by 314159265359879** [comment]
Hero Gamer also confirmed these is reproducible. It is currently possible to confirm transactions (contract calls) that have fees to low for the network to accept them and then they stay in submitted. (a) It is not possible to increase the fee for these transactions and (b) nonces are likely to be off afterwards. 

![image](https://user-images.githubusercontent.com/33360391/154719274-deb7d810-b42f-46f3-baa1-2a50ead2bbdd.png)

**Comment by markmhendrickson** [comment]
@GinaAbrams @314159265359879 @sconedrag @caoer Have any of you seen this behavior again recently, and if so, with how much frequency?

**Comment by sconedrag** [comment]
@markmhx I still get it sometimes with a 0.0005 fee. When it happens I usually just resend with 0.0006 and that goes through. It's maybe every 4-5 weeks.

Edit: Just happened today, and I needed to up the fee to 0.0007

**Comment by andresgalante** [comment]
@sconedrag this is strange since we shipped a minimum fee cap that is higher than 0.0005. What version of the wallet are you using?

**Comment by sconedrag** [comment]
v3.7.0. What's the new min fee cap?

**Comment by andresgalante** [comment]
Caps are here:
https://github.com/hirosystems/stacks-wallet-web/blob/dev/config/wallet-config.json#L13

**Comment by sconedrag** [comment]
Ah got it. These are the suggested Low/Med/High values right? Does it actually gatekeep any txs with Custom fees lower than those values?

**Comment by andresgalante** [comment]
These are the low caps in case the suggested one is too low for the tx to go through. It doesn't do anything to custom fees.

**Comment by koz-btc** [comment]
I am having the same issue but doesn't really seem related to the fee I used, since it's really higher than the caps (I've used 0.12STX for example). 

Happened to me on two different wallets, one on mainnet and other on testnet. The only way I have for making them dissapear is removing the account and logging in again (using the seeds).

The transactions are not broadcasted, or at least they don't enter the mempool, they are submitted but not pending.

![Screenshot from 2022-05-08 21-25-02](https://user-images.githubusercontent.com/104938638/167330781-ea3d0aeb-da08-4c90-92fa-7103e674b969.png)
![Screenshot from 2022-05-08 21-08-49](https://user-images.githubusercontent.com/104938638/167330785-63d8c887-b806-4966-ae8b-875edaf548dd.png)

**Comment by markmhendrickson** [comment]
@koz-btc Thanks for this additional report 🙏  If you visit your wallet's address page on the explorer, do you see these transactions appear there at all? Or are they simply missing?

**Comment by koz-btc** [comment]
@markmhx they are simply missing. Also when I click on them on the wallet, they take me to a "Transaction not found" page.

**Comment by Hero-Gamer** [comment]
Hi @koz-btc 

Thanks for sharing your wallet address. I had a look your tx history. Like you mentioned the tx hasn't been broadcasted to the public mempool. 

Typically of the "submitted" issue I've seen in the past are due to too low fee. Or perhaps very quick consecutive attempts pressing confirmation button. So I'm slightly surprised you'd have that issue when fee is 0.12stx. 

For the mainnet one, I see you are currently on Nonce 1 for that address. 
(previously you made one successful Nonce 0 "claimStx" tx)
 
A few questions if you don't mind: 
Q1. Did you attempt the BNS "name-preorder" tx quite soon after that "claimStx" tx?
Q2. Do you remember what nonce the "name-preorder" tx was set to?
Q3. Could you try again the same action of "name-preorder", and check what Nonce is the Hiro wallet  trying to set for you? And what fee is it suggesting you as "standard" option?

Thanks

**Comment by koz-btc** [comment]
@Hero-Gamer responses inline:

> A few questions if you don't mind:
> Q1. Did you attempt the BNS "name-preorder" tx quite soon after that "claimStx" tx?

Not at all, it was a few hours later.

> Q2. Do you remember what nonce the "name-preorder" tx was set to?

Cannot really remember, but I'm trying again on an new tx on the testnet.

> Q3. Could you try again the same action of "name-preorder", and check what Nonce is the Hiro wallet trying to set for you? And what fee is it suggesting you as "standard" option?

I've tried again with the testnet account. These are the suggested values by Hiro:

![Screenshot from 2022-05-09 10-05-20](https://user-images.githubusercontent.com/104938638/167416232-34e7f211-f385-49fd-aaa0-f872e64517d6.png)

![Screenshot from 2022-05-09 10-05-27](https://user-images.githubusercontent.com/104938638/167416246-d24eb1e7-24d7-4b69-9ca4-373214236b65.png)

(I've edited the response with values from a mainnet account, not testnet)

I can see the suggested nonce is zero, which is incorrect since some other transactions were some other previous txs on that account:

![Screenshot from 2022-05-09 10-07-51](https://user-images.githubusercontent.com/104938638/167416551-02d109c4-68ae-46b6-8aaf-7af42eb0c4f2.png)

**Comment by Hero-Gamer** [comment]
Hi @koz-btc 

I see the problem now. Hiro wallet mainnet address should be suggesting you Nonce 1, not nonce 0. So that "submitted" tx in your Activity, might be due to nonce error suggestion.

Would you be able to try attempt to send/press confirm that Nonce 0 tx you've shown above and let us know if the wallet is allowing you to send the tx? Or does it come up with a error message saying "nonce conflict"?

**Comment by koz-btc** [comment]
To provide additional information. My transaction above went through when I set the correct nonce manually. But after that, tried to perform another transaction on the same account using clarinet from command line (deploying a smart contract) and had the same problem, the nonce automatically used to broadcast the transaction is incorrect.

![Screenshot from 2022-05-09 11-28-13](https://user-images.githubusercontent.com/104938638/167492209-faaec5b7-0611-4fcf-8022-de1d07f8c003.png)

I have the hypothesis that the suggested nonce is gotten from the same origin from both hiro and clarinet (maybe a common API?), that is returning the incorrect nonce.
The difference is that Hire keeps the transaction in a submitted state locally on the browser, and clarinet for example just shows the error saying the nonce is not valid.

Hope this helps to debug the issue.

**Comment by markmhendrickson** [comment]
cc @fbwoolf since I believe you're working on resolving related issues atm

**Comment by fbwoolf** [comment]
> cc @fbwoolf since I believe you're working on resolving related issues atm
>
I am working on this, but what am I being cc'd on to respond to?

**Comment by markmhendrickson** [comment]
No need to respond, just bringing this onto the board as WIP alongside https://github.com/hirosystems/stacks-wallet-web/issues/2467 🙏

**Comment by fbwoolf** [comment]
I believe we can actually close this issue with the merge of: https://github.com/hirosystems/stacks-wallet-web/pull/2576

Fix for catching tx errors properly, so they don't become included in the submitted state, has now been included in the next release. https://github.com/hirosystems/stacks-wallet-web/pull/2569
