### ISSUE TITLE
Support loading state for asset picker in send modal

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-app#2235]
There seems to be an asset drop down issue on the fresh install. It works but not right after we install the extension all my automated Stella test are failing because the asset is not available in the drop down after a fresh install and clearing the cache.

This goes away after clicking through the app there seems to be something related to caching. The amount of time it takes to become clickable varies I have seen it take over a minute and I couldn't figure out why the drop down wasn't working in chrome. As you can see in the video in Brave it was a brief amount of time.

https://screencast-o-matic.com/watch/c3n2opVbjvb

**Comment by fbwoolf** [comment]
@kyranjamie you might be the best person to look at this tomorrow? Maybe related to changes around data fetching with `useTransferableAssets` but not sure why the bug would surface now?

**Comment by kyranjamie** [comment]
> Maybe related to changes around data fetching with useTransferableAssets but not sure why the bug would surface now?

Indeed, and this is made worse by the fact that this is a test wallet with _loads_ of balances.

Because:

1. It's a fresh install (there's no ReactQuery cache)
2. We've added rate limiting to the metadata endpoint
3. We decide whether or not an asset is transferable based on metadata result

@timstackblock if you were to wait on this page, does it eventually show the drop down?

I wonder how we can best address this. Perhaps we need to add a spinner there, while we're still waiting for some balances? 🤔   

Though, I do think this is quite an uncommon edge cause, _usually_ there will either be a cache, or they'll have fewer assets and it'll have loaded in time. We're already fetching the data when they land on the homepage. We could also hit the API a little bit faster to further lower the occurrence of this.

**Comment by Eshwari007** [comment]
Tested the issue with PR 2172 manually:

- Installed the extension with an account that has Stella account
- Uninstalled the extension with the same account
- Logged into the account
- On send form, noticed the below:

Quick observation: I surely can't see Stela token on the first attempt for asset dropdown but upon the second or third try they are being populated.It could be APi taken time to fetch the data as @kyranjamie mentioned above or purely cache issue

This is blocking automation as it waits for Stella tokens to be populated on the first try in order to run the integration test, can we try kicking it off a little later (automation test) or perhaps attempts to second and third try?
Am just thinking of a possible workaround for the issue.

cc @timstackblock @kyranjamie

**Comment by kyranjamie** [comment]
@Eshwari007 @timstackblock I've merged https://github.com/hirosystems/stacks-wallet-web/pull/2239 which should fetch it faster than before. Though it is still an expensive operation which, on initial wallet install, may take some time.

**Comment by andresgalante** [comment]
> Though it is still an expensive operation which, on initial wallet install, may take some time.

@kyranjamie does this have to be this way or should we open an issue to improve performance here on later iterations?

**Comment by kyranjamie** [comment]
One issue is that, even after it does load, the list doesn't re-rerender the dropdown list with the newly-found transferable assets. We can investigate this.

We can also request from the API team an endpoint that accepts a list of contract ids and returns all metadata, as we need this to know if an asset is transferable (and currently, we iterate through all balances to get it)

https://github.com/hirosystems/stacks-wallet-web/blob/0b5fb744853b67c8570e0a3f6f2f7b3cd4f5782f/src/app/query/tokens/fungible-token-metadata.query.ts#L44-L55

**Comment by timstackblock** [comment]
It's still slow on this PR we can separate this issue out and go live with Silver fox without the fix since this is taking some time.

**Comment by andresgalante** [comment]
@timstackblock what do you mean? if this is a new bug, are you suggesting introducing a regression with 3.2?

**Comment by andresgalante** [comment]
@landitus to think about a way to improve the UX

@saralab to create an issue on the API repo

**Comment by landitus** [comment]
Regarding the experience, here's the initial draft proposal to add the loading state inside the dropdown drawer. This is to indicate the list still needs to be populated while keeping the page interactive and actionable with the assets that are loaded. 

<img width="961" alt="Screenshot 2022-02-24 at 20 30 20" src="https://user-images.githubusercontent.com/239215/155594249-f85d6d8e-b2a4-4af0-ba85-d41b3c42f966.png">

Figma: https://www.figma.com/file/uWutVORXsNUqdrHS0F07jG/%F0%9F%93%A4-Send?node-id=405%3A7826

**Questions:**
- should we consider adding a state if the loading fails? Could we add a link to retry loading?
- what's the order of the assets displayed in here? Alphabetical, total amount or something else?

**Comment by markmhendrickson** [comment]
> should we consider adding a state if the loading fails? Could we add a link to retry loading?

+1 on adding a loading state and retry option. 

> <img width="189" alt="image" src="https://user-images.githubusercontent.com/28991/155679630-0d3fb91b-05cb-4018-9e60-7e404596e305.png">

Do we need a spinner image here instead of the circle? For expediency, we could also just now have an loading image / we could just display "Loading..."

To wit, "Loading assets..." would be more concise.

**Comment by landitus** [comment]
Here's the latest design, which addresses the latest comments. lmkwyt! For the loading spinner, I figured we could use the same we have in the Explorer

<img width="3708" alt="Asset picker" src="https://user-images.githubusercontent.com/239215/155738897-bde08c20-f446-4e80-b7f8-8d73b924d4bd.png">

Figma: https://www.figma.com/file/uWutVORXsNUqdrHS0F07jG/%F0%9F%93%A4-Send?node-id=425%3A785

Reference for the spinner:
https://user-images.githubusercontent.com/239215/155738969-37a85f89-4859-4855-a795-d56a4e8ad86a.mp4

**Comment by markmhendrickson** [comment]
LGTM 👍

**Comment by landitus** [comment]
This is ready for development
