### ISSUE TITLE
Add Developer Survey banner to Testnet

### ISSUE THREAD

**Issue by ginny-d** [blockstack/blockstack-app#2253]
From the Marketing team, we need help spreading the voice about our Developer Survey, and we could really use the help of promoting it in the wallet, in Testnet mode, so it reaches more developers.

This is the preview of the text to show:
<img width="489" alt="banner — full" src="https://user-images.githubusercontent.com/78865845/155157951-d2994007-e124-4737-9451-3103bfddecca.png">

It needs to link to survey.hiro.so . Ideally this would be displayed starting next week, until March 18th

The component can be found here: https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%90-Spec?node-id=516%3A7608

**Comment by kyranjamie** [comment]
We have a ["messaging config"](https://github.com/hirosystems/stacks-wallet-web/blob/dev/config/wallet-config.md) for use cases just like this in `./config`. I'd recommend we extend this feature to support the requirements of this message. 

They are:

- [ ] Adding a customisable link text (right now it just says _Learn more_)
- [ ] Adding support for message dismiss-ability
- [ ] Adding ability to target mainnet/testnet

**Comment by markmhendrickson** [comment]
I imagine we can skip "Adding support for message dismiss-ability" for now as well as "Adding a customisable link text" unless either is a trivial change.

"Adding ability to target mainnet/testnet" is key since we don't want to show this to all users on mainnet for a month.

@kyranjamie what's your t-shirt estimate here?

**Comment by kyranjamie** [comment]
If we skip dismiss-ability, `S` for the other two changes.

**Comment by ginny-d** [comment]
Please disregard this issue as we decided to close the survey submissions earlier than expected
Thank you

**Comment by markmhendrickson** [comment]
Since this feature is ready, I imagine we should proceed to release it for use with a future survey?

**Comment by ginny-d** [comment]
Yes good call, we may want to use it in the future

**Comment by andresgalante** [comment]
@markmhx can you please write instruction on how to QA this one

**Comment by timstackblock** [comment]
I don't actually see the message on the extension when I am on testnet. I am guessing this is because we no longer need the survey and the config is turned off, please advise?

<img width="1238" alt="Screen Shot 2022-03-21 at 10 10 37 AM" src="https://user-images.githubusercontent.com/49165468/159279114-1b24bd72-a092-41be-9fcf-df35ebb9253d.png">

**Comment by markmhendrickson** [comment]
@kyranjamie mind indicating how @timstackblock can set the configuration briefly for testing and then revert?

**Comment by kyranjamie** [comment]
We'd need to make another PR, adding back the config described in the JSON schema, and point the config to read from the PR.

**Comment by Eshwari007** [comment]
@kyranjamie Moving the ticket back to development as per your comment above in needing another PR
cc @timstackblock

**Comment by kyranjamie** [comment]
Closing this as developer survey has finished 🎏
