### ISSUE TITLE
Sign out from popup wallet isnt consistent with windows wallet

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/blockstack-app#2341]
Similar issue were reproducible on v3.6.0 

The user is trying to sign out from the popup wallet and was signed out successfully.
However, noticed the windows full wallet version was not signed out
The user then attempts to log in via the popup wallet but instead of signing into a wallet, the unlock screen appears

Both the popup and window version wallets should be signed out simultaneously
attaching the screen recording for perusal

https://user-images.githubusercontent.com/38872890/160894787-334362bf-dd8f-49ad-a330-5e4bb0912fb2.mov

**Comment by fbwoolf** [comment]
@kyranjamie dropping a note here bc it doesn't look like `signOut` is working. It hits the `OnboardingGate` and then routes to home (I think). I can come back to this but working on a different bug atm.

**Comment by kyranjamie** [comment]
Edit: Good find, Esh. I'm able to replicate this, but only on wallets with lots of accounts.

I suspect the issue here is that, when signing out, and the other frame reloads, the `chrome.storage` is immediately updated again by values in the other frame's state.

This issue only happens when multiple frames are open.

**Comment by fbwoolf** [comment]
I started looking into this but not real familiar with the new code involving `chrome.storage`.

**Comment by markmhendrickson** [comment]
@Eshwari007 can you confirm how many accounts you have in your wallet when this problem appears?

**Comment by fbwoolf** [comment]
@markmhx I can reproduce this with only 2 accounts.

**Comment by Eshwari007** [comment]
> @Eshwari007 can you confirm how many accounts you have in your wallet when this problem appears?

I have abt ~290 accounts on my wallet.This is the test account.

**Comment by kyranjamie** [comment]
I'm also happy to take a look at this one. We might have to do something like close _other_ frames when signing out.

**Comment by Eshwari007** [comment]
@kyranjamie @fbwoolf 
In the past when the user signs out the pop-up wallet , both the full window view and popup wallet land on the onboarding first page as below:
<img width="383" alt="Screen Shot 2022-04-05 at 2 01 24 PM" src="https://user-images.githubusercontent.com/38872890/161820453-e10e0708-b776-4877-ad7b-3af94e5c6874.png">

However now, upon signing out both the wallet and pop-up window wallet close out all their frame. 
Is this the expected behavior?
cc @markmhx 

https://user-images.githubusercontent.com/38872890/161820607-973c51ba-0d84-46c2-9012-ed43719e3aba.mov

**Comment by kyranjamie** [comment]
This is expected behaviour. There are two things working together here:

1. If the pop up is open on a window, and that window closes, so does the pop up. Browser behaviour.
2. This PR introduces the behaviour where signing out closes all _other_ frames

In your example, you have the pop up open with the wallet in full screen. So, per point 1, both close. If you have the pop up open on a non-wallet page, it would not close.

Signing out is a fairly uncommon action. I've never signed out of my real wallet. Combine this with users who sign out, from the pop up, while they _happen_ to be on a full page wallet screen? How often would we expect that to happen, and what is the consequence?

**Comment by Eshwari007** [comment]
> This is expected behaviour. There are two things working together here:
> 
> 1. If the pop up is open on a window, and that window closes, so does the pop up. Browser behaviour.
> 2. This PR introduces the behaviour where signing out closes all _other_ frames
> 
> In your example, you have the pop up open with the wallet in full screen. So, per point 1, both close. If you have the pop up open on a non-wallet page, it would not close.
> 
> Signing out is a fairly uncommon action. I've never signed out of my real wallet. Combine this with users who sign out, from the pop up, while they _happen_ to be on a full page wallet screen? How often would we expect that to happen, and what is the consequence?

As per @kyranjamie Use case above, the test is passed. Will move it back to development if any behavior tweaks needed from @markmhx

**Comment by markmhendrickson** [comment]
This behavior looks fine to me. No need to make more tweaks 👍
