### ISSUE TITLE
Support increase fee for Ledger

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2345]
When increasing the fee for a transaction, we need to go through the ledger connection flow. This hasn't yet been integrated.

cc/ @markmhx @andresgalante how important is this, a must for initial release?

**Comment by andresgalante** [comment]
This is not necessary for the initial release, we'll implement increasing fee with Ledger after.

**Comment by landitus** [comment]
Here's the flow for increasing transaction fees, updated with Ledger support.

[Figma](https://www.figma.com/file/o0VSeFzhYI2GgnDcX0NPmU/User-lifecycle-flow?node-id=875%3A1436)

<img width="3938" alt="User lifecycle flow - Increase transaction fee v2" src="https://user-images.githubusercontent.com/239215/165794070-3a666b8a-361a-4905-96cd-f91d04a19dd2.png">

**Comment by landitus** [comment]
Here's a prototype and short video demo of the [flow](https://github.com/hirosystems/stacks-wallet-web/issues/2345#issuecomment-1112362135) 

The biggest divergence from the normal Ledger TX flow is that the Ledger modal cannot overlay in the same way since the Increase fees is already a modal. Given this situation, I've mocked a transition between modals instead. Biggest UX question is what does the X close button on Ledger modal do?

- A. Go back to transaction fees modal (as seen in the prototype)
- B. Abort the flow, close modal and you see the page below: Activity

[Figma prototype](https://www.figma.com/proto/M3EmplplSgZtM9FYHTtlqC/%232345---Ledger---Increase-fee?page-id=0%3A1&node-id=1%3A7&viewport=337%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=1%3A7&show-proto-sidebar=1)

<img width="1158" alt="CleanShot 2022-04-29 at 16 33 29@2x" src="https://user-images.githubusercontent.com/239215/165965862-12cf6c88-778b-40ff-9d33-6c15e8686052.png">

https://user-images.githubusercontent.com/239215/165965989-2e545d1d-f0fd-4eec-a09e-4182bfb1547e.mp4

**Comment by markmhendrickson** [comment]
Perhaps if we have sequential overlay modal states (e.g. here with "Increase fee" first then "Connect Ledger"), all but the first view should have a back arrow option in the top-left corner?

It could still have a close option in the top-right corner for all views, which will simply close the overlay modal in general (e.g. here taking the user back to the home screen activity). That way the user has a clear way to either go back in the process or simply abort the process entirely.

**Comment by landitus** [comment]
> Perhaps if we have sequential overlay modal states (e.g. here with "Increase fee" first then "Connect Ledger"), all but the first view should have a back arrow option in the top-left corner?
> 
> It could still have a close option in the top-right corner for all views, which will simply close the overlay modal in general (e.g. here taking the user back to the home screen activity). That way the user has a clear way to either go back in the process or simply abort the process entirely.

Ok, that sounds good, so I've updated the prototype with this behavior. I think it's better now!

[Figma prototype](https://www.figma.com/proto/M3EmplplSgZtM9FYHTtlqC/%232345---Ledger---Increase-fee?page-id=0%3A1&node-id=1%3A14&viewport=241%2C48%2C0.5&scaling=scale-down&starting-point-node-id=1%3A14&show-proto-sidebar=1)

**Comment by fbwoolf** [comment]
@landitus is this ready for development?

**Comment by fbwoolf** [comment]
@landitus I think this is done being designed so I'm going to get started on it, but let me know if I am wrong. It seems like in your last comment it is done?

**Comment by fbwoolf** [comment]
@markmhx I'm questioning needing the back button on every ledger modal step here after working on this. It seems like it might be enough to provide it on the first `Connect` step to go back to the modal to increase fee, but once the user initiates connecting to ledger maybe just using the `X` to cancel out completely is simpler? Also, there is some funky stuff happening right now using the `X` button we need to fix before releasing.

**Comment by fbwoolf** [comment]
I am going to put up a PR that just has the back button on the first ledger modal to connect to see how people feel testing it. I think it is enough bc backtracking through the ledger flows isn't something we want to do imo. Right now, even if a user clicks on the `X` icon, it doesn't cancel out connecting or signing the tx on the ledger. For example, you still have to approve or reject the tx on the ledger if you close the tx on the details modal step.

**Comment by markmhendrickson** [comment]
cc @landitus on the design question above re: the `X` 👆

**Comment by landitus** [comment]
sorry for the delay @fbwoolf . The last time we reviewed the increase fee flow with @kyranjamie we realized this flow (as seen in the Figma) will not work on the widget since the Ledger can't be connected/accessed from an extension widget. So the next idea was to force this flow into a new tab and then try to improve the UX later. Though it's not ideal, it would allow the Ledger to be connected to the browser.  Open to any suggestions! Maybe I can take a fresh look at it again and see if another idea comes up.

**Comment by fbwoolf** [comment]
> sorry for the delay @fbwoolf . The last time we reviewed the increase fee flow with @kyranjamie we realized this flow (as seen in the Figma) will not work on the widget since the Ledger can't be connected/accessed from an extension widget. 
>
Yep, that is fine, I can force it to be full page but my question is also for full page view in the modal. I don't think we need the back button except on the first connect screen for ledger to go back to the increase fee form ...once the user has initiated trying to connect the ledger that sequence can be really fast and using the back button isn't ideal. I think just having them close the modal at that point is better?

**Comment by fbwoolf** [comment]
You can test it in full page view with the build in the linked PR.

**Comment by fbwoolf** [comment]
@landitus I think there is some weird behavior happening here even with the `X` button but it is the same with sending a tx in full page. If you try to cancel out of the modal the UI flashes and ultimately the ledger still asks you to approve or reject the tx. Maybe after the user clicks to `Connect` the ledger should handle things? Maybe the `X` shouldn't even be available on all steps?

**Comment by fbwoolf** [comment]
We should probably get @kyranjamie's feedback on this when he is back bc the `X` button has been left just as a route change ...it really doesn't perform any cancellation of the call to ledger, which might be intentional or not possible to do?

**Comment by landitus** [comment]
> Maybe after the user clicks to Connect the ledger should handle things? Maybe the X shouldn't even be available on all steps?

You are probably onto something here @fbwoolf. While building the initial flows with @kyranjamie we've seen out-of-sync issues on the Ledger hardware if a transaction is not completed on the Wallet UI. I think your idea of letting the hardware take over fixes this and if doable we should go for it! Let's see what @kyranjamie thinks as well!

**Comment by landitus** [comment]
Maybe we can show some clarifying hover message while we remove the affordance of the close/back buttons and the hardware takes over? 👀 

https://user-images.githubusercontent.com/239215/175377404-6f2a31e6-267a-4088-92cd-84909799d354.mp4

**Comment by fbwoolf** [comment]
> Maybe we can show some cool hover message like this while we remove the affordance of the close/back and the hardware takes over? 👀
> 
I love that idea! Looks really great. 🚀

**Comment by landitus** [comment]
Here's a revised flow where we now force the **Increase Fee flow** into a new tab so that the browser can interact with the Ledger device.

- [Figma](https://www.figma.com/proto/M3EmplplSgZtM9FYHTtlqC/%232345---Ledger---Increase-fee?page-id=51%3A4380&node-id=113%3A4379&viewport=-2075%2C333%2C0.25&scaling=scale-down&starting-point-node-id=113%3A4379&show-proto-sidebar=1)
- [Flows](https://www.figma.com/file/o0VSeFzhYI2GgnDcX0NPmU/User-lifecycle-flow?node-id=875%3A1436)

I've prototyped the **Happy path** and the **Transaction denied path**. Other states can be copied from the transaction flow. Also, the flows have been updated in Figjam with the branching logic "if it's a hardware wallet".

https://user-images.githubusercontent.com/239215/175534252-108df260-105f-4429-8d56-ce9b18b24199.mp4

**Comment by fbwoolf** [comment]
Thx @landitus I'll get these changes implemented today. 🙌

**Comment by fbwoolf** [comment]
Refactored this and tested it locally ...such an improvement imo.

**Comment by landitus** [comment]
I'm trying to test this build locally with my Ledger but I'm stuck here. I've updated everything (Ledger Live) reinstalled Stacks app (0.19) and still I get the out of date notice.

<img width="560" alt="CleanShot 2022-06-24 at 22 11 25@2x" src="https://user-images.githubusercontent.com/239215/175660669-8dd56554-1001-4733-a83f-2901744d31a6.png">

**Comment by fbwoolf** [comment]
> I'm trying to test this build locally with my Ledger but I'm stuck here. I've updated everything (Ledger Live) reinstalled Stacks app (0.19) and still I get the out of date notice.
> 

You likely aren't using the latest Stacks app from Zondax? You need to follow the test instructions here:
https://github.com/hirosystems/stacks-wallet-web/discussions/2451

**Comment by fbwoolf** [comment]
The latest build is actually `v0.22.7`: https://github.com/Zondax/ledger-blockstack/releases

**Comment by fbwoolf** [comment]
I think it might be better to change the wait message to `Ledger device in use` bc during the connect process you really just have to wait for a response (success or failure), but with the tx signing you do have to approve or reject the tx on the device. So, looking for a more generic message that works for both?

![Screen Shot 2022-06-25 at 11 55 30 AM](https://user-images.githubusercontent.com/6493321/175783384-4e568872-9902-4454-84b1-38b9da5d2ed1.png)

EDIT: Or, maybe `Wait for Ledger device`?

**Comment by fbwoolf** [comment]
This is all working great except one thing I'm seeing with routing I haven't been able to figure out yet, but still looking into it. When you go from the increase fee form > connect ledger ...the activity list disappears on the home page behind the modal. It must have something to do with the nested routes but not sure yet.

![Screen Shot 2022-06-25 at 12 16 26 PM](https://user-images.githubusercontent.com/6493321/175784064-3a1abeda-7561-417b-8292-4491d41412db.png)
