### ISSUE TITLE
Browser support warning for Ledger feature

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2347]
- [Figma](https://www.figma.com/file/VQPOPkkrfVcf0BEd9kz3HZ/%232275---Ledger%3A-Onboarding-%2B-Transaction-signing?node-id=851%3A19803) 
- [Figma prototype](https://www.figma.com/proto/VQPOPkkrfVcf0BEd9kz3HZ/%232275---Ledger%3A-Onboarding-%2B-Transaction-signing?page-id=507%3A12473&node-id=851%3A19803&viewport=317%2C48%2C0.5&scaling=scale-down&starting-point-node-id=849%3A19111&show-proto-sidebar=1)

Firefox won't be supported initially. This is because Firefox doesn't support WebUSB and WebHID libraries, which is what the Wallet uses to connect the Ledger device to the browser. The lack of USB connection support in Firefox has been ack by the Ledger team: https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md#what-about-firefox-then

This needs to be communicated in the UI.

**Comment by landitus** [comment]
We should prompt for a message when the user tries to connect the Ledger during the onboarding, while using Firefox. [Check prototype](https://www.figma.com/proto/VQPOPkkrfVcf0BEd9kz3HZ/%232275---Ledger%3A-Onboarding-%2B-Transaction-signing?page-id=507%3A12473&node-id=851%3A19803&viewport=317%2C48%2C0.5&scaling=scale-down&starting-point-node-id=849%3A19111&show-proto-sidebar=1)

![Browser not supported](https://user-images.githubusercontent.com/239215/161574880-89c0955a-a8fb-4bb4-a96d-07452e7bfed1.png)

@sjwhitely Wanted to loop you in on this limitation, and also for the message copy. What do you think of the following? 
- We can keep it more vague: saying the `Browser is not supported`. 
- Or we could be more clear that this is not a limitation with Ledger. Maybe `Ledger integration is not supported in your browser` Given the root cause

**Comment by sjwhitely** [comment]
@landitus current copy looks great to me - I wouldn't suggest making any edits!

**Comment by landitus** [comment]
Thanks @sjwhitely !
@kyranjamie This is ready.

**Comment by kyranjamie** [comment]
Done
