### ISSUE TITLE
Not able to connect with the new 3.7.0 and .btc username

### ISSUE THREAD

**Issue by pradel** [blockstack/blockstack-app#2354]
With the new Hiro wallet version 3.7.0, I am not able to connect to websites anymore for account that owns a .btc username. Connecting with an account that does not own an username is working fine.

This is the error I am seeing in the console:
<img width="493" alt="Screenshot 2022-04-07 at 15 41 35" src="https://user-images.githubusercontent.com/5749437/162214592-cac96f0a-0b8f-47c0-b117-c8d176c6bb3e.png">

The ones I tried:
- Arkadiko
- Frens
- Alex

**Comment by markmhendrickson** [comment]
I just tried with my `mark.btc` name and authenticated to Arkadiko fine. I wonder if it's a particular type of .btc name 🤔

https://user-images.githubusercontent.com/28991/162223272-d380cc6c-b84a-4214-af19-44be8e50ee49.mov

**Comment by markmhendrickson** [comment]
@pradel Do you have another .btc you can try to see if you get the same result?

**Comment by pradel** [comment]
I tried with 2 different ones and got the same issue

**Comment by markmhendrickson** [comment]
@janniks and I are thinking that this issue may get resolved by the work being done to remove BNS checking from authentication entirely here: https://github.com/hirosystems/stacks-wallet-web/pull/2333

He's going to prepare a test build and let you know here when it's ready for you to try with these .btc names that are failing for you.

**Comment by janniks** [comment]
This is a strange one, and really two issues...

- It seems _for some accounts_ the username is NOT passed into the authResponse payload. These will succeed, because they essentially skip the username matching check. I couldn't figure out when it's passed and when it isn't — might need some help from the wallet team on this if we want to figure this out.
- The username matching uses the `iss`/[`did`](https://www.w3.org/TR/did-core/) part of the payload. This currently uses the `btc-addr` version of the address of the `dataPrivateKey`. BUT the registrar/API response's `address` (aka `owner`) includes the public address (the same address as shown in the wallet UI). So matching will fail even when it shouldn't, as it's comparing two different addresses of the same owner.

At first glance, it "looks" like the username matching check should have never worked. It's hard to track down the history of when API+stacks.js would have had matching addresses at the same time, if that was ever the case...

**Comment by markmhendrickson** [comment]
I'm closing this out since I believe it'll be resolved on the app's side with a Stacks.js upgrade to include https://github.com/hirosystems/stacks.js/pull/1230. cc @janniks
