### ISSUE TITLE
Upgrade Connect packages

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2375]
Tracking updating Connect packages.

**Comment by Eshwari007** [comment]
@fbwoolf Can you kindly specify the test steps which is required to verify this ticket? Seems like it has been closed along with PR :2374. Does testing PR: 2374 will knock this ticket as well?

**Comment by fbwoolf** [comment]
The two issues you have been testing are closed (they have already been merged into dev). I tested them myself before merging. They are only in the QA column to test them again once we create a release PR. I did not include test steps on either issue for that reason.

**Comment by Eshwari007** [comment]
Ok, will test them both again in Release PR when it's ready.

**Comment by fbwoolf** [comment]
The only change you will likely be able to test here is in the test-app download modal. Upgrading the Connect packages fixes the broken modal illustrations: https://github.com/hirosystems/connect/pull/207

If those load, then this issue passes.

**Comment by fbwoolf** [comment]
I think it would be a better process if the dev assigns you to their issue if/when they need your help to do QA?

**Comment by Eshwari007** [comment]
We can surely talk more about this during our meeting with the team but as per my understanding if the issue is on QA's queue-we (Tim and myself) are allowed to pick it for testing. Dev can always feel free put the ticket back to 'Review' if they feel the issue is not quite QA ready.

Would be curious to hear on team's input on the process as well
cc @timstackblock @andresgalante

**Comment by fbwoolf** [comment]
I don't understand spending time doing QA on a PR that has been merged into dev and closed the issue. The process you describe does not make sense to me for a closed issue.
