### ISSUE TITLE
Prevent transferred usernames from showing in accounts list

### ISSUE THREAD

**Issue by pradel** [blockstack/blockstack-app#2394]
With the new release 3.7.2, I saw that the wallet shows transferred .btc names. Previous versions were only showing the address without the username correctly.

Both usernames shown in the following screenshot has been transferred to other addresses.
- gregogun.btc is now owned by SP1F48HCD4SP4HT8BHQPXZ35615764KC80ACNMBDZ https://stacks-node-api.mainnet.stacks.co/v1/names/gregogun.btc. But shown for my address SP2619TX0ZEZQ9A4QMS29WH1HKA86413NZHDZ2Z04.
- same issue for blogging.btc
![Screenshot 2022-04-29 at 18 39 38](https://user-images.githubusercontent.com/5749437/165987678-792494ee-8abe-4a33-9b91-932846c610bd.png)

**Comment by Hero-Gamer** [comment]
Having EXACT same issue! I can't log into marketplaces with the right account now. 
Takes me to the already transferred wallet address. 

Been like this for maybe little less than 24 hours now.

**Comment by Jamil** [comment]
This is a huge issue for us; just had someone transfer an NFT to a BNS address, and it resolved to an address which *previously* owned that BNS. Luckily that person owned both wallets, but could have been a lot worse. 

As @Hero-Gamer mentioned above, it’s also affecting logins for some people.

We’re disabling transferring NFTs by BNS for now and some temporary stopgaps, but it’d be great to get an update on triaging / paths to resolution here.

**Comment by markmhendrickson** [comment]
@pradel Mind logging out of the wallet and back in, to see whether this might be due to a caching issue as suspected previously with https://github.com/hirosystems/stacks-wallet-web/issues/1880?

@Hero-Gamer I'm a bit unclear on what you mean by "Takes me to the already transferred wallet address." since the _address_ per se shouldn't change for your account, regardless of the BNS username associated with it. 

Which marketplaces are you using exactly, and mind sharing a screenshot of what you see there that indicates a different address (alongside what you see in your wallet)?

**Comment by markmhendrickson** [comment]
cc @janniks @kyranjamie in case they have insight on why recent code changes may have caused previously transferred usernames to start appearing in the accounts list again

**Comment by pradel** [comment]
@markmhx tried to reset the wallet and login again and the same issue is happening so definitely not a caching issue.
Iirc 3.7.1 was showing the correct addresses instead of usernames.

**Comment by markmhendrickson** [comment]
This appears to be an API-borne problem in that https://stacks-node-api.mainnet.stacks.co/v1/names/[NAME] isn't returning the right address for usernames once transferred. It continues to return the address of the previous owner. cc @rafaelcr @zone117x @saralab @aulneau

**Comment by pradel** [comment]
@markmhx that's interesting, if you open this link in your browser https://stacks-node-api.mainnet.stacks.co/v1/names/gregogun.btc, and then hit refresh (cmd + r) multiple times (like around 20), you will see that the endpoint sometimes returns `SP1F48HCD4SP4HT8BHQPXZ35615764KC80ACNMBDZ` and sometimes returns `SP2619TX0ZEZQ9A4QMS29WH1HKA86413NZHDZ2Z04`.

**Comment by rafaelcr** [comment]
@pradel we were in the process of testing a new API version, so traffic was being split between versions 3.0.3 and 4.0.0-beta, and the newer version seems to be the one with the regression. This is why you were seeing flappy responses.

I've just disabled this split while we investigate this BNS issue, so you should be seeing the correct owners of BNS names again. Please let me know if this isn't the case cc @markmhx

**Comment by markmhendrickson** [comment]
Thanks @rafaelcr! Has the disable been rolled out to production? I am indeed still seeing the issue with one username used for querying in particular.

**Comment by Hero-Gamer** [comment]
> @pradel Mind logging out of the wallet and back in, to see whether this might be due to a caching issue as suspected previously with #1880?
> 
> @Hero-Gamer I'm a bit unclear on what you mean by "Takes me to the already transferred wallet address." since the _address_ per se shouldn't change for your account, regardless of the BNS username associated with it.
> 
> Which marketplaces are you using exactly, and mind sharing a screenshot of what you see there that indicates a different address (alongside what you see in your wallet)?

Hi Mark, 

I just mean generally speaking what's going on here same as what everybody else been saying. 
To clarify exactly my example & experience: 

**Say I have two wallets**
1) Wallet 1 - hello.btc - SP1...ABC - hiro web wallet v3.7.2 on Microsoft Edge - Seedphrases set 1
2) Wallet 2 - world.btc - SP2...XYZ - hiro web wallet v3.7.2 on Chrome - Seedphrases set 2 (i.e. different key)
*world.btc BNS domain was previously bought & registered with SP1...ABC, but transferred (using btc.us transfer function) some months ago to SP2..XYZ address.

**For the past few days, intermittently (but for the majority of the time).**
* I'd open Edge and enter password to login hello.btc SP1...ABC, after logging in Hiro web wallet would display I'm logged in as **world.btc with SP1...ABC**
* I'd go to an NFT market site such as Gamma.io/Byzantion
* Attempt to **Connect wallet with Wallet 1 with SP1..ABC.**.
* Pop-up would show me a list of accounts to connect to, but it would display **world.btc with SP1...ABC**  (which is incorrect). I would select it nevertheless cos I need to login.
* After connecting, the front end website would show me as logged in as Wallet 2 **world.btc in URL**, however on the gamma page itself would display me as **world.btc with SP1...ABC**, I cannot see my wallet 1 NFTs, it would just show all NFTs of wallet 2. 
* If I attempt to make actual purchases/transactions, the **pre-confirmation pop-up window would show hello.btc with SP1...ABC** luckily. (which suggests I can only sign tx with the right wallet, which is good. I'd be more worried if I were able to sign wallet 2's tx with wallet 1)
* Due to this glitch, I cannot connect to my wallet 1 hello.btc SP1...ABC on the NFT marketplaces and use it properly. 

Hope above is clear and makes sense? Let me know if you need anything else. 
Anyways, from my understanding of the conversations in various threads, it appears to be just API issue. 
Looking forward to the fixes. 

Thanks team!

**Comment by markmhendrickson** [comment]
I'm closing this out on the wallet side since it appears to be an API issue that's getting resolved.
