### ISSUE TITLE
Reimplement submitted transaction functionality

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2467]
[Multiple](https://discord.com/channels/621759717756370964/745197302255321108/981053123684630578) [users](https://discord.com/channels/621759717756370964/625538774230892545/980500275645259857) on Discord have reported issues with stale _submitted_ transactions. Lots of old transactions that never go away.

These transactions are added when broadcast, and persisted until found in mempool, to offer a predictable experience. Without this state, transactions are broadcast, nothing will show for a few seconds, and then they'll immediately reappear (when the mempool has been refreshed). It's confusing.

In certain cases—be it a wallet bug or transient API issue—transactions are submitted and never make it to the mempool. This results in a "write-only" case. The tx never appears, and is never cleared from the store.

Some suggestions/questions for how we might implement this differently, or more reliably:
- **Not using localStorage**. If we assume these are occasional error cases, and in happy flow we only need this state for several seconds, could we cache in memory? This would mean slow-to-appear-in-mempool txs might disappear on refresh, also not ideal, but maybe better than forever-lasting stale txs that never go stale
- **Human readable keys**. Currently we use `makeLocalDataKey` to create a unique hash/key for each `account, network, version`. If we do continue using localStorage here, I suggest human readable keys. It would make debugging much easier.
- **Adding expiry time**. After a period of an hour or something, I'd have thought we can be pretty sure that a tx isn't ever going to appear. We could add a timer to check existing submitted txs and then clear them if not present.

**Comment by friedger** [comment]
I like the expiry time!

**Comment by fbwoolf** [comment]
Related issue: https://github.com/hirosystems/stacks-wallet-web/issues/2115

**Comment by Hero-Gamer** [comment]
I think "expiry time" is a good step forward! What kind of time frame are you thinking of setting?
(the other two options I don't quite understand how it will feel from end user UX perspective, if I understand better I could give feedback.. sorry a non-techny here..)

In additional to this good step forward ,I do think the bigger goal from UX perspective, that end-user does not even come contact (or need to be shown) with "submitted" state. If possible of course technically. 

My main reasons being: 
- "Submitted" state does not offer single benefit to user (and developer also?) at all, user cannot do anything with it, has zero utility basically (unless I'm missing something). So, what's the point of even having it/them hang your wallet for 24 hours, I'm not quite sure. 
- From all the users I've helped wallet trouble shoot re "Submitted" state, overwhelming majority (95%) of them think they are the same as pending transaction. Just because they see that **orange tx** in their Hiro wallet (they don't read the small print of "submitted" vs "pending" which are different"
- The side effect of end users conflating the two is:
 1) they think they sent the transaction successfully, go about doing their irl business, comes back to Hiro wallet hours later, still see all the tx pending, comes into Discord and ask "why are they still pending?". 
 2) User would keep piling on more submitted transactions sometimes without knowing, because they all look orange in Activity tab, therefore they think they must be being processed right..
- Users could have been doing other much more productive transactions/activities on Stacks during these time wasted waiting and assuming their tx are being processed, thereby increasing productivity per Stacks block.

Look forwards to your thoughts :)

**Comment by 314159265359879** [comment]
In regards to "questioning the submitted state", I think it is possible to leave this in the background and not show users "submitted" transactions... Only show the user the pending transaction as soon as it is in the mempool. But if you do show users perhaps it can be made more distinct from a "pending transaction" 
A. For example give this a red background
![image](https://user-images.githubusercontent.com/33360391/174068793-79394be7-390d-42ad-ae01-25c5e5767e0f.png)
B. and/or Show an icon it is about to be send

If we do insist on showing "submitted" state because it is distinct from "pending" because the first is in your local storage (or mem cache) and the second is in the mempool on the network. Then I would suggest providing the option to:
1. Increase fee
2. Edit nonce

As those are two issues causing "infinitely submitted state" transactions and that way the user can solve it.

**Comment by friedger** [comment]
Submitted is the state before pending and I think it is useful because it gives immediate feedback.

The representation could be better, like a pending tx in a disabled state with an indicator to wait until the pending state has been reached.
After 1 minute a retry button could appear.

**Comment by wickles** [comment]
I run into this pretty often, to the point where I pretty much always have a running list of "submitted" transactions that are long past stale and take some days or weeks to clear out from the mempool. 

If the account nonce successfully surpasses that of a stale submitted transaction then the stale transactions should be discarded from the UI.

**Comment by Hero-Gamer** [comment]
For the record, during today's megapont free mint, when network/API under heavy load/stress, we have seen many many tx stayed in submitted state despite correct nonce in the wallet.

Later on when API became healthier (after an hour or two), I made the same tx again, right nonce, then that tx quickly turned from submitted to pending, whilst the old tx stayed submitted in the wallet.

**Comment by fbwoolf** [comment]
@kyranjamie @markmhx would it make sense here just to add a button in the UI to `Clear Submitted Transactions` with a hover state that explains the transactions were broadcast but not yet picked up by the mempool? I feel like providing the user with some control over this feature might be a good move? It could just be a small button in line with the `Submitted` header, so you only see it if there are submitted transactions in the list? I have mixed feelings about even keeping this feature.

**Comment by aulneau** [comment]
@fbwoolf my understanding of `submitted` state are transactions that have not been broadcast, but the raw TX exists locally in the wallet. My understanding of the issue with long standing `submitted` transactions is that they often have some error in them, or the fetch to post them to the api has failed, hence why they stay in that state

**Comment by aulneau** [comment]
> I have mixed feelings about even keeping this feature.

I think it's in line with the general thinking of other features that this kind of feature would exist. As the original implementor of this feature, my goal for it was to allow for a better failure state when network conditions are less than ideal. The wallet should have an ability to track all transactions that it has signed, and if it fails to broadcast them, it should continually retry without the user having to go to the app that originated the tx request, and do the actions all over again. 

Just my 2 ustx :)

**Comment by fbwoolf** [comment]
Here in the code it looks like the tx is added to the submitted state `after` broadcast? https://github.com/hirosystems/stacks-wallet-web/blob/8c6b67048264c7c13ba3fdb73d118a888d9d6646/src/app/common/hooks/use-submit-stx-transaction.ts#L70

Am I reading that wrong?

**Comment by fbwoolf** [comment]
Also happening here after broadcast...

https://github.com/hirosystems/stacks-wallet-web/blob/8c6b67048264c7c13ba3fdb73d118a888d9d6646/src/app/store/transactions/transaction.hooks.ts#L193

**Comment by aulneau** [comment]
yeah, looking at those it does seem that way, however I'm able to repeatedly force txs to go into the `submitted` state by:
- sign into an app
- create a STX token transfer tx where the recipient is my address
- sign the tx (tx comes from the app)
- the TX never gets broadcast (i'm fairly certain the api errors, but the wallet swallows this error)
- the TX forever stays in the "submitted" state

hence my assumption that many of these "submitted" txs are really because there needs to be better error handling/capture for the broadcasting of txs.

**Comment by fbwoolf** [comment]
> there needs to be better error handling/capture for the broadcasting of txs.
>
Yeah, definitely agree with this. But, in addition, what do you think of the user being able to clear the submitted txs list if they want to or clearing them on a timer as @kyranjamie proposed?

**Comment by aulneau** [comment]
I'd bet the issue is this:

https://github.com/hirosystems/stacks-wallet-web/blob/8c6b67048264c7c13ba3fdb73d118a888d9d6646/src/app/store/transactions/transaction.hooks.ts#L192

in this other example, https://github.com/hirosystems/stacks-wallet-web/blob/8c6b67048264c7c13ba3fdb73d118a888d9d6646/src/app/common/hooks/use-submit-stx-transaction.ts#L63

you're checking for the existence of `.error`, however, when submitting txs from an app, you're only checking for the existence of the txid, which is always present, even with a .error.

**Comment by aulneau** [comment]
> what do you think of the user being able to clear the submitted txs list

yeah i think that's a good idea :)

**Comment by fbwoolf** [comment]
> 
> you're checking for the existence of `.error`, however, when submitting txs from an app, you're only checking for the existence of the txid, which is always present, even with a .error.

Yep, I see that too, thanks for feedback.

**Comment by aulneau** [comment]
@fbwoolf https://github.com/hirosystems/stacks-wallet-web/pull/2575

**Comment by fbwoolf** [comment]
That is funny, was just posting this...

`
Identifying this has significantly helped catch unnecessary submitted transactions. Locally, I am now providing a toast in the tx popup and preventing adding the tx to the submitted state when there is an error. We weren't handling that correctly for tx requests ...so likely was causing the most confusion.
`

Very similar solution, thanks for the help!

**Comment by fbwoolf** [comment]
Thoughts on toasts as feedback in the UI?

![Image](https://user-images.githubusercontent.com/6493321/179639345-c13269bf-4d5d-4daf-ade7-a9514fe78fdc.gif)

EDIT: I want to add handling all the error reasons.

**Comment by aulneau** [comment]
> Thoughts on toasts as feedback in the UI?
> 
> ![Image](https://user-images.githubusercontent.com/6493321/179639345-c13269bf-4d5d-4daf-ade7-a9514fe78fdc.gif) [ ![Image](https://user-images.githubusercontent.com/6493321/179639345-c13269bf-4d5d-4daf-ade7-a9514fe78fdc.gif) ](https://user-images.githubusercontent.com/6493321/179639345-c13269bf-4d5d-4daf-ade7-a9514fe78fdc.gif) [ ](https://user-images.githubusercontent.com/6493321/179639345-c13269bf-4d5d-4daf-ade7-a9514fe78fdc.gif)
> 
> EDIT: I want to add handling all the error reasons.

I think toasts are good, but I'd suggest removing the loading state immediately, and passing the proper message for the error reason. 

Interestingly, `TransferRecipientCannotEqualSender` isn't accounted for in `@stacks/transactions`. I wonder where all the error reasons are in the node, it would be good to cross reference them. @kantai can you link to the error enum in the stacks-blockchain repo that contains `TransferRecipientCannotEqualSender`?

**Comment by aulneau** [comment]
@fbwoolf here are all the errors -> https://github.com/stacks-network/stacks-blockchain/blob/master/src/chainstate/stacks/db/blocks.rs#L259

**Comment by markmhendrickson** [comment]
Great work, you two 💪 Thanks for chipping in @aulneau.
