### ISSUE TITLE
Hiro Web Wallet overides ownerNonce in sponsored TX

### ISSUE THREAD

**Issue by unclemantis** [blockstack/blockstack-app#2512]
```
export async function contractCall() {
    openContractCall({
        network: testnet,
        anchorMode: AnchorMode.Any,
        contractAddress: contract_address,
        contractName: contract_name,
        functionName: function_name,
        functionArgs: [],
        postConditionMode: PostConditionMode.Deny,
        postConditions: [],
        sponsored: true,
        ownerNonce: owner_nonce,
        appDetails: {
            name: "My App",
            icon: window.location.origin + "/my-app-logo.svg",
        },
        onFinish: async (data) => {
            const sponsoredTx = await sponsorTransaction({
              transaction: deserializeTransaction(data.txRaw),
              fee: sponsor_fee,
              sponsorPrivateKey: private_key,
            });
            
            broadcastTransaction(sponsoredTx, testnet);
        },
    });
}
```

```
owner_nonce = new BN(35)
```

When I confirm in the wallet popup I get this in return after `broadcastTransaction(sponsoredTx, testnet)`

```
{
  "actual": 34,
  "expected": 35,
  "is_origin": true,
  "principal": "ST17EV8YSY8MJ9...Q2KKJQ305S1"
}
```

Why is this? Why is the wallet overriding the nonce that i set in the TX? Yes I am doing this on purpose. I have a reason.

**Comment by unclemantis** [comment]
This is also true for `nonce: owner_nonce,`

Please look at these two references containing `nonce: Number(values.nonce) || options.nonce`

[useSoftwareWalletTransactionBroadcast](https://github.com/hirosystems/stacks-wallet-web/blob/92e1047240326d4582f49e99f68426f5fac3aa38/src/app/store/transactions/transaction.hooks.ts#L123-L127)

and

[useGenerateUnsignedStacksTransaction](https://github.com/hirosystems/stacks-wallet-web/blob/92e1047240326d4582f49e99f68426f5fac3aa38/src/app/store/transactions/transaction.hooks.ts#L192-L196)

In my opinion the line should be

`nonce: options.nonce || Number(values.nonce)`

**Comment by fbwoolf** [comment]
This is not a bug in the wallet. The code you are referencing are local options in the wallet code. I believe I linked you to the `sponsorTransaction` function in stacks.js that shows this is expected behavior. Calling that function is not handled by the wallet.

https://github.com/hirosystems/stacks.js/blob/ee8eb8c138f91ac3264a75a4e05a27721f749153/packages/transactions/src/builders.ts#L1364

We just return the rawTx here but don't broadcast it:
https://github.com/hirosystems/stacks-wallet-web/blob/603a1423d34281a5d4b8059d2efcd4720b5481d3/src/app/common/transactions/broadcast-transaction.ts#L21

In your example code, you need to add the `sponsorNonce` into the options in `sponsorTransaction`. If it is undefined it will be replaced with the sender nonce.

https://github.com/hirosystems/stacks.js/blob/ee8eb8c138f91ac3264a75a4e05a27721f749153/packages/transactions/src/builders.ts#L1348
