### ISSUE TITLE
Add option to easily transfer STX to another account in same wallet

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2699]
Add option to select one of wallet's other accounts (e.g. from dropdown) for easier asset management between accounts

<img width="393" alt="Screen Shot 2022-10-04 at 13 08 03" src="https://user-images.githubusercontent.com/28991/193807373-a6ee0d06-d2cd-46d6-ba03-a39cd589d9ed.png">

**Comment by kyranjamie** [comment]
This is quite a straight forward feature to implement. We have a dropdown library in place already, and can reuse components from elsewhere to style the accounts that appear on focus.

**Comment by Hero-Gamer** [comment]
I like this idea

**Comment by Hero-Gamer** [comment]
If users can mark their "favorites" from the library might be very handy

**Comment by tuanphungcz** [comment]
yeah, this could be a nice feature to avoid switching accounts just to copy-paste the wallet address 😄

so I made a quick prototype for this feature as in the video below

As a user, I can click on "Transfer between my accounts" (inspired by Metamask 😄). The Drawer pops up and the user can select one of his accounts.

@markmhx I wasn't sure if this issue is not taken by anyone, so I didn't do the PR, but let me know what you think.

https://user-images.githubusercontent.com/16448321/201970131-916089e7-7155-4ec0-ab89-900a007d469b.mp4

**Comment by markmhendrickson** [comment]
@tuanphungcz this is fantastic 👏 

Please do submit a PR and we'll review. I expect we'll want to finesse how the "Transfer between my account" option is displayed, but otherwise this UX looks on point to me.

**Comment by tuanphungcz** [comment]
Ok, I got it 👍 Here is the PR https://github.com/hirosystems/stacks-wallet-web/pull/2865
