### ISSUE TITLE
Nonce computation issue

### ISSUE THREAD

**Issue by 0xFrancisc** [blockstack/blockstack-app#2773]
There's a nonce computation bug in the web wallet.

When there is a pending TX that will never get confirmed because another with the same nonce was already mined, Hiro will read that TX's nonce as being the one to anchor the next nonce on.

Given such TXs stay in pending state until aborted for over 48 hours, nonce computation is broken during that period.

**Comment by markmhendrickson** [comment]
Is this the sort of scenario you've encountered?

1. User has previously transacted successfully with nonces 0-5
2. User broadcasts new transaction with nonce 4 that will never confirm because of conflict with confirmed transaction
3. While that transaction is still pending, user goes to broadcast another transaction and is erroneously recommended nonce 5 by the wallet,  *apparently because the transaction in step 2 is using nonce 4 (and 5 == 4 + 1)*

**Comment by 0xFrancisc** [comment]
Thanks, Mark.
That's exactly it.

**Comment by fbwoolf** [comment]
@0xFrancisc I can't seem to reproduce using these steps. Every time I get the `Incorrect nonce` toast and I can't broadcast a tx with a nonce that has already been confirmed?

![Screen Shot 2022-11-03 at 4 00 39 PM](https://user-images.githubusercontent.com/6493321/199833462-ab51b983-23bf-46c4-b581-492e7f657849.png)

I have a possible fix PR I'll put up but I can't test it.

**Comment by 0xFrancisc** [comment]
I think that's reproducing it.
You get the incorrect nonce because the next after pending is already mined.

**Comment by 0xFrancisc** [comment]
To be clear, the issue is incorrect selection of the nonce leading to the "unable to broadcast transaction" error.

**Comment by 0xFrancisc** [comment]
This is happening again...

**Comment by markmhendrickson** [comment]
@0xFrancisc mind confirming the version of your wallet in which this is happening again?
