### ISSUE TITLE
Display certain punycode conversions properly in account labels

### ISSUE THREAD

**Issue by jeky138** [blockstack/blockstack-app#2783]
![image](https://user-images.githubusercontent.com/79683717/199192260-93450c8f-a165-4e6e-9142-2fafb2af6286.png)
1️⃣1️⃣1️⃣.btc  This is the correct display

**Comment by markmhendrickson** [comment]
_From @edu-stx:_

I've done a little more digging into this. I suspect that at the heart of this issue is that different tools may work in slightly different ways. For example, punycoder.com may not work exactly the same as the lib we're using in the wallet. On top of that, there's user error or browser/OS specific features that may alter a string as it is being copy/pasted. If the entire process of going from unicode to punycode, to unicode again on the wallet isn't perfectly aligned, users can end up seeing unicode interpretationsn of their punycode that they did not expect. 

For example, take the table in the screenshot. Had the user registered a different punycode, xn--123-uc1abb94470bcac.btc they would see the results they were expecting. However, this punycode is treated as invalid by punycoder.com.

I've quickly put together a tool to help us help users should they have issues. This tool uses the lib that both the Wallet and gamma use, so at least we'll be aligned,
* code + app preview: https://stackblitz.com/edit/react-ts-j9rjzg?file=App.tsx
* app only: https://react-ts-j9rjzg.stackblitz.io/

**Comment by markmhendrickson** [comment]
@jeky138 mind providing several punycode values that render incorrectly for you here to help with diagnostics and resolution?

**Comment by markmhendrickson** [comment]
I'm finding that the value shown in the screenshot above (`xn--111-uc1abb.btc`) renders with a combination of "1 + square" instead of 1️⃣ emojis in all three of these converter tools:

https://adraffy.github.io/punycode.js/test/demo.html#u=1%E2%83%A31%E2%83%A31%E2%83%A3.btc

<img width="979" alt="image" src="https://user-images.githubusercontent.com/28991/199922673-d542bebd-4c0a-45e4-879c-65e57e5d926a.png">

https://www.punycoder.com/

<img width="646" alt="image" src="https://user-images.githubusercontent.com/28991/199922765-c6e5aad8-f374-4356-bb25-0e643a3c3f81.png">

https://react-ts-j9rjzg.stackblitz.io/

<img width="844" alt="image" src="https://user-images.githubusercontent.com/28991/199922789-7b60e443-867d-467a-ad60-8fe9aee5fbb6.png">

**Comment by edu-stx** [comment]
@jeky138 the punycode `xn--111-uc1abb94470bcac` should appear in the wallet as what you're expecting.

When in doubt, you can use the tool over at https://react-ts-j9rjzg.stackblitz.io/ to see how different punycodes will render in the wallet.
