### ISSUE TITLE
Account name is off center in popup header

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#2794]
If I remove this prop it aligns, but I'm not sure what else this will impact? @edu-stx 

![Screen Shot 2022-11-03 at 2 52 14 PM](https://user-images.githubusercontent.com/6493321/199820896-a0dbd7a2-f084-4b16-b18a-362487cd52ef.png)

**Comment by edu-stx** [comment]
It will cut off emojis and other tall non-Latin characters in the account label.

**Comment by markmhendrickson** [comment]
I wonder if there's a way to allow taller characters to overflow upwards while keeping the account label, address and balance on the same vertical alignment?

**Comment by edu-stx** [comment]
Surely can be done. @fbwoolf do you want to take this on or should I?

**Comment by kyranjamie** [comment]
Underlying problem here is the capsize issue https://github.com/hirosystems/stacks-wallet-web/issues/2344

It adds _both_ a `::before` & `::after` element. The alignment issue is fixed when the `::after` is removed as well, but here only the before is removed.

I reckon we should spend some time removing this library, otherwise we'll have an endless game of cat-and-mouse fixing alignment issues, without ever address the root cause. I think this'd be beneficial, even if in the short term, some alignment issues are introduced.

**Comment by markmhendrickson** [comment]
Is this unblocked for execution now that #2808 is merged?

**Comment by kyranjamie** [comment]
We should remove the `removeBeforePesudoElement` code now that capsize is removed.

**Comment by markmhendrickson** [comment]
@edu-stx want to take this one?

**Comment by edu-stx** [comment]
Opened #2833 to remove the capsize work-around.
