### ISSUE TITLE
Show locked/stacked Stacks balances

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2835]
The UI only shows available balance, and not what is stacked.

**Comment by markmhendrickson** [comment]
Is this the case only for Ledger-connected accounts or even software ones?

**Comment by kyranjamie** [comment]
I suppose this is not specific to Ledger. (Just happened to discover using my stacking Ledger).

**Comment by markmhendrickson** [comment]
Cool, makes sense 👍

**Comment by mica000** [comment]
This design proposal includes changes the web wallet that aims to not only show the locked/stacked stacks balance but also increase the visibility of the Stacking feature.

Goal 1: Bridge the existing gap that exists on the web wallet;
Goal 2: Increase feature visibility;
Goal 3: Increase amount of Stacking users;



https://user-images.githubusercontent.com/119523541/211592391-3f7b1c48-b4a1-4888-a84b-0f326a3e8b36.mov

[Prototype
](https://www.figma.com/proto/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?page-id=6818%3A40809&node-id=7146%3A132680&viewport=-1203%2C1742%2C0.21&scaling=min-zoom&starting-point-node-id=7146%3A132680&show-proto-sidebar=1)

[Figma](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=7146%3A132680&t=dCQHhB26J0zv7W9C-4)

**Comment by markmhendrickson** [comment]
Looking good! A few notes:

- If the user has only partially locked their balance, do we want to show both "locked" and "unlocked" sub-balances? Or just "locked" and the user has to deduce the remaining unlocked amount? I believe in the desktop wallet we show both, with the unlocked labeled "10 STX _available_"
- We can create a new tab for Stacking in the wallet here (and I like the idea!), though I'm not sure we can embed the Stacking app / UX entirely there since it'll live in a separate code base for the hosted site. Perhaps we can start with a simple prompt to "get started with Stacking" that would take the user to the separate app, then enhance from there inside the wallet itself?
- Should we perhaps show the top-level balance on the home screen in USD with the STX shown further below? We should perhaps consider that approach, placing the locked/unlocked UI under "Balances" in the STX row itself so it's specific to that asset and not others.
- I might recommend a different icon for the Stacking tab, something that connotes earning / yield? The current graph-like icon could connote "visualize your assets over time" as easily.

Note as well that we could leverage the addition of token-specific screens for displaying detailed info about STX (and other tokens) such as locked/unlocked status. The user could click on a token listing under "Balances" and get taken to another full-view screen that's specific to the token, with various details about it for the user (and even view its specific activity history, without other token activity shown).

**Comment by markmhendrickson** [comment]
@mica000 I'm thinking that short-term until we add the new token-specific screens, we should just push a hotfix for locked vs. unlocked (because right now we show just the unlocked amount so it appears as though you've lost all the locked STX 😱)

wdyt of this simple parenthesis?



![Image](https://user-images.githubusercontent.com/28991/229536341-09b51761-a6da-4066-9fb6-81d4a1891faa.png)

**Comment by mica000** [comment]
@markmhx Seems like a good idea. Let's give it a try!

**Comment by mica000** [comment]
This is related to https://github.com/hirosystems/wallet/issues/3569

Figma in progress: https://www.figma.com/file/aIhESuca3xWkJ7efpaivbV/Balances?node-id=0%3A1&t=uNgCPD24CgnpFIrM-1
