### ISSUE TITLE
Support newly created tokens on the wallet

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2839]
I have gotten two reports from users who used the launchpad on stackswap.org asking for support for their token. 

**Token 1: Beecoin (BCON)**

It looks like there are three coins with the same name on the launchpad so I will ask the user which one they will be using for their project. 
![image](https://user-images.githubusercontent.com/33360391/201313218-1ec23691-3d59-4a37-b70c-8fce34305a94.png)

Additionally they would like to see details for the derived token (I believe it is the related LP token): STSW-BCON

**Token 2: parkplanb (PPB)** 
Token contract: SP1Z92MPDQEWZXW36VX71Q25HKF5K2EPCJ304F275.tokensoft-token-v4ked04n8a2
`get-token-uri` response: `(ok (some u"https://stackswap-launchpad.s3.amazonaws.com/36fd46f4-5b9b-4403-af43-3425e99b5d16.json"))`

'get-symbol' response: PPB

Contents of .json
`{"title":"Asset Metadata","type":"object","properties":{"name":{"type":"string","description":"parkplanb"},"description":{"type":"string","description":"Great New Token"},"image":{"type":"string","description":"http://s3-us-east-2.amazonaws.com/stackswap-launchpad/8eb7158c-c0e5-47bf-8884-9a3e8cb07928.png"},"homepage":{"type":"string","description":"https://your.homepage.com"}}}`

provided logo image: 
![image](https://user-images.githubusercontent.com/33360391/201314061-e9df8d08-b5b5-4003-b37f-85d2eda18a4c.png)

Are these responses as expected or in accordance with the standards we expect them to be in?
What would be needed to get the logo's and token tickers in the wallet?

Do we want something like, adding new tokens, to be automated or otherwise have a process to get details for new tokens added to the Hiro wallet?

**Comment by markmhendrickson** [comment]
My understanding that tokens should show up in the wallet automatically if they conform completely to the SIP-010 standard. There's no separate process for adding new tokens to the wallet if the user holds them with their address on chain.

It would require inspecting the token's contract to determine just where it might not conform to that SIP.

Also, as far as multiple tokens potentially showing up as the same in the wallet (e.g. BCON here), we ought to display their particular registration details so the user at least has a way of distinguishing them based on how they've been deployed on chain: https://github.com/hirosystems/stacks-wallet-web/issues/2841

**Comment by 314159265359879** [comment]
Thanks for the input Mark, perhaps there is some deviation from SIP010 in that case. The JSON looks different to me, and I do not see the token symbol in there. There may also be something about how these contracts are created. They are generated by the protocol. Lets ask some input from the Stackswap team. @kjchiang3 would you mind having a look here?

The details for BeeCoin1111:
associated contract is: SP1Z92MPDQEWZXW36VX71Q25HKF5K2EPCJ304F275.tokensoft-token-v4k4xpeivzv

the api call 'get-symbol' results in BeBe
and get-token-uri gives me: 
(ok (some u"https://stackswap-launchpad.s3.amazonaws.com/4ebebc67-6344-41f2-a142-71c958998d23.json"))

JSON content:
`{"title":"Asset Metadata","type":"object","properties":{"name":{"type":"string","description":"Beecoin1111"},"description":{"type":"string","description":"Sweet New Token"},"image":{"type":"string","description":"http://s3-us-east-2.amazonaws.com/stackswap-launchpad/49e1ec93-6c09-47c5-b3ce-8f20944fa238.jpg"},"homepage":{"type":"string","description":"https://beecoin1111.modoo.at"}}}`

Token logo from the JSON:
![image](https://user-images.githubusercontent.com/33360391/201425747-a0c7907f-5ece-4956-8ff1-8df29830ce8e.png)

Here is a token contract that does display as expected in the wallet/explorer
![image](https://user-images.githubusercontent.com/33360391/201431236-2dfcfc45-09a4-4268-b19f-5de9d80f229e.png)

Token contract for Wrapped BTC (xBTC): SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin
token uri:
(ok (some u"https://wrapped.com/xbtc.json"))

json content
`{
  "name": "Wrapped Bitcoin",
  "symbol": "xBTC",
  "description": "Wrapped Bitcoin on Stacks (xBTC) is a 1:1 equivalent of Bitcoin (BTC) on the Stacks network. xBTC combines the security of Bitcoin with general purpose smart contracts of Stacks, making DeFi applications for the Bitcoin ecosystem possible.",
  "image": "https://wrapped.com/images/xbtc.png"
}`

**Comment by kjchiang3** [comment]
Hey there, James from Stackswap here.

I believe the issue to be this:

As the mechanism for the Stackswap Token Launchpad is to pre-deploy these contracts before changing the metadata for the launched tokens, the only issue is to update the list from which Hiro pulls token data from. This wasn't an issue before the big update from sometime this past summer.

I believe there are 2 solutions:

1. update the token metadata manually whenever a new token is launched from the Launchpad by keeping a separate list which Hiro can pull from
2. refresh the token metadata source periodically so that the list can be accurately reflected at least by the end of the day/ few days/ week, whatever the time period is determined to be.

**Comment by markmhendrickson** [comment]
Thanks @kjchiang3 for chiming in here with context

cc @zone117x since I believe he can provide the best current and historical context on how the API does or doesn't refresh metadata for previously deployed token contracts

**Comment by zone117x** [comment]
> As the mechanism for the Stackswap Token Launchpad is to pre-deploy these contracts before changing the metadata for the launched tokens

This is not a supported workflow for the API's token metadata indexing. Right now, the metadata is fetched as soon as the API detects a new SIP-010 contract deployment. The historical context relates to SIP-010 lacking any kind of metadata update notification mechanism. 

A new SIP tackling this issue is activation-in-progress: https://github.com/stacksgov/sips/pull/72, and a new indexing service is implemented on top of this standard: https://github.com/hirosystems/token-metadata-service. It's not yet deployed, but it's targeted for deployment this quarter. 

cc @rafaelcr who's been leading this project.

**Comment by markmhendrickson** [comment]
Thanks @zone117x. I'm closing this issue on the wallet side since it does appear to be a question of server-side functionality.
