### ISSUE TITLE
[Bitcoin] return BTC address on auth

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#2909]
As requested by Friedger for catamaranswaps.

**Comment by 314159265359879** [comment]
friedger.btc — Today at 10:58 AM
A relevant issue here: https://github.com/bitcoin-nfts/bitcoin-colors/issues/26

The requirement is "wallet should provide the BTC address of the logged in user". 

Sharing the btc address without user's consent might be a privacy issue if the user selects only the stx address for sharing/auth.

**Comment by whoabuddy** [comment]
There's also a challenge of *which BTC address* to return:

- the converted Stacks address, which produces a legacy 1 address at the Stacks derivation path (used with Catamaran Swaps iirc?)
- the wrapped Segwit address, generated from the same key but down the default derivation path (this is what Xverse uses)
- other options/combinations of the above

We're interested in the second one for the linked issue. If this were positioned as the "wallet" sharing "known addresses" on login, do you think that'd still be an issue? Could the privacy challenge be solved by clear communication?

**Comment by 314159265359879** [comment]
Mark mentioned we'll be going with Native SegWit initially in the discussion here: https://github.com/hirosystems/stacks-wallet-web/issues/2845

Will that work for your purpose too @whoabuddy?

**Comment by whoabuddy** [comment]
Not in the current form of the design. Since both legacy and wrapped segwit addresses (or basically, anything Base58Check encoded) can be converted into a Stacks address, we're using that as a way to associate an NFT with a Bitcoin address, as well as allow that Bitcoin address to claim the NFT later.

The plan is to store the Bitcoin address in the contract using the same definition as PoX, which while it's being upgraded to support segwit/taproot, the libraries and primitives we are working with are still based on those legacy addresses.

Our hope was that both Hiro and Xverse could align on using the wrapped segwit address so the experience of loading the seed phrase into either wallet is the same. It'd be a shame if that didn't work out as I think it'd cause more confusion.

Is it overly complex to have both? I know the Mycellium wallet does this, allowing you to switch between legacy, wrapped segwit, and native segwit addresses based on the same seed phrase.

**Comment by markmhendrickson** [comment]
We're looking to support just Native SegWit with our initial Bitcoin implementation to keep things simple. However, I've filed an issue here for capturing the future support of other address types: https://github.com/hirosystems/stacks-wallet-web/issues/2923
