### ISSUE TITLE
Show microblocks as a state of pending rather than confirmed

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3111]
https://github.com/hirosystems/stacks-wallet-web/issues/2944#issuecomment-1411816492 a quick fix to resolve confusion about microblock confirmations would be to display them as an advanced stage of pending rather then confirmation. 

Something like this in the activities tab:
![image](https://user-images.githubusercontent.com/33360391/218559188-2678800a-a99d-453d-8b39-5d7d0e947ae5.png)

See also: https://github.com/hirosystems/stacks-wallet-web/issues/3110

Should be revisited after with nakamoto-release.

**Comment by Hero-Gamer** [comment]
why do you even need to tell people it's in microblock. It's either "Confirmed" or "pending" no? from the wallet perspective. Maybe in explore have more details re microblock? idk just thinking out aloud

**Comment by Hero-Gamer** [comment]
hypothetically speaking if there were 3 stages of tx (microblock, middle block, anchor block), we don't need to tell everybody everything technically correct to a user. Do we?
It's either confirmed, or not confirmed (pending).

**Comment by markmhendrickson** [comment]
Let's tackle this on https://github.com/hirosystems/stacks-wallet-web/issues/3110 by clarifying what microblocks means as a state for users. Longer term this year with Nakamoto, they should become much more effective so I'd rather not take them out for now (since we may then have to put them back in)

**Comment by Hero-Gamer** [comment]
It's either "confirmed", or "pending". 
- Imo users do not need to understand (at the current blockchain state where microblock doesn't really mean anything to users) anything in between. What state tx is in "pending", mircro-blocks or whatever else flavors, users do not really need to know.
- Users only need to know if fund is deducted, or not. A user CAN use his post-deducted fund, OR NOT.
- Yes longer term if new upgrade comes that actually deducts user's balance and allows users to USE his balance after a micro-block tx succeeds, sure. However 1. we don't know how many months out that will be, 2. when that month comes we can prepare for that launch, there is no need to not keep displaying ambiguous state right now just because Nakamoto release might come.  
Just my 2 Sats.

**Comment by markmhendrickson** [comment]
Transactions in microblocks as they're currently implemented _do_ have a stronger probability of inclusion in the next anchor block vs. transactions that are simply pending. So I'm thinking our clarification for the current implementation could be something along the lines of explaining this e.g. in a tooltip ("This transaction has been included in a microblock, which means it hasn't confirmed yet but has a higher likelihood of confirming in the next anchor block.").
