### ISSUE TITLE
[Bitcoin] Remove Stacks specific copy when bitcoin transaction is pending

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3129]
The pending tooltip label displays copy that relates to Stacks network congestion, and should be removed/adjusted in the case of bitcoin pending txs

**Comment by markmhendrickson** [comment]
This appears resolved



![Image](https://user-images.githubusercontent.com/28991/219871670-41d00a7a-ad73-427e-a1dc-0a669972918d.png)

**Comment by kyranjamie** [comment]
Afaik, this is the same copy as before that Tycho described as being stacks specific

**Comment by markmhendrickson** [comment]
Hmm yea, I can't recall what seemed wrong about it. I'll ask him to provide more guidance here. cc @tycho1212

**Comment by tycho1212** [comment]
This copy appears to be Stacks specific since it references 1) network congestion and 2) that txs could take 'a couple of hours'.

1) Network congestion on the Bitcoin blockchain is extremely rare, much rarer than on the Stacks chain. I would suggest removing references to network congestion

2) Bitcoin blocks are produced very reliably every 10-20 minutes (I don't think it's happened in recent history that there was no block for 'a couple of hours'). I would remove reference to 'a couple of hours'

**Comment by markmhendrickson** [comment]
How about for BTC transactions: `This transaction is waiting to be confirmed. The average (median) confirmation time on Bitcoin is 5-10 minutes`

Per https://www.blockchain.com/explorer/charts/median-confirmation-time
