### ISSUE TITLE
[Bitcoin] Fix kill switch with dev builds

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#3130]
Wallet config to disable bitcoin was removed bc it wasn't working with dev builds to test.

**Comment by markmhendrickson** [comment]
@fbwoolf have you gotten this ironed out?

**Comment by fbwoolf** [comment]
@kyranjamie I never understood what you felt I did wrong with my implementation beyond the wallet.config changes not being recognized properly by dev builds bc it wasn't on main, can I just redo my implementation but directly off main but set it to `false` for now?

**Comment by kyranjamie** [comment]
All I changed from previously was not using the kill switch in the feature flag (because the branch detection didn't work and we needed to test test builds). 

It's not that anything in your implementation was wrong, more that I don't think we're on the same page as to what the kill switch should do. I wrote on [discord](https://discord.com/channels/915096489422893067/991327998345228391/1074998995908313090) why I think we should consider a kill switch separate from a feature flag. But maybe we should consider what our exact needs for this are.

Here's how I see the two features. There are similarities, but I think it's a mistake to consider and implement them the same. Though, feel free to call me out if you think this is being pedantic. 

**Feature flag**
For Bitcoin, we're using this as a way to continue development outside of bitcoin, without having one big feature branch. We're using it to stage a launch from testnet to mainnet. Post-launch, I imagine we'll remove this feature flag from the codebase entirely.

The feature you added Fara is basically a remotely toggle-able feature flag. Maybe that has its own uses, but not what I had in mind.

**Kill switch**
A remote mechanism to prevent certain actions, only to be used in the most severe of cases. That's not necessarily disabling a feature entirely. It could be throwing an error, navigating to an explanatory page, or disabling one part of a feature e.g. sending a currency, but not hiding its balances, as would be the case with a feature flag. A heavy handed kill switch could literally break the wallet for all users. God forbid, but in some scenarios that could be a useful tool to have.

**Comment by fbwoolf** [comment]
I think what you describe requires thought thru a design phase. Where is this triggered and what does it trigger in the UI. When I did a Google search to understand a `kill switch` most references called it a `feature flag`, so I'm not sure there is much difference once the feature is live and we don't need the `feature flag` for development purposes anymore? Wouldn't that, essentially, be replaced by this? Why would we at that point need to check if bitcoin is enabled for the reasons we are doing now?

**Comment by fbwoolf** [comment]
@markmhx what is your thought here, are there UI changes to add for a `kill switch`. I just thought it would shutdown bitcoin completely ...maybe the best move here is for me to branch off main and implement the new wallet config prop as a chore commit so it doesn't trigger a release, then we can decide how to use it on dev?

**Comment by markmhendrickson** [comment]
It seems the ambiguity here is whether we want to turn off Bitcoin functionality entirely in this scenario (restoring the wallet to its current Stacks-only UX) or whether we want to turn off just one or more parts of it that we think might be particularly dangerous (e.g. sending BTC but otherwise showing Bitcoin throughout the wallet e.g. balances, activity, receive addresses).

IIRC our main concern has been about possible missends of BTC, so I'd suggest that the kill switch (or feature flag, whatever we want to call it) is used simply to disable **just the ability to send BTC** if used.

And design wise, since this is meant to be a switch of last resort, we can simply trigger an alert (old school like `alert('Sending BTC is temporarily disabled. Learn more on Twitter at @hirowallet'`). There's no need to get fancier with the UI since it really is a last resort sort of thing.

Does that help?

**Comment by fbwoolf** [comment]
Sounds good, I will implement it this way branched off dev.

**Comment by fbwoolf** [comment]
I going to show our generic error page not just an alert here.
