### ISSUE TITLE
Improve display of balances in balances and account selection view

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3132]
![image](https://user-images.githubusercontent.com/33360391/218865912-ac29afae-ffb9-4b95-ad52-62461b1a633e.png)

Can we revert this change? Showing dollar value here (alone) makes no sense, first of all this is the STX wallet, We want to see the STX balance ;-). And the dollar value doesn't take into account all assets. So the value is usually off. 

I think this was done to save space, make it look cleaner, save space by leaving the dollar value out instead? 
Users need the STX amount because it helps them keep track of specific accounts (when they do not have BNS names). dollar value varies so is not helpful in this regard.

For reference the old view (prior to wallet version 3.34.0).
![image](https://user-images.githubusercontent.com/33360391/218866190-80fc5522-8c0a-4b3c-866a-275529b9905d.png)

**Comment by markmhendrickson** [comment]
Assigning @mica000 so she can take a fresh look at our approach here not that we're dealing with BTC and STX. The idea indeed was to simplify this space with just the dollar value across both balance types, though I agree we could probably do better here by not removing so much data re: the specific balances.

**Comment by 314159265359879** [comment]
A recent request from a user was to showing the dollar equivalent value in the balances tab. I guess this would require having endpoints to check the dollar value of such tokens and show no dollar value if it is unknown:

![image](https://user-images.githubusercontent.com/33360391/218974303-81862157-7d73-4a84-aad5-1170b39f981c.png)

**Comment by mica000** [comment]
@314159265359879 @markmhx What are your thoughts on this solution?
![Image](https://user-images.githubusercontent.com/119523541/219375039-18e105fa-7766-44ba-9283-fb5dcf1a3892.png)


I would suggest we show the total balance in dollars on the main header, as a space for your "total portifolio", since we also have BTC, at least for now. 

Later, the header needs a design update. Currently, the account name takes too much space and not all users have .btc name, leaving the header to be used by a generic name for account 1, 2, 3... But to tackle this we need to define what are the main actions the user want to do and to see on the home screen. We can discuss this soon.

For the balance, Indeed we can show the dollar under each account balance.

Design: https://www.figma.com/file/ooIjZrRmCDeMj1q6pcOEnR/Extension-wallet?node-id=20%3A3579&t=mNCA8d3nFk2OfrAM-4


Prototype: https://www.figma.com/proto/ooIjZrRmCDeMj1q6pcOEnR/Extension-wallet?node-id=42%3A4336&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=42%3A4336

**Comment by markmhendrickson** [comment]
Works for me! Presumably we'd still show the raw BNS value with a copy button in the header if available? Want to include a version for that as well?

Also, how does this approach map to how we display balances under "Choose account"?

**Comment by alter-eggo** [comment]
@mica000 @markmhx is this ready for development?

**Comment by markmhendrickson** [comment]
Yep for the home screen changes, though the account selection ones will require some more design guidance. They can be tackled separately though 🙏

**Comment by alter-eggo** [comment]
@kyranjamie could you help here please? how it is better to count total user balance here?
