### ISSUE TITLE
Add fees screen for BTC and inscription send flows

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3141]

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1110%3A54471&t=Shl5eSB4xRFAbQkH-4

<img width="1103" alt="Screenshot 2023-02-16 at 14 07 55" src="https://user-images.githubusercontent.com/119523541/219373338-e40bc0fe-eda3-43bd-b5df-e64e2e2abf1a.png">

**Comment by markmhendrickson** [comment]
LGTM! I do wonder if we need the blue button at the bottom, in that we could simply transition to the next screen upon selection of one of the 3 options?

**Comment by markmhendrickson** [comment]
LGTM! I do wonder if we need the blue button at the bottom, in that we could simply transition to the next screen upon selection of one of the 3 options?

**Comment by mica000** [comment]
@markmhx Good point! I think I left it from the old design because in that case, the selection would interfere with the total amount but since its removed, we could remove the CTA to make the flow faster
<img width="1233" alt="Screenshot 2023-02-16 at 15 08 06" src="https://user-images.githubusercontent.com/119523541/219387110-40b53d08-1a37-4602-8835-8be1c193c700.png">
