### ISSUE TITLE
Add Ordinal address option to "receive" asset screen and or change copy

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3229]
I noticed a user sending their ordinal here:
![image](https://user-images.githubusercontent.com/33360391/220205320-d4b7bbb0-a527-4560-8f24-67f448b7dd1e.png)

We may want to edit the copy here: "Share your account's unique address to receive any token or collectable"
To make it clear that this bitcoin address it not to be used for Ordinals

Could we possibly add a line for an Ordinal address?
![image](https://user-images.githubusercontent.com/33360391/220204681-d2fd12bd-f7a6-493c-bba7-75f6c419fe1c.png)

Show the warning before copy here too?

**Comment by kyranjamie** [comment]
Agree on changing descriptive text, but adding copy address button here is dangerous (for the opposite reason). We separated it on purpose, to make absolutely sure that users don't accidentally send BTC to a taproot address, because then it'll be stuck.

Afaik, you can't send ordinals to a native segwit address? Most software should warn you, I'd hope?

<details>
<summary>Maybe there's another way we can educate, without adding the ability to copy from here? Inline instructions would be safer</summary>

Anything that doesn't allow user to copy address

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1618764/220293935-2defe21c-8013-4545-bca2-1a533cb402b9.png">

</details>

**Comment by 314159265359879** [comment]
I understand that reasoning. You want to make absolutely sure that if you show an address for ordinals here it isn't confused with a bitcoin address for BTC. My mockup may not do the best job but I intended the logo look like an ordinals logo. We do not even call it "bitcoin address" rather Ordinal inscription address ;-)

The inscription dapp should def do a check for a correct address. I know Gamma.io does such a check and it will error if you try to use a non-taproot address. 

This place (Receive) in the wallet though does seem to be the expected place to get an ordinals address. Pointing to the correct place here as Mark suggested could be a helpful option too:
![image](https://user-images.githubusercontent.com/33360391/220326135-420043b9-7ab2-422a-bd35-03dd14fb67bb.png)

**Comment by mica000** [comment]
It's understandable. I think we messed up the information architecture by separating in 2 flows. The Send, Receive and Buy are placed as actions at the top of the app, giving the impression you would be able to Send, Receive and Buy anything in the wallet while it's not true with the current implementation. 

I will work on a quick fix for now but the biggest need actually is to fix the architecture. I already have some ideas for improvements. Will prototype and we can discuss it.

**Comment by mica000** [comment]
https://user-images.githubusercontent.com/119523541/220437040-816651d4-3a83-49de-ac38-1f6dfa33ffe3.mov

**Comment by badonyx** [comment]
For me the "Collectibles" section is below a very very long list of FT and NFT, so this very much needs to change for UX alone.

**Comment by mica000** [comment]
@0xbabo thanks for sharing! Could you provide a screenshot?

**Comment by markmhendrickson** [comment]
@0xbabo This will be resolved very soon with https://github.com/hirosystems/stacks-wallet-web/issues/3200

**Comment by markmhendrickson** [comment]
@mica000 design improvements here for receipt look great!

Just wondering if we can make this part a little more streamlined, maybe onto just two lines? So it doesn't take up so much space

![Screenshot 2023-02-21 at 14 28 49](https://user-images.githubusercontent.com/28991/220473277-20db582c-9fe0-44e6-b704-8a46aa0c654f.png)

**Comment by markmhendrickson** [comment]
And note we'll need the Ordinal logo here as well 

![image](https://user-images.githubusercontent.com/28991/220473406-1bc04b50-9a22-4b4a-bb3f-604dc95f760b.png)

**Comment by mica000** [comment]
Good catch @markmhx! Here are the proposed design updates.
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=259%3A44770&t=0II1C0rmGSuggeJo-4

Svg:

![Token](https://user-images.githubusercontent.com/119523541/220696865-cfbfc2e3-3203-42fd-8dc0-ac60f89e8064.svg)


![Receive full tab 2](https://user-images.githubusercontent.com/119523541/220606369-26d2c3e1-e5dd-4d8a-85dd-649277e22725.png)
![Receive full tab 3](https://user-images.githubusercontent.com/119523541/220606437-161db3c0-baa8-429f-b286-16379adc2bc4.png)
![Receive full tab 4](https://user-images.githubusercontent.com/119523541/220606508-68c73708-db6e-41eb-9379-4913c268df7a.png)

-----------

![Receive modal 7](https://user-images.githubusercontent.com/119523541/220606565-3f44c21e-4eda-4a50-ba77-bb843c544bc8.png)
![Receive modal 9](https://user-images.githubusercontent.com/119523541/220606632-0aa9f2e8-dcce-419a-9d87-801ebc686aa0.png)
![Receive modal 13](https://user-images.githubusercontent.com/119523541/220606716-aa16df9a-541e-484b-b242-7e26ed0370b3.png)

**Comment by mica000** [comment]
Outlining that in order to avoid the situation described by @kyranjamie we also need to remove the ability to copy BTC addresses throughout the wallet. 

This is a safety measure that will decrease the speed of flow and conflicts with the latest change but might be needed because users have to be educated about not depositing Ordinals in the wrong address. 

This means removing the copying ability from the account header:

Account header as it currently is:
<img width="307" alt="Screenshot 2023-02-21 at 22 30 40" src="https://user-images.githubusercontent.com/119523541/220609268-21e93f70-9097-4e8c-9e4e-a1336b508c90.png">

---------

Returns to show total balance:
<img width="367" alt="Screenshot 2023-02-22 at 12 07 18" src="https://user-images.githubusercontent.com/119523541/220609300-8aebf80a-8098-41af-8103-34120239c4ab.png">

**Comment by 314159265359879** [comment]
Please no not like that last image. Under Account: Show the STX address and copy option.
Don't show the dollar amount but the exact STX amount.

Both are used to identify accounts or tell them apart. 

The dollar amount is wrong (because it doesn't take into account all tokens and it has less value for identification because of price fluctuations due to market conditions). Dollar value should only be shown per token (if available) on the balance rows of that token.

**Comment by badonyx** [comment]
@mica000 the "Token" and "Collectibles" addresses are both the same in your images...
