### ISSUE TITLE
Show full BTC and Ordinals activity from both Native SegWit and Taproot addresses

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3249]
Sacdaddy suggested:

_Possible improvement.  I sent an ordinal to my Hiro ord address this AM.  I can see it in my hiro wallet.  The activity tab in hiro does not display that though?  My first reaction would be that I would want to see it there.  I check that tab a lot as I go about my interactions w/the wallet._

![image](https://user-images.githubusercontent.com/33360391/220638955-8d042cd8-88b2-400a-b45c-5153d475ce15.png)

**Comment by markmhendrickson** [comment]
This issue should include broadly:

- The display of activity on Taproot addresses, whether BTC or Ordinals
- The display of Ordinals activity from the Native SegWit address (since it'll be supported by https://github.com/hirosystems/stacks-wallet-web/issues/3392)

Design-wise, we don't need anything new to show regular BTC activity from Taproot addresses (since it'll look the same as from Native SegWit).

For Ordinals activity from either address, we need a new design for the activity listing that indicates how a particular inscription is getting sent or received.

**Comment by mica000** [comment]
I found some old designs that were developed for NFTs. Are these representative of the states we need to cover for Ordinals?

https://www.figma.com/file/8CaxP6TRWskoTO9cmlvX9M/Archived-designs?node-id=2221-14454&t=NTq8Pp6mLWRm4xYQ-4

![Image](https://user-images.githubusercontent.com/119523541/230389802-c6e90ee0-029b-45b4-9474-01f5d10580b2.png)

**Comment by mica000** [comment]
Design note:

Set bid = Ordinal inscription
Swapr = Exclude and only show 
Squared or rounded avatar?

cc @mica000

**Comment by alter-eggo** [comment]
@mica000 @kyranjamie want to discuss problem of data fetching here. in order to display ordinals txs like in design we need to make request for each btc tx to check if there is inscription, example of request: https://api.hiro.so/ordinals/v1/inscriptions?output=ff07bb68e59a3fc10e8f8568290764b3702b9f5a27a4968003101d7c443a9b97:0

there are 2 possible ways here to reduce number of requests: 
- fetch inscription data only for pending txs
- implement dynamic rendering of activity list, and fetch data for each btc tx only once it is rendered

**Comment by kyranjamie** [comment]
To elaborate on this a little:

We need to do a request for each bitcoin transaction's _input_, which could be many requests per transactions. This presents problems technically as it means we may have to fire 10s or 100s of requests to figure out if inscription transfers are being made on the activity page, which can run into rate limiting and other problems. Further, there could also be many inscriptions per transaction.

I believe these designs were made with Stacks asset transfers in mind, which are typically contract calls and go 1:1 with assets. Ordinals trasfers on bitcoin work a bit differently, and should really be seen as _contents of a bitcoin transaction_, rather than a transaction themselves.

As such, I think the UI should display inscription transfers as children of a transaction, rather than a transaction item per inscription.

**Comment by markmhendrickson** [comment]
My understanding is that there are two most common scenarios with inscriptions:

1. **Simple transfer** in which the inscription is always on the first input and so querying for inscription data for subsequent inputs would be practically unnecessary
2. **PSBT trades** in which a single inscription _may_ usually be on the first input, or it may be on subsequent ones after BTC is provided for payment, which would be trickier re: needing more queries to get the inscription data. I wonder if @fbwoolf has an idea given her work on PSBTs and testing. We could also confirm by looking at the top marketplaces' transaction format.

For the latter case, it's certainly possible that several inscriptions are transferred at once though this seems a lot less common at present moment given how PSBTs are implemented (and perhaps our v1 of this activity UX could only "look" for a single inscription in its most common input index).

> I think the UI should display inscription transfers as children of a transaction

This depends on whether we want to group activity by transaction vs. treat various, related events as atomic entries within the "Activity" area in general. 

E.g. currently we list out the transfer effects of Stacks contracts separately from the contract executions themselves. Though I do suspect that it'd be better / more logical to nest these transfer effects as children within the execution transaction itself so the user can see how a single transaction led to one or more transfers (in or outbound):

![Screenshot 2023-07-27 at 11 48 12](https://github.com/hirosystems/wallet/assets/28991/bc176fb9-8aa3-49c2-bc59-62f632368ab3)

> there are 2 possible ways here to reduce number of requests:
> 
> - fetch inscription data only for pending txs
> - implement dynamic rendering of activity list, and fetch data for each btc tx only once it is rendered

The former solution seems inadequate since we wouldn't end up showing inscriptions for a lot of transactions (and eventually, none of them, once transactions all settle for the user). We'll need a solution that displays inscriptions regardless of tx status.

The latter solution could work though I wonder how much latency it'd cause as the user scrolls. If we can display a subtle loading state and display inscriptions immediately as their inputs are queried and returned results, perhaps the effect would be good enough.

Alternatively we could paginate the activity list and only load for the first e.g. 10 transactions then query another 10 only once the user scrolls to the end.

**Comment by mica000** [comment]
Since I wont have the time to dive into the details of it right now, would be suuuper helpful if y'all would sketch out the information architecture of how you imagine this feature could work.

Maybe we can use the PSBT Fijam file which already has some preliminary discussion that we we take advantage of? https://www.figma.com/file/W3Bv2iU0L279vDEUurGgVU/PSBT?type=whiteboard&node-id=0-1&t=DzNGjN5bpF2OfrQi-0

**Comment by alter-eggo** [comment]
> The latter solution could work though I wonder how much latency it'd cause as the user scrolls. If we can display a subtle loading state and display inscriptions immediately as their inputs are queried and returned results, perhaps the effect would be good enough.

I feel like this one is might work, since we need dynamic rendering of activity list all the same. also we can cache response for a long period of time, so we will make that multiple requests only once 🤔
