### ISSUE TITLE
Support inscriptions on Native SegWit addresses (display and send)

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#3299]
I have gotten three reports of this in the weekend. Couple more last week. We have some improvements coming that should help prevent this. 
1. What users want to know most of all is if their Ordinal inscriptions are lost if they do send them to the native segwit address. 

I think if we add support for sending ordinals from taproot addresses we should also look at options to do so from native segwit addresses. 

2. A user also managed to send the ordinal to a legacy Bitcoin address (they found it on their account page on gamma.io) Any chance at recovering that?

**Comment by markmhendrickson** [comment]
https://github.com/hirosystems/stacks-wallet-web/pull/3273 should help resolve the UI confusion greatly.

We do indeed to provide a way to withdraw these ordinals from non-taproot addresses as well, since users will inevitably still end up depositing a certain number of them there, and even if the process requires FAQ-based instructions.

**Comment by markmhendrickson** [comment]
We may want to simply support Ordinals on Native SegWit addresses in general, on par with Taproot (e.g. show them under "Collectibles", allow for sending from there) in addition to protecting against missends during BTC transfers with coin control similar to that we have for retrieving BTC from Taproot addresses now.

**Comment by markmhendrickson** [comment]
@kyranjamie this is resolved yea?

**Comment by kyranjamie** [comment]
@alter-eggo did this yeah
