### ISSUE TITLE
Refactor address vs. BNS name entry for recipient field in send form

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#3366]
This issue builds on https://github.com/hirosystems/stacks-wallet-web/issues/3364. Reusing the same field for bns names and recipients has proven difficult and error prone.

![CleanShot 2023-03-06 at 10 00 27@2x](https://user-images.githubusercontent.com/1618764/223064021-002c9076-3827-46be-bf64-a481c89ca3c9.png)

While we can fix the implementation, we've spent too much time on this, and the consequences of it going wrong are severe enough that, we should also reconsider the design of this component, provided that will simplify the implementation without a huge UX sacrifice.

@mica000 would be great if you could explore a few alternative UI for this for us to discuss & consider.

<details>
<summary>Some ideas</summary>

1) Having a toggle/tab interface where it's either recipient or bns name (not both). UI could prompt users entering a BNS name and even auto-switch to the bns tab if a name is detected.

2) A separate "Look up BNS name" flow, opening a modal with a search box, and the ability to look up a name. When found, the recipients actual address is entered to the recipient field.

</details>

**Comment by markmhendrickson** [comment]
@mica000 while we're doing this, let's add a "pending" state for BNS lookups as well? Since right now the API can be slow to respond to the user's entry, and while the user is waiting for the form to recognize a name they've entered, they may wonder if it's just broken.

Additionally, it would benefit from a "BTC / STX address for BNS name not found" state if the lookup is done but no related address is found.

Finally, if the name resolves to a _contract_ and not just a simple address (per screenshot below), let's display a special state e.g. "Transfers to contracts are not available at this time".

![image](https://user-images.githubusercontent.com/28991/223998239-88564efc-f6cf-4427-9ccf-1a331eedab51.png)

And let's make sure to add new analytics events for the triggering of each of these lookup states, each with property `token` (e.g. `stx`, `btc`, fungible token address):

- `start_bns_lookup_for_send_recipient` when pending begins
- `finish_bns_lookup_for_send_recipient` when finished with property `success` (bool), with bool indicating whether BNS name resulted in address value or not, and if it did, `address_type` as `principal` or `contract` depending on whether the value was a simple address or a contract

**Comment by markmhendrickson** [comment]
Also, it appears as though if the BNS name resolves to a contract recipient, we're allowing the user to proceed to the confirmation screen but simply stripping the contract out of the recipient value, leaving the address principal as the recipient.

We should change this to error and prevent the user from proceeding per the above state, in case the user does not indeed intend to continue receiving transfers to the BNS name they've assigned to their deployed contract.

**Comment by fbwoolf** [comment]
Current state of work...

![Screen Shot 2023-03-09 at 8 09 40 AM](https://user-images.githubusercontent.com/6493321/224057126-fd717070-d204-4db9-acc5-73e36f9893eb.png)

![Screen Shot 2023-03-09 at 8 10 02 AM](https://user-images.githubusercontent.com/6493321/224057147-19894852-55ee-4032-99e8-1ffa815d3e94.png)

![Screen Shot 2023-03-09 at 8 10 19 AM](https://user-images.githubusercontent.com/6493321/224057173-945e391c-d4b0-4b84-ac3d-91d75c4cc02b.png)

**Comment by mica000** [comment]
@fbwoolf @markmhx 

What do you think of adding this states to cover for the loading and the displaying of the address?

This might increase the content vertically so a footer could be added to prevent the "preview" CTA from disappearing in the scroll. @fbwoolf Let me know if this is the case.

<img width="482" alt="Screenshot 2023-03-09 at 16 21 52" src="https://user-images.githubusercontent.com/119523541/224070158-dc8414b5-aa07-4a05-9f63-7e4b750fc903.png">


Figma: https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1807-77609&t=aN1XBe9LZW9tw8mp-4

**Comment by mica000** [comment]
![Image](https://user-images.githubusercontent.com/119523541/224673010-12deda70-ddd3-4e14-8902-576a9098f6ad.png)

Updated design: https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=2045-86268&t=KrrJ8n7OQXEcbt9x-4

**Comment by markmhendrickson** [comment]
Looks generally great to me! I've added some minor comments in Figma.

**Comment by fbwoolf** [comment]
@mica000 what do we want to do in this case when the address resolves > but there is an error... right now the error animates and appears above the address, but should it replace the address in that space?

<img width="484" alt="Screen Shot 2023-03-18 at 7 20 52 PM" src="https://user-images.githubusercontent.com/6493321/226147056-034452de-fe1f-472b-9eae-47e27b46cb8a.png">

**Comment by mica000** [comment]
@fbwoolf are you asking of the error and address should be swapped in this case? If so, yes, makes sense!

**Comment by fbwoolf** [comment]
> @fbwoolf are you asking of the error and address should be swapped in this case? If so, yes, makes sense!

Yep, I wasn't sure if they should both show or if the error should replace the address (if there is an error once the address resolves) ...thx for feedback, I'll swap them in this case.
