### ISSUE TITLE
Wrong deep link to explorer contract

### ISSUE THREAD

**Issue by hugoclrd** [blockstack/blockstack-app#3591]
On the screenshot below, there is a contract call to a custom network (a subnet on tesnet).
The deep link to the contract function `mint` on the explorer goes to the testnet network `?chain=testnet`.

Expected behaviour: it should link the custom network `?chain=testnet&subnet=https://api.subnets.testnet.dev.hiro.so`.
We might need to bring the Explorer team in the loop to know if these query params are the definitive ones or subject to change (cc @He1DAr)

<img width="350" alt="Screenshot 2023-04-24 at 14 49 11" src="https://user-images.githubusercontent.com/911307/234001273-f513e161-a573-4ff1-a491-4e5d3415136b.png">

**Comment by hugoclrd** [comment]
Note: exact explore query params to be confirmed: https://github.com/hirosystems/explorer/issues/1240

**Comment by pete-watters** [comment]
@markmhendrickson , this issue seems very old and upon checking the code I can see that the only place we use `ExplorerLink` now is in `test-app`

Since we moved to Leather and made the global Header we don't show this in the header in the production version of the wallet. 

Do you think it's OK to close this or at least to reduce the severity?
