### ISSUE TITLE
Always show account number in avatar instead of first letter if BNS username available

### ISSUE THREAD

**Issue by DeloonCasino** [blockstack/blockstack-app#3606]
When an account has a BNS domain, it switches from "Account167" to "domain.btc" in the Switch Accounts tab. 

Please add an option to show both, Account167 and domain.btc. This makes it easier when using the scrollbar to find the last edited account. 

Imagine all account numbers switched from
Account154 = 785273.btc
Account155 = 857573.btc
Account156 = 427937.btc

Makes it tough to find the last position, for example while editing domains to BNSx.

**Comment by markmhendrickson** [comment]
Good suggestion!

**Comment by 314159265359879** [comment]
I think this could be implemented simply by always showing the number in the sphere in front of the account instead of showing the first character of the account name in it when there is a domain name registered to it.

![image](https://github.com/leather-wallet/extension/assets/33360391/c6f5a100-67ec-469f-ad6c-916335437276)

Perhaps it can be picked up together with a fix for this issue: https://github.com/leather-wallet/extension/issues/4483
