### ISSUE TITLE
Resolve errors from Blockstream for "Retrieve BTC" users with hundreds of inscriptions

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#3631]
It doesn't appear it has been reported in the wild yet but Blockstream's API limiting re https://github.com/hirosystems/wallet/issues/3481 could theoretically impact "Retrieve BTC" usage as well

**Comment by kyranjamie** [comment]
451 is _HTTP 451 Unavailable For Legal Reasons_, likely region blocking. Doubt this is a rate limiting problem.

**Comment by markmhendrickson** [comment]
It appears 400s are being produced as well. Not sure how much of each type but perhaps @314159265359879 has more context on the behavior exhibited in https://github.com/hirosystems/wallet/issues/3481

**Comment by 314159265359879** [comment]
So far most of the cases (BTC balance not displayed) I have seen were resolvable by adding an allow rule to a firewall or other kind of blocker and/or by switching IP to a different jurisdiction via a VPN. 

Perhaps those 400's are returned because of "too many history entries" issue described here: #4248

**Comment by 314159265359879** [comment]
> It appears 400s are being produced as well. Not sure how much of each type but perhaps @314159265359879 has more context on the behavior exhibited in #3481

A user is hitting 400's here and Bitcoin balance isn't getting displayed:
![image](https://github.com/leather-wallet/extension/assets/33360391/48c25b44-3f5c-4ece-a1c8-4e55686731f0)
I can confirm this is due to "too many history entries"
https://blockstream.info/api/address/bc1q58r0usu75zruj9wa3gqfdtkrzvguqacwmsnnmn/utxo
https://mempool.space/address/bc1q58r0usu75zruj9wa3gqfdtkrzvguqacwmsnnmn

Other account in the same Leather wallet
![image](https://github.com/leather-wallet/extension/assets/33360391/0ab5ae7a-4bdf-42e2-b92e-ab320a2b6e3f)
I can confirm this is due to "too many history entries"
https://blockstream.info/api/address/bc1qew9c9tn8qsvy6rks8s73gm2yseqz0jycmgd94w/utxo
[bc1qew9c9tn8qsvy6rks8s73gm2yseqz0jycmgd94w](https://mempool.space/address/bc1qew9c9tn8qsvy6rks8s73gm2yseqz0jycmgd94w)

I don't think we have a solution for this yet. It would require a custom API that allows retrieving any amount of history/UTXO's to be checked. 

Would this issue be resolved if UTXO's are consolidated?

**Comment by markmhendrickson** [comment]
Our own nodes for querying could help with resolving this or paid Mempool plan might help as well. It looks like we need to fix tracking for Blockstream (and other APIs) to get captured:

<img width="429" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/463b7bba-3db1-465e-bfb2-3b1c1f82a68b">

**Comment by markmhendrickson** [comment]
Can we use blockchain.info as a backup e.g. https://blockchain.info/balance?active=bc1qke8cq9kkvpwvm74rrvd7lhxl3d0faw4qau8lzn ?

**Comment by kyranjamie** [comment]
This would only allow us to show the address balance, and not tx history nor ability to send transactions.

**Comment by markmhendrickson** [comment]
I presume https://github.com/leather-io/issues/issues/215 will resolve this issue

E.g. https://mempool.space/api/address/bc1qdagxsxz3ccsje9k82dykg5ewtj83hdef7xsjy3/utxo resolves fine whereas https://blockstream.info/api/address/bc1qdagxsxz3ccsje9k82dykg5ewtj83hdef7xsjy3/utxo doesn't

**Comment by markmhendrickson** [comment]
The build on https://github.com/leather-io/extension/pull/5690 does indeed resolve it for me.

**Comment by markmhendrickson** [comment]
@alter-eggo just to confirm, the relevant queries for BTC retrieval are also switched to Mempoool with #5690?

I spoke too early above in terms of testing. I confirmed https://github.com/leather-io/extension/issues/4248 is resolved, not this particular issue.

**Comment by alter-eggo** [comment]
reopened to double check

**Comment by markmhendrickson** [comment]
@alter-eggo have you been able to double check on your end?

**Comment by alter-eggo** [comment]
@markmhendrickson tested and all good here
