### ISSUE TITLE
Resolve invalid request error during auth with @didtools/pkh-stacks

### ISSUE THREAD

**Issue by dabuchera** [blockstack/blockstack-app#3702]
Hi
I'm running right now into the following error. It is a app which I'm working one where users can sign in with their stacks wallet to a [ceramic](https://github.com/ceramicnetwork/ceramic) app. Things were working 1-2 months ago but now I'm not sure if the error is coming from the wallet or [@didtools/pkh-stacks](https://github.com/ceramicnetwork/js-did/blob/481f76935c2379c03f043c1b9aed5bcbf344feea/docs/modules/pkh_stacks.md?plain=1#L11)

![image](https://github.com/hirosystems/wallet/assets/53481997/e932b055-2952-4da2-b411-fb5c67d2b080)

Thanks

**Comment by dabuchera** [comment]
Possibly from here:

https://github.com/hirosystems/wallet/blob/3775a6c7776a0cfe541bccbc0009140a0f55c8f4/src/app/pages/stacks-message-signing-request/stacks-message-signing.utils.ts#L41

**Comment by kyranjamie** [comment]
Thanks for reporting @dabuchera 

We have a check here https://github.com/hirosystems/wallet/blob/442f78720280f11600584e64ee5e4138113215be/src/app/store/signatures/requests.hooks.ts#L52-L71 that throws if the request isn't valid. Could it be that your request [isn't passing these checks](https://github.com/hirosystems/wallet/blob/442f78720280f11600584e64ee5e4138113215be/src/app/common/signature/requests.ts#L62-L101). Steps to reproduce would be helpful.

We haven't changed the behaviour of this in a while, but the latest router update does make errors thrown more prominent.

**Comment by pradel** [comment]
@kyranjamie I spent some time trying to see what's going on but not sure exactly what to do. Nothing changed on our app side and the calls to `window.StacksProvider.signatureRequest` just stopped working in both Hiro and Xverse too, Xverse is crashing when we do the call. The fact that both wallets are affected makes me wonder if the issue is coming from one of the stacks.js deps that was updated on both wallets.

To reproduce you can create a simple js page and do the following code

```ts
import { createUnsecuredToken } from 'jsontokens'

const token = createUnsecuredToken({ message })
const { signature } = await window.StacksProvider.signatureRequest(token)
```

The following string is passed as the message content
```
signData localhost wants you to sign in with your Stacks account:
SP3VCX5NFQ8VCHFS9M6N40ZJNVTRT4HZ62WFH5C4Q

Give this application access to some of your data on Ceramic

URI: did:key:z6MkgAyigdUgCJxGnycPEwYmNkqDWh3vcaZQ4xYaJ3vBG33E
Version: 1
Chain ID: 1
Nonce: WR1JgoJhi6
Issued At: 2023-05-30T16:26:30.307Z
Expiration Time: 2023-06-06T16:26:30.307Z
Resources:
- ceramic://*
```

Do you see smth wrong with the following code?

**Comment by kyranjamie** [comment]
I'm not sure what's changed here but traced down the issue a little further

https://github.com/hirosystems/wallet/blob/686482e92851cf4f1a87a1e2856ca3003352d93e/src/app/common/signature/requests.ts#L74-L75

`TokenVerifier` throws the error

```
MissingParametersError: a signing algorithm and public key are required
    at new TokenVerifier (verifier.js:11:1)
    at verifySignatureRequest (requests.ts:75:1)
```

because public key and signature are undefined. This would be expected if you're using a `createUnsecuredToken`, but I'm not sure how it would've worked before.

**Comment by pradel** [comment]
I can confirm that this is also the issue I am having, could it be that before the error was thrown but not catched so the flow was still continuing?
It's really strange that this behavior broke in both Xverse and Hiro wallets while it was working in both just fine. Do you have an idea for a fix? This one is a big blocker for us and means the Stacks Ceramic integration is not working anymore on mainnet.

**Comment by pradel** [comment]
@kyranjamie I spent some time to find in which version the issue was introduced. Version **4.22.0** is working fine, version **4.23.0** is the one that first introduced the issue. So the regression happened in one of these changes https://github.com/hirosystems/wallet/compare/v4.22.0...v4.23.0
