### ISSUE TITLE
Balance displayed as `-1` with pending transfer

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/blockstack-app#3716]
Ran into this with a fresh account - after sending some STX to it the main page shows a balance of -1 while the activity tab shows the correct amount.

![Screenshot from 2023-05-16 15-33-34](https://github.com/hirosystems/wallet/assets/9038904/80eb7d69-57e4-470e-b249-58912680a476)

![Screenshot from 2023-05-16 15-33-51](https://github.com/hirosystems/wallet/assets/9038904/a7899c5d-af00-49fa-a944-ec46d3958780)

**Comment by 314159265359879** [comment]
Thanks for reporting Jason! Another user reported this too.

**Comment by 314159265359879** [comment]
I see more examples: 
![image](https://github.com/hirosystems/wallet/assets/33360391/384746fd-b191-497f-841b-ee1b2fa5828e)


On this address I see a pending (yet unprocessable because the nonce is already used) transaction, does that have anything to do with this bug?
![image](https://github.com/hirosystems/wallet/assets/33360391/aefb8c4e-5458-4c30-a880-d1d76e25f26b)

**Comment by markmhendrickson** [comment]
@alter-eggo any idea if your recent work re: available balances could have been related to this at first glance?

**Comment by 314159265359879** [comment]
This looks like two issues
1. (this?) Don't subtract the balance if the transfer is outgoing but the transaction is [unprocessed/unprocessable](https://github.com/hirosystems/explorer/issues/1038) (we need that state to be added, I think it would resolve this right away because it would not be pending anymore). Not sure what to do meantime, I am hoping @alter-eggo has a creative idea :-)

2. fees from incoming transactions are subtracting: https://github.com/hirosystems/wallet/issues/3761

**Comment by alter-eggo** [comment]
yeah, prob it is affected by work with available balances. I'll take a look

**Comment by alter-eggo** [comment]
fixed in this issue https://github.com/hirosystems/wallet/issues/3761
can we close this one? @markmhx @314159265359879

**Comment by 314159265359879** [comment]
Tested, confirmed fixed, thanks @alter-eggo!
