### ISSUE TITLE
Show summary of transfer in PSBT display UI

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#3923]
This was requested by apps, so I'm making a new issue to track it, though it is related to: https://github.com/hirosystems/wallet/issues/3849

It appears other wallets are showing a summary at the top.

cc @mica000 @markmhx 

Ours:
https://cdn.discordapp.com/attachments/1075823519688036494/1121875014661197924/IMG_3080.png

Others:
https://cdn.discordapp.com/attachments/1075823519688036494/1121875015034482769/IMG_3081.png
https://cdn.discordapp.com/attachments/1075823519688036494/1121875016053690429/IMG_3082.png

**Comment by markmhendrickson** [comment]
Thanks @fbwoolf. Let's pursue the more comprehensive enhancement of #3849 though since presumably we can apply logic that summarizes what the user will receive to their address while also summarizing what they'll send.

I'd love to check in early this coming week on the work needed there to see how we can move it forward, perhaps during kick-off or technical planning if we need more time to dive through the complexity as a team.

If you have time before then, please add a t-shirt label and any notes that come to mind for you on #3849 re: design or technical considerations given your work on this UI to date.
