### ISSUE TITLE
Show HTML previews for inscriptions (e.g. recursive)

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4077]
https://ordinals.hiro.so/sat/390660864168

https://docs.ordinals.com/inscriptions.html#sandboxing

**Comment by 314159265359879** [comment]
If we want to use this solution to show this inscription
https://ordinals.hiro.so/inscription/14effa0e0a947cc05cab869d50626cdaf2ad1cbc05f81dbc8d99cb763116f117i0

As it is displayed on ord.io:
![image](https://github.com/hirosystems/wallet/assets/33360391/0ba35ade-6bab-47cf-ad1e-286a801ef18b)

https://www.ord.io/bc1pd4fjc9cyg8wfgc3x7d3pcxc99tmn6vqw5gstp6hhmputm06rw2tqdqdtxd

Are there any changes needed from the ordinals-api too? Or rather the explorer so it is displayed there similarly too? @rafaelcr

**Comment by markmhendrickson** [comment]
@kyranjamie thoughts here on whether we can embed HTML previews safely in the wallet somehow, or whether we need to request a preview image (perhaps animated) from the API that can be used instead?

**Comment by kyranjamie** [comment]
I would be reluctant to add `iframe`s tbh, even if we can have a very strict CSP to lock things down. Is this feature in demand?

Embeddable content just seems like it'd create such as cess pit of scammers.

**Comment by 314159265359879** [comment]
@kyranjamie I agree we do not want to create such a hole in the wallet for scammers to take advantage of. We should still show some placeholder in the wallet, perhaps even a warning/explanation about the type of ordinal?

**Comment by 314159265359879** [comment]
I see this PR for[ embedding iframes](https://github.com/leather-wallet/extension/pull/4269) which can resolve this https://github.com/leather-wallet/extension/issues/4077

This recursive inscription doesn't load in that build (4269). Perhaps it is using something else. It should be displaying several .svg files on top of each other. Should this be covered by this PR or would that require a different kind of enhancement?

Example inscription: https://ordinals.hiro.so/inscription/6795bcea8de910906a20643a300484005b3df113a9246a43b7408efb8a0036a7i0
text/code of the inscription:
`<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1025 1025" height="100%" width="100%" id="bitcoin-face-for-werner.btc">
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/8723751cfc76f030dcd8c7be883fc0ab95eec8a4274f55caf00d20f151fbfe64i0" id="background-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/0991d1034aa2f40b13b82774f9b6faccee23b037ad352b5edcca27e8cb05bde9i0" id="body-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/c029f0afeea66091a573fba60dbe3e5e7301828dc520610a9eae120364a6b5d0i0" id="head-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/49f8014d388de06928f604d2ac6eb7380d2fcfa441570ce96004e62da21945b5i0" id="ears-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/6ec67f9a3061fc866c3cbcd9c1a30b2ae1c9e3c20f486bd689d3e3886bbf725di0" id="chain-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/7b16e48fbc6658a6646b660d50af0f955abaa37bb1b8f0532ba53158bf71a6dbi0" id="mouth-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/b439feeb2356b77bdc63617dc8a3437b0cbbe4d261b8f2041eb4d81bfec92da7i0" id="nose-1"></image>
<image height="100%" width="100%" y="0" x="0" xlink:href="/content/629079513bdae4bc955fbb309fdbc8092ed4761f43e2c46144cc8cb04644921bi0" id="eyes-1"></image>
</svg>`

**Comment by 314159265359879** [comment]
Another example of recursive inscriptions that do no currently show in the wallet, they will appear blank or black. 

![image](https://github.com/leather-wallet/extension/assets/33360391/1c178d74-9367-4a66-9f9c-790dc6a30a3a)

Here are two more examples of an ordinal that doesn't show yet on the Hiro explorer and the code it uses:
https://ordinals.hiro.so/inscription/604fec792efe3526a8989d61c44ed52f30bdf5a807a34c86428edf1700055bcei0
https://ordinals.hiro.so/inscription/30a2fdd98d363d182f75ce96ddc6b3ffe1eeb29d2a05e748a208a49b033557a2i0 

![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/1ce9559f-0794-42c6-84c3-0e9127301831)

This is the original inscription being expected to be displayed recursively via the code in `#32321985` (and `#...88`): https://ordinals.hiro.so/inscription/604fec792efe3526a8989d61c44ed52f30bdf5a807a34c86428edf1700055bcei0


------------------------------------------------------------------------------------------------------------------------------------

This is an example of an ordinal showing up black in the wallet, although displaying correctly on explorer.hiro.so:
https://ordinals.hiro.so/inscription/efba55d53fb0f11d091ee0eca2f8d5a0fab4d4fdde35733d03c40f9c5c429dd0i0

![image](https://github.com/leather-wallet/extension/assets/33360391/e11bd8d0-2820-41cc-8ce1-4a5321e7c35b)

This is what is [displayed in ordiscan.com](https://ordiscan.com/inscription/35318044) (see code and submodules, avif and js)
![image](https://github.com/leather-wallet/extension/assets/33360391/a7d39bd6-ebb7-4372-b4dc-374766921b02)

Is it safe to show this in the wallet? if not can we display a message about that in the wallet instead to help users understand why it is blank/black instead of displaying their inscription image?

**Comment by 314159265359879** [comment]
The owner of this inscription would like this displayed as an image if possible. It is a cursed recursive inscription:
>Note the difference in short inscription number, reported here: https://github.com/hirosystems/ordhook/issues/202

https://ordinals.hiro.so/inscription/81433a25e784366a7db917af98393be6eba232a03646e1fc072904fc3b8803b2i2 
![image](https://github.com/leather-wallet/extension/assets/33360391/d0a966a9-1d2d-427f-9edd-ef665480dac6)

https://www.ord.io/81433a25e784366a7db917af98393be6eba232a03646e1fc072904fc3b8803b2i2
![image](https://github.com/leather-wallet/extension/assets/33360391/7619e2e1-d99a-4005-b52f-08a06641e5c6)

**Comment by markmhendrickson** [comment]
We discussed this earlier this week with @kyranjamie and @janniks and concluded that it seems safe to attempt an iframing approach for HTML inscriptions, one in which iframes are loaded only when in view / within the viewport, to avoid possible performance issues to loading many on a given screen as the user scrolls.
