### ISSUE TITLE
Ordinals not loading beyond the first 20

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4338]
From a user:

> I have 400 inscriptions in my wallet:
> 
> https://ordinals.hiro.so/inscriptions?a=*REDACTED* (as requested by user)
> 
> yet my hiro wallet (chrome browser addon) displays only 20. I can only see other ones when i browse the btc in the taproot wallet... I can't see my inscriptions on my leather wallet or send them anywhere, yet they are being displayed in every single ordinal explorer i've found on the net. Why? How can I get access to my inscriptions?
> 
> These 20 inscriptions are exactly only what's on first page of your hiro ordinal explorer! It the wallet correctly using your own api? I built an explorer using your api for my website and it uses page parameter to read ALL of the ordinals - normally before i applied that change i was also seeing only first 20 ordinals. It looks like a bug in the wallet. How do I get access to the rest of my ordinals?! any idea?

I think it may be related to this recent fix from Hiro: https://github.com/hirosystems/ordinals-explorer/issues/92#issuecomment-1723697958

It looks like the wallet needs an update to accommodate, right?

**Comment by angree** [comment]
It looks like the wallet is using Hiro ordinal API, where it only provides the first 20 inscriptions by default. The way to fix it is to call the api like this:
$apiUrl = "https://api.hiro.so/ordinals/v1/inscriptions?address=" . urlencode($address) . "&limit=$limit&offset=$offset";

where limit should be changed to maximum 60 (to minimize number of calls) and offset should be 0, then 60 (limit amount), then 120 and so on, until an empty page is retrieved. (alternatively to reduce number of calls we may stop if the last page has returned less than limit=60 inscriptions) 
So wallet content should be retrieved in pages and multiple calls, instead of one call. That is the bug I think (I had the same issue integrating hiro api for my website)

**Comment by fbwoolf** [comment]
@alter-eggo this should be handled by the infinite query, you might have more context here?

**Comment by alter-eggo** [comment]
hm, I impersonated the address, and everything looks ok with inscription loading.
@314159265359879 could you ask please user's app's version

https://github.com/leather-wallet/extension/assets/46521087/4b0471c0-469c-465f-84e7-fee36887a5fd

**Comment by 314159265359879** [comment]
@alter-eggo the user said they are using the latest version on Chrome, here is a quote:
> I am using the most recent version from chrome store - v6.9.2

If you see all 400 loading and the user is somehow blocked perhaps it is related to a more local connection issue or restriction.

**Comment by 314159265359879** [comment]
I have sent the user an email to check some more things such as console errors (if any) or check if it is caused by location based restrictions.

**Comment by angree** [comment]
i have 7 computers, 2 vpns, 2 remote machines and so on. I will check it now on other computer with and w/o vpn. 
     
      
       
        Dnia 10 października 2023 12:10 Werner ***@***.***&gt; napisał(a):
       
    
       
         
 github.com @alter-eggo  the user said they are using the latest version on Chrome, here is a quote: 
 
 I am using the most recent version from chrome store - v6.9.2 
 
 If you see all 400 loading and the user is somehow blocked perhaps it is related to a more local connection issue or restriction.

**Comment by angree** [comment]
it is not related to my ip as my ip is the same on all computers. I just installed it on brave instead of chrome (on this computer that chrome had problem with) and IT WORKS. Thanks. Please remove a link to my wallet from the original github post.  
     
      
       
        Dnia 10 października 2023 13:10 Werner ***@***.***&gt; napisał(a):
       
    
       
         
 I have sent the user an email to check some more things such as console errors (if any) or check if it is caused by location based restrictions.

**Comment by 314159265359879** [comment]
I have redacted the address in the first post. Closing this.
