### ISSUE TITLE
Accounts beyond account 1 are not displayed

### ISSUE THREAD

**Issue by mijoco-btc** [blockstack/blockstack-app#4373]
Wallet: v6.11.0
Browser: Chrome

Multiple accounts were always displayed on testnet and mainnet. I just signed out and connected to devnet and then signed back in and switched back to testnet and now only account 1 is displayed.

<img width="369" alt="Screenshot 2023-10-18 at 11 53 03" src="https://github.com/leather-wallet/extension/assets/4384929/abe8526b-b30d-4ac8-87c9-ee024a9d4caf">

**Comment by mijoco-btc** [comment]
Update: I uninstalled the extension and reinstalled and normal behaviour returned.

Maybe a glitch with my workspace.

**Comment by 314159265359879** [comment]
Hi @radicleart thanks for the update. 
When you set up a wallet with a secret key it is expected to check addresses for activity/balance and then display those that have any. Perhaps something prevented that process from running. 

Alternatively you can always reveal them again by clicking "add account" however many times to reveal them all again. Since this is not ideal for a key that has hundreds of accounts there is also a console command you can use in that case. See option 2 here: https://leather.gitbook.io/guides/accounts/several-accounts-missing

Closing this issue for now. Feel free to reopen if it does pop up consistently.
