### ISSUE TITLE
Improve PSBT signing UX

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#4469]
**Updates**

- Removed subtitle under “Approve transaction” 
- Moved pill to the upper right side
- All links were replaced to Leather links (underscored and black)
- Branding colors updated on
  - All text
  - Wrapper
  - Tags
- Updated notification so it's using the new call out (https://github.com/leather-wallet/extension/issues/4311)
- Replaced “see details” for chevron
- Updated error state “failed to sign”

Designs
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?type=design&node-id=3799-63150&mode=design&t=w5ciwIxfUs43qY3b-4

**Comment by markmhendrickson** [comment]
@mica000 these updates look generally good! I've written a few addressable comments in Figma, however.

Also, I'd suggest we add the following update to this issue:

- Show `SINGLE |  ANYONECANPAY` as "Certain" ([per Slack conversation](https://trustmachines.slack.com/archives/C05K6H9T545/p1698408697488809)) since the transaction would be invalidated if someone subsequently tried to change any of the inputs or outputs that affected the guarantees ("You'll transfer" or "You'll receive"), even if they change other inputs or outputs that _don't_ affect those guarantees. I.e. the user can be certain that those guarantees will stand, or the entire transaction will be invalid

**Comment by markmhendrickson** [comment]
I've broken the SIGHASH type question into its own issue here: https://github.com/leather-wallet/extension/issues/4608
