### ISSUE TITLE
Fix recognition of active account during Stacks contract execution

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4599]
The first account in the wallet is shown as the active one for signing, both in the modal's header and in the "switch account" drawer when opened, even when a different account has been connected to the site e.g. https://stacks.gamma.io/

https://github.com/leather-wallet/extension/assets/28991/3000e1cf-3383-410c-9498-503836d30fd1

**Comment by markmhendrickson** [comment]
Also affects ALEX here so it doesn't seem app-specific


https://github.com/leather-wallet/extension/assets/28991/d012fe5b-73be-4aa5-94dd-d70068ba998b

**Comment by markmhendrickson** [comment]
@314159265359879 can you recreate this?

**Comment by 314159265359879** [comment]
@markmhendrickson I have been able to reproduce this with 6.22.0. 
This also explains a couple reports by users from the past months.

**Comment by 314159265359879** [comment]
It is the same on Bitcoin apps and Stacks apps.

**Comment by 314159265359879** [comment]
Steps to reproduce (Stacks)
1. Sign in to stacks.gamma.io on account 4
2. Then on the Leather extension switch to account 1
3. Try to buy a random NFT
4. See the screen pop up with Account 1 top left (expected is account 4). 
5. Upon confirmation the transaction is still signed with account 4. 

**Or with bitcoin** 
1. Sign in to gamma.io on account 4
2. Then on the leather extension switch to account 1
3. Try to buy an ordinal or create an inscription
4. See the screen pop up with Account 1 top left (expected is account 4). 
5. On bitcoin this is a bit different... on unisat the transaction is signed with account 1 when inscribing something!
on magiceden there is no error and no broadcast... just "loading, please wait..." and no way to resubmit/sign
on gamma.io (buying a recent print for example) there is no broadcast after confirming. captured in a seperate issue here: https://github.com/leather-wallet/extension/issues/4859

**Comment by pete-watters** [comment]
I added Edgars fix [in this PR](https://github.com/leather-wallet/extension/pull/5152) based on [Edgars PR](https://github.com/leather-wallet/extension/pull/4923) .

However, when this is released, we will no longer see the account at all in the header as when implementing global headers https://github.com/leather-wallet/extension/pull/4655 we changed this header so that it only shows the logo and not the account:
![Screenshot 2024-04-03 at 11 09 12](https://github.com/leather-wallet/extension/assets/2938440/d3ec848e-3a93-47ca-991a-8f85fe016582)
