### ISSUE TITLE
Double padding in between STX and BRC-20 balances

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#4603]
Probably a relatively minor issue, but I am noticing there is double padding between my STX and BRC-20 balances, as shown in the screenshot where I inspected the element.

![Screenshot 2023-11-29 at 11 55 42 AM](https://github.com/leather-wallet/extension/assets/122313287/99ddf7aa-3ea4-4617-9064-aad64b01dab8)

**Comment by pete-watters** [comment]
I was checking this and it looked OK to me when I also had other tokens in between:
![Screenshot 2023-12-04 at 11 20 19](https://github.com/leather-wallet/extension/assets/2938440/b771e16f-8769-4e49-bfd1-b50a9ccae549)

I tried to send some `SATS` between my accounts then to check if it happens when you only have `BRC20` + `Stacks` but that failed 
![Screenshot 2023-12-04 at 11 21 21](https://github.com/leather-wallet/extension/assets/2938440/91b984b6-a926-4f45-b20d-d2b56112d577)

**Comment by markmhendrickson** [comment]
I'm also seeing this:

<img width="401" alt="Screenshot 2023-12-08 at 07 36 05" src="https://github.com/leather-wallet/extension/assets/28991/ed377697-c097-41a2-8c23-51f7e186da23">
