### ISSUE TITLE
Fix missing account in app nav during PSBT signing with Ledger (Bitcoin only)

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4657]
<img width="439" alt="Screenshot 2023-12-07 at 16 01 01" src="https://github.com/leather-wallet/extension/assets/28991/e05910a4-19cd-4c54-93cc-5b1f83ea77f7">

**Comment by pete-watters** [comment]
I will fix this as part of work in https://github.com/leather-io/extension/issues/4859. 

In the screenshot above for this bug we aren't showing anything in the header. 

Now we show a logo instead of the account
![Screenshot 2024-07-03 at 07 10 27](https://github.com/leather-io/extension/assets/2938440/023682a7-c8b2-4a54-8fd1-26e7cc7827aa)

That changed when implementing the global header. I will change it show that we show the account instead of the logo
