### ISSUE TITLE
Fix available balance for BRC-20 while sending

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4703]
E.g. here I'm seeing 4 BIMB under balances and in the token picker when initiating sending, but then it shows up as 0 BIMB in the form:

https://github.com/leather-wallet/extension/assets/28991/a91e9c65-022f-4bea-b632-7313cb611640

**Comment by pete-watters** [comment]
I took a look at this and I don't have `BIMB` but I do have `SATS`. I'm just wondering if this is as the amount is so small that its basically a dust amount and you can't get rid of it? 

Of my supposed 100M SATS I only have 99211647 available for transfer so I think that could be happening here

**Comment by kyranjamie** [comment]
Because BRC-20 operates outside the norms of bitcoin, there's no concept of dust, as far as I know (so long as the inscription transfer itself is inscribed on a UTXO above network dust threshold).

**Comment by pete-watters** [comment]
OK thanks Kyran! 

Reading into it a bit more(via our own tooltip) and I figured out the balance we show on the asset list is:
![Screenshot 2023-12-18 at 10 05 09](https://github.com/leather-wallet/extension/assets/2938440/59f5deb4-7ecb-4df3-a0c5-418818de2730)

I tracked back this work to [this PR](https://github.com/leather-wallet/extension/pull/3790) but it's light on details

@markmhendrickson:
-  do you have some inscriptions in this wallet in `bimb`? 
- should we show your `BRC-20` balance as the available balance

When I check in my wallet in the asset list it says I have  100M SATS but then I only have 99,211,647 available for transfer so I think that could be happening here. You can see below I have some inscriptions which are included in my asset list balance but excluded from my total balance

![Screenshot 2023-12-18 at 10 13 59](https://github.com/leather-wallet/extension/assets/2938440/2c975fb2-e115-4dbb-b237-134d301900c7)
![Screenshot 2023-12-18 at 10 15 42](https://github.com/leather-wallet/extension/assets/2938440/8d49c877-5006-4e25-b2f4-14b981ae8ff7)

**Comment by 314159265359879** [comment]
I have a wallet that has 1000 Fara
And It has a transfer inscription of 50 Fara (unused)

When I see the balance of FARA it is 1000

When I click send the available balance is 950 fara (the other 50 is already made transferable). 

This is the complete situation:
$FARA balance: 1000
Transferable $FARA: 50 
Available $FARA: 950

We should consider showing BRC-20 (for example $FARA) Balance and Transferable amount separately in the balance overview. Especially new users have trouble making sense of this. Some users do not realize they have already created a send inscription and the next step is to send that inscription and then they are surprised the balance is 950 instead of 1000.

**Comment by markmhendrickson** [comment]
Let's tackle this as part of [the send UX redesign project](https://github.com/leather-wallet/extension/milestone/76) more broadly.

**Comment by markmhendrickson** [comment]
I'm closing this issue since we intend to disable BRC-20 sends per https://github.com/leather-io/extension/issues/5773
