### ISSUE TITLE
Connecting Ledger to Leather sometimes freezes on the "successfully-connected-your-ledger" page

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4705]
chrome-extension://ldinpeekobnhjjdofggfgjlcehhmanlj/index.html#/bitcoin/successfully-connected-your-ledger

Seeing this on chrome
Bitcoin app 2.1.3 on ledger
![image](https://github.com/leather-wallet/extension/assets/33360391/583c0013-b226-4e0f-9565-d46cf3bbb943)

I have seen it pop up several times now, the wallet never connects. The X (upper right) can't be clicked to close the overlay, reloading the page is the only option. 

Sometimes it connects the next time sometimes it doesn't

**Comment by kyranjamie** [comment]
I've seen this using the newer testnet app but not on mainnet with this version

**Comment by 314159265359879** [comment]
I was connected to the testnet, tried connecting failed, connected to mainnet and kept failing. Signed out from the wallet, tried connecting again and it worked. 

I wonder if it had something to do with the testnet connection. I don't recall being on testnet the previous times I saw this but it was also less persistent then, I only had to reload the wallet and it would connect normally after that.

**Comment by kyranjamie** [comment]
This is a particularly challenging one tbh. It's not because of the newer app version, as I earlier suspected.

I haven't managed to resolve yet, but my best suspicion is this is some react rendering/stale closure issue. We have a `delay(1250)` in the event stream to give the user time to see the _It's connected_ message. When I remove this, it works (albeit the view transitions still broken).

Equally, if I remove the view transition—but not the delay—it also works. This makes me think something's up with/changed with the render, such that the stream is recreated erroneously, causing it to rerun.

Update: so it seems this broke because of the the routing changes. When I remove `<ModalWrapperBackground/>`, and put the routes back in `app-routes.tsx` it works as expected. There's a subtle difference in behaviour with this routing mode where, when navigating between the steps, the container component is dismouted/remounted. This doesn't happen without the `/*` routing behaviour. cc/ @pete-watters 

@pete-watters any objections if the solution to this is taking a step back and removing the dynamic routes/background state stuff?

**Comment by markmhendrickson** [comment]
@kyranjamie @pete-watters any updates here on how we want to approach this issue?

**Comment by kyranjamie** [comment]
This issue was fixed by @edgarkhanzadian in https://github.com/leather-wallet/extension/pull/4779

I think we're in agreement that we need to back track on routing changes and have global routeless modals for the core settings actions
