### ISSUE TITLE
Ensure all HTML inscriptions appear in collectibles with previews

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#4809]
I just bought a cursed inscription through MagicEden to test our ability to store and display cursed inscriptions within Collections.

It does not show up in my Collectibles, and actually shows up as a UTXO "not" containing an inscription when using the "Retrieve BTC" feature [image attached below]

Inscription: https://ordinals.com/output/12192c9310e2a314fc31ecd26cf8997338da340b507f0f9e98c2c72e26d717c0:1

Transaction: https://mempool.space/tx/12192c9310e2a314fc31ecd26cf8997338da340b507f0f9e98c2c72e26d717c0

![Screenshot 2024-01-15 at 11 28 41 AM](https://github.com/leather-wallet/extension/assets/122313287/9ff13db9-6306-46b7-8d09-1ab1bbbf3e62)

**Comment by 314159265359879** [comment]
I tested this one, looks like it does show up, it only took a couple of minutes after the transfer was confirmed on the blockchain. 
![image](https://github.com/leather-wallet/extension/assets/33360391/9e8fa0ae-f0e6-4647-a9e9-ed38bec3d6a2)

Perhaps the inscription above isn't displayed because of its source code?
https://ordinals.com/inscription/ba20139b3fa0d0eb5f87e05708adae844c0e815db466ae89105169e47f5a7595i2
```
<script
  t="185,319,379,336,210,212,334,331,311,196,292,306"
  e="0"
  b="#c799ff"
  r="813000"
  src="/content/ea8fe5775eda290616d1fb42d0f1e65950ad4bc78485d3e6a89acde4476fa726i0"
></script>
```

**Comment by brandonmarshall-tm** [comment]
Ah yes, that would probably explain it. Though I wish we had a workaround for that, because it looks like more projects are using scripts in this way and Hiro doesn't seem to support them.

Another example of a non-cursed ordinal with script:
https://ordinals.com/inscription/5aa1e09c67aef0afb5c9711627784acb6f329181452feda487afcc6bceffde65i302
https://ordinals.hiro.so/inscription/5aa1e09c67aef0afb5c9711627784acb6f329181452feda487afcc6bceffde65i302

**Comment by 314159265359879** [comment]
https://ord.link/49013928 This is one we are seeing displayed normally in the wallet it has this source code. So some script does run?
ce6ac6ce0e3fab436216d079c5bf76d949314458c19c3e0eb65ccd6e306ce398i0
```
<script
  src="/content/d91650a911e27c5402ffd45893b17023e0ede8cb6912aa11fee0bbb264de2bfdi0"
  data-p="ae31b4cd9a38d68a933a2cfffb14660eb402e39a8069352ec65392b696691f9ei0,ss,4,100,1,d"
></script>
```

**Comment by brandonmarshall-tm** [comment]
Renamed the issue to be more in-line with what the actual problem is. Certain inscriptions containing <script> tags are being blocked, however these are still "internal" scripts and not external-facing ones, so should not be sandboxed.

**Comment by 314159265359879** [comment]
I see reports of users mentioning that RISC ordinals are not showing up either. These are recursive inscriptions child/parent with script tags, JS and HTML. I understand that some scripts may not be safe to execute in the wallet but we should show a placeholder so they can be interacted with and sent. 

When they are in the taproot address, the user will be able to interact with these via Magic Eden and other supporting marketplaces. 

It does look like ordinals.hiro.so indexer has caught up but users are reporting that these inscriptions are showing as uninscribed BTC rather than ordinal transactions. 

I checked a couple of the transactions to see if the user got inscriptions with their outputs and it does look that way for[ this address](https://mempool.space/address/bc1p954afza780rg0322lyejrtgsxj67qrgu90uypgydywwhgpsy9xvs0xm6p8):

1.
Inscription transaction: https://mempool.space/tx/66971672febe2dc428122f29966c9a8294db863374a428497339bd9f5c480d43
Output with the inscription https://ordinals.com/output/66971672febe2dc428122f29966c9a8294db863374a428497339bd9f5c480d43:72
Inscription number: 66971672febe2dc428122f29966c9a8294db863374a428497339bd9f5c480d43i71
#56731572
https://ordinals.hiro.so/inscription/66971672febe2dc428122f29966c9a8294db863374a428497339bd9f5c480d43i71

2.
https://mempool.space/tx/a42619616548586a7862b944a60ac05dd02e4b57e23722147edb133c3bebaf31
https://ordinals.com/output/a42619616548586a7862b944a60ac05dd02e4b57e23722147edb133c3bebaf31:380
a42619616548586a7862b944a60ac05dd02e4b57e23722147edb133c3bebaf31i379
#56737522

3.
https://mempool.space/tx/2c769643f12359f598f03376f60a013b0bd2dbcf3e0ac61627f5735814cf8e73
https://ordinals.com/output/2c769643f12359f598f03376f60a013b0bd2dbcf3e0ac61627f5735814cf8e73:479
2c769643f12359f598f03376f60a013b0bd2dbcf3e0ac61627f5735814cf8e73i478
#56736221

**Comment by brandonmarshall-tm** [comment]
Adding Pizza Ninjas to this list as well, since it's another higher-profile collection that is currently being recognized as uninscribed BTC

Ex: 
https://www.ord.io/56246276
https://ordinals.hiro.so/inscription/39399e536443446eda3f26ce7038178ec3b69157f38eaed19caea4614aabaf62i107

**Comment by fbwoolf** [comment]
We currently use the `ordinals.com/preview/...` to render in the iframe if type `text/html`.

**Comment by brandonmarshall-tm** [comment]
In the case where a preview can't be rendered, like Pizza Ninjas, it'd be nice to have some sort of placeholder. Rendering a placeholder with something like "Preview unavailable" would at least put users at ease that their inscription arrived into their wallet, and would still give them the ability to send it if desired. This is especially needed for the RSIC inscriptions because in order to be "activated" the user needs to send it to themselves.

**Comment by 314159265359879** [comment]
Linking to discussion on our slack related to quantum cats https://trustmachines.slack.com/archives/C0520G8J33M/p1707166443941859

Not displayed currently, also a series with:
1. child/parent inscriptions
2. there is .js involved (recursive module)

```
`<script
  c="cat0071"
  src="/content/627ae063b9e9d6de1ee2d981c96757f219724df8a1cd6652c4d3920deb0f901di0"
></script>
```

https://ordinals.com/inscription/4b31771df21656d2a77e6fa18720a6dd94b04510b9065a7c67250d5c89ad2079i71
https://ordiscan.com/inscription/53785931

**Comment by markmhendrickson** [comment]
It appears that Quantum Cats aren't showing up given an ID-related issue on the API side as reported with https://github.com/hirosystems/ordinals-api/issues/302.

@brandonmarshall-tm is it possible that Pizza Ninjas and RSIC are suffering from the same issue?

It's not clear to me if we're blocking certain HTML inscriptions in the wallet UI given script considerations or not, given @fbwoolf's indication that we're embedding previews from ordinals.com (not Hiro) and all relevant inscriptions seem to show up fine in ordinals.com as previews. 

@fbwoolf I assume if they show up fine on ordinals.com, they should show up fine in the wallet UI since we're not doing anything extra to filter or block scripts?

**Comment by fbwoolf** [comment]
> @fbwoolf I assume if they show up fine on ordinals.com, they should show up fine in the wallet UI since we're not doing anything extra to filter or block scripts?

Yes, that would be my assumption unless look into it further. We handle the html inscription type from Hiro data > then use the id given to us and render that preview from ordinals.com in the iframe.

**Comment by brandonmarshall-tm** [comment]
It seems like we have two main issues: The "owned by" is wrong for some of them, and most cursed inscriptions do not show up. Both are because of Hiro's API, so both should in theory be fixed with a reindex. But that has been pending for weeks now since we reported it

**Comment by fbwoolf** [comment]
@brandonmarshall-tm this merged PR should fix your svg issue. It will be in the next release:
https://github.com/leather-wallet/extension/pull/4933

**Comment by 314159265359879** [comment]
The user of this address mentioned that he has many of his ordinals not getting displayed in Leather. Perhaps it can be used to mock this address in the wallet after we make some changes to make sure we have them all covered. 
https://ordinals.hiro.so/address/bc1p98rqntc3xjyq2lurft709q8vw8wluq96tp98r96925hmaezeh09q8qdysj

**Comment by markmhendrickson** [comment]
> The user of this address mentioned that he has many of his ordinals not getting displayed in Leather

Has the user indicated if there's a type of inscription that doesn't get displayed in particular? It could help diagnose the underlying issue.

**Comment by fbwoolf** [comment]
@314159265359879 many of those aren't displaying in the Hiro explorer either, this example doesn't have a preview to display: https://ordinals.com/preview/efd0fb8ccaca2d1fc0691c8372952c644c81d7c58b1b5e627039f0f51cc7f268i0

**Comment by 314159265359879** [comment]
> @314159265359879 many of those aren't displaying in the Hiro explorer either, this example doesn't have a preview to display: https://ordinals.com/preview/efd0fb8ccaca2d1fc0691c8372952c644c81d7c58b1b5e627039f0f51cc7f268i0

I am afraid I didn't get more info from the user, which inscriptions were affected exactly. They made a general claim that everything was showing when they used an alternative wallet possibly exaggerating nothing was displayed in Leather. 

There is one more issue that popped up at a user who has ordinals on regenerated addresses. I see 429 errors in the console logs they shared and they are on account 111 so they are likely to hit the limit too. I am not sure if checking for inscriptions on non-zero index addresses alone could have the user hit the limit: https://github.com/leather-wallet/extension/issues/4948

**Comment by brandonmarshall-tm** [comment]
> @brandonmarshall-tm this merged PR should fix your svg issue. It will be in the next release: #4933

Just confirming that every inscription that shows up my Collectibles is now displaying as it should! Now it's just a matter of fixing the collectibles that don't display at all, which is more on Hiro's end!

**Comment by brandonmarshall-tm** [comment]
Hiro's reindex is now complete, and the number of inscriptions in my wallet is now reporting correctly! 

There is now just one inscription in my wallet that isn't displaying correctly, and I believe it's because it is using the `text` type even though it contains an image and code. This one is probably more of an edge case, but thought i'd report it!

https://ordinals.hiro.so/inscription/eb2067abe9e6e4e0eb23bf61ef6d1c233da2768f909786cc90aae7239fc45db8i538
https://ordinals.com/inscription/eb2067abe9e6e4e0eb23bf61ef6d1c233da2768f909786cc90aae7239fc45db8i538
https://www.ord.io/60541983

**Comment by fbwoolf** [comment]
> Hiro's reindex is now complete, and the number of inscriptions in my wallet is now reporting correctly!
> 
> There is now just one inscription in my wallet that isn't displaying correctly, and I believe it's because it is using the `text` type even though it contains an image and code. This one is probably more of an edge case, but thought i'd report it!
> 
> https://ordinals.hiro.so/inscription/eb2067abe9e6e4e0eb23bf61ef6d1c233da2768f909786cc90aae7239fc45db8i538 https://ordinals.com/inscription/eb2067abe9e6e4e0eb23bf61ef6d1c233da2768f909786cc90aae7239fc45db8i538 https://www.ord.io/60541983

Yeah, not rendering in the Hiro explorer either ...not sure how to catch that if the type is wrong, which it appears it is? 🤔 We could fallback to rendering the preview from ordinals.com? What do you see now in the wallet, just the `image unavailable` placeholder?

**Comment by brandonmarshall-tm** [comment]
No placeholder, it's just a black box
![Screenshot 2024-03-04 at 11 41 04 AM](https://github.com/leather-wallet/extension/assets/122313287/b2f57af9-d468-461a-812c-09f53dba713e)

**Comment by brandonmarshall-tm** [comment]
@fbwoolf a thought: What if all plaintext inscriptions were displayed as if they were HTML inscriptions? They would still display the same afaik, and in cases like this they would render "correctly" even when the mimetype is wrong.

**Comment by fbwoolf** [comment]
> @fbwoolf a thought: What if all plaintext inscriptions were displayed as if they were HTML inscriptions? They would still display the same afaik, and in cases like this they would render "correctly" even when the mimetype is wrong.

I think the only prob with that is we would be rendering a lot of iframes, and this preview of the text would be rendered and not styled by us... https://ordinals.com/preview/bc24f311bdb8e3f3b5aba06a12afa44ea0b8985992b88b01c2c94cb365f8461ei9

It might be better to use it as a fallback if the HIro query doesn't return the data we need?

**Comment by brandonmarshall-tm** [comment]
Oh yeah, that's a good point. I guess the fix is going to be more complicated than that 😅

**Comment by markmhendrickson** [comment]
> this preview of the text would be rendered and not styled by us...

Perhaps we could do a check beyond mimetype for text inscriptions in which we see if the text is validly formatted JSON, applying the same styling as JSON inscriptions (per mimetype)?

**Comment by brandonmarshall-tm** [comment]
@fbwoolf Here's another example where, based on the file type, the preview should be rendered through ordinals.com instead!

https://ordinals.hiro.so/inscription/c71bba106124a23d768874eba97ba730bcccb4bf58b86563e6c7e2685574e495i448
https://ordinals.com/inscription/c71bba106124a23d768874eba97ba730bcccb4bf58b86563e6c7e2685574e495i448

**Comment by markmhendrickson** [comment]
This latest inscription appears have a "model/gltf+json" mimetype so I'm spinning up a new issue to support it here: https://github.com/leather-wallet/extension/issues/5091

I've also split out the formatting enhancement for text inscriptions here: https://github.com/leather-wallet/extension/issues/5092

@brandonmarshall-tm Are we aware of any inscriptions with the HTML mimetype that don't show up currently, or can we close this particular issue for now?

Related: I've moved this issue for linking to Ord.io instead of Hiro Explorer so these display more consistently when the user clicks through: https://github.com/leather-wallet/extension/issues/3980
