### ISSUE TITLE
Ledger "Instruction not supported" error pops up right after "requesting STX addresses (1...5)-(5...5)"

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#4824]
![image](https://github.com/leather-wallet/extension/assets/33360391/4b816fc4-9739-4852-92e6-cf49ae052331)

![image](https://github.com/leather-wallet/extension/assets/33360391/55a86f56-5cc8-4e0f-9d0a-16492508f555)

First reported https://discord.com/channels/1075856098269089834/1075921953333968896/1187192792846446682
Second report today

The second user reported trying to access an account from the Blockstack ICO days. Probably unrelated but they are likely to work around this issue by using the desktop wallet instead because it skips this step and only accesses the index 0 address.

**Comment by larrysalibra** [comment]
https://github.com/leather-wallet/extension/assets/597182/383bb446-78cb-465b-8580-b171fcf3f087

I'm also experiencing this on a couple ledgers that were previously used with the leather desktop wallet.

Leather wallet extension version: v6.40.0
Chrome: Version 125.0.6422.61 (Official Build) (arm64)
macOS: 14.5 (23F79)

**Comment by kyranjamie** [comment]
@larrysalibra are you using the latest Stacks Ledger app from Ledger Live? `0.23.3`?

**Comment by larrysalibra** [comment]
thanks @kyranjamie ! The problem was that the development settings in ledger live that enabled the installation of the pre-release version of the ledger Stacks app prevented the prompt to upgrade the ledger firmware to `2.1.0` from `2.0.0` from appearing. This also prevented prompts to update the bitcoin and stacks ledger apps from displaying. Disabling those two settings caused the "update ledger firmware" prompt to appear in ledger live and allowed me to successfully update both the firmware and the apps. 

With the latest apps I don't see this error in the Leather extension anymore and everything works fine.


<img width="426" alt="Screenshot 2024-05-20 at 22 45 52" src="https://github.com/leather-wallet/extension/assets/597182/4c77729c-42aa-4c17-b88f-786af131bb0a">

**Comment by pete-watters** [comment]
Thanks for the update @larrysalibra, glad the issue has been resolved
