### ISSUE TITLE
Ensure users can increase fees for swaps

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#4828]
Per [user report](https://trustmachines.slack.com/archives/C069V6G48F7/p1705443334166589):

<img width="565" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/a8ebc124-8bba-4572-a998-4d3555b85ade">

@314159265359879 want to try swapping and increasing the fees for the transaction to see if you can recreate?

**Comment by 314159265359879** [comment]
@markmhendrickson this is a ledger bug not just a swap transaction are affected but any transaction when using a Ledger. 
Described here: https://github.com/leather-wallet/extension/issues/4503

The workaround is to replace the transaction manually, which is currently not possible when using the integrated swap (we'll discuss in our meeting on Monday) because it doesn't take the user through the flow of setting custom fee or custom nonce which would be needed. 

They can recreate the swap transaction via app.alexlab.co sign in (stacks network) with Leather and then make the swap, then adjust the fee (higher than the current transaction) and use the same nonce (click edit nonce below the fee options and above the confirm button) so that the original transaction can still get replaced.

**Comment by 314159265359879** [comment]
closing this
