### ISSUE TITLE
Indicate API-based errors for user

### ISSUE THREAD

**Issue by alter-eggo** [blockstack/blockstack-app#4925]
Design: https://www.figma.com/file/FlmF7ropcijOb7iVSDqNn0/%F0%9F%9F%A7-Web-App-Explorations-2024-H1?type=design&node-id=2039-75582&mode=design&t=jbjoqCEhyQt6z8Gm-4

**Comment by kyranjamie** [comment]
Curious how we detect when to show this error. It's not easy to get right, I think. 

If we track error responses, we show it when we see a 429, or any error response, it will be displayed very regularly for users. How do we build in a way so it doesn't flicker on/off. 

Further, if a user encounters 1 429 error, I might not actually effect functionality that much, yet we will show the error anyway.

Maybe it should be isolated to only certain query types?

**Comment by alter-eggo** [comment]
agree here. most critical requests are for blockstream api utxos and hiro api inscriptions? maybe start with them?
show callout in case there are more than 2 consecutive api error?

**Comment by markmhendrickson** [comment]
I'm moving this to the design backlog so we can firm up the UX specification before development. I'm also not sure using the toast is the right approach, for the above stated reasons. It seems more reliable to indicate errors within the components themselves that experience such errors (e.g. if the account total balance can't load, show an error there and retry option).

cc @fabric-8 @mica000 since this issue needs general consideration as we redesign components. I imagine we may resolve it gradually as we roll out new components
