### ISSUE TITLE
Update copy when no post conditions for Stacks transaction

### ISSUE THREAD

**Issue by tycho1212** [blockstack/blockstack-app#4988]
The current 'no post conditions banner' feels alarmist to users, especially since the lived experience of signing txs on other chains is the equivalent to a 'no post conditions tx' on stacks.

I would suggest something like 'This transaction is uncapped' since claiming that the transaction is 'not secure' is often not true / feels subjective.

Why is this important? The devex of adding post conditions is the most totally messed up thing I've ever seen. We've been trying to add post conditions for a week to one contract call. I can't even imagine how new devs in the ecosystem will experience this. Making it less intrusive UX to not use post conditions would be great until the ecosystem invests in making this devex better

PS: we're pushing ahead with fixing post conditions but it's essentially blocking our launch now when it shouldn't really be (the transaction is very much secure, just not verified / capped)

![signal-2024-02-27-081528_002](https://github.com/leather-wallet/extension/assets/32067484/a915efa1-d83a-4c38-b60a-30fb43bf94b1)

**Comment by markmhendrickson** [comment]
We've already redesigned this UX in general, so this warning will get updated holistically before long. However, in the meantime if it helps unblock you all, we can tweak the language. `This transaction can transfer any of your assets` seems like an accurate statement instead of `...is not secure`.

**Comment by markmhendrickson** [comment]
> The devex of adding post conditions is the most totally messed up thing I've ever seen.

I'd suggest getting in touch with the Hiro team about this specifically, if the guidance for how to set them via Stacks.js needs improvements. We could provide guidance as a wallet provider, though this seems best to get right on the library level first.

**Comment by friedger** [comment]
I agree to the update but alarmist message is a must. If we educate users that it is ok to sign txs without post conditions we end up in more scams and depleted wallets as on other chains. Post conditions is a unique selling point of stacks. 

I also agree improving DX, the recent contract call as read-only will help a lot.

**Comment by tycho1212** [comment]
Agree with that!

> This transaction can transfer any of your assets seems like an accurate statement instead of ...is not secure.

In the meantime, @y0s0n will reach out to Hiro soon to chat about making adding post conditions easier. Definitely agree with @friedger that they are super important ✨

**Comment by 314159265359879** [comment]
I think we should leave the "is not secure" phrase here when transactions are sent in "allow mode". Just because other chains think it is okay doesn't mean it should be adapted when we have a safer option (using deny mode for post-conditions). 

I agree that setting them correctly can be tedious but a highly anticipated app like Zest should adopt "deny mode" for its post-conditions. 

Even setting post conditions lazily without a cap for all the tokens that the transaction is expected to transfer with "can send more than 0 STX" and "... more than 0 sBTC" is safer than an "allow mode" transaction with no post-conditions which safeguards absolutely nothing. We do want to teach our users to tread very carefully when they see this message pop up. I think "is not secure" is warranted. 

I trust this transaction from Zest but we want users to be very careful when they see "allow mode" transactions, bad actors will take advantage when we let our guards down!

**Comment by diwakergupta** [comment]
> Agree with that!
> 
> > This transaction can transfer any of your assets seems like an accurate statement instead of ...is not secure.
> 
> In the meantime, @y0s0n will reach out to Hiro soon to chat about making adding post conditions easier. Definitely agree with @friedger that they are super important ✨

cc/ @janniks for visibility

**Comment by janniks** [comment]
Thanks for the mention

Let's chat about fixing post-conditions! We've added a more natural builder to Stacks.js, but would love to improve more!

I also really don't like the naming of post-condition-mode, since the mode doesn't change anything about included post-conditions (they are always verified). I try to refer to the mode as "allow/deny transfer of unspecified assets".

**Comment by tycho1212** [comment]
Indeed, I think @y0s0n just pinged Sabby about this but will link him this thread!

@314159265359879 even this lazy setting of post conditions can be extremely difficult from a developer perspective (it'e taken us 7 days of iterating on one contract call (still doesn't work) and we should be one of the most experienced teams with Stacks development)

> Even setting post conditions lazily without a cap for all the tokens that the transaction is expected to transfer with "can send more than 0 STX" and "... more than 0 sBTC"
