### ISSUE TITLE
Display BRC20 tokens in Ledger enabled wallet, but disable send-flow because it doesn't work

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5028]
Users are startled when the BRC20 balance isn't displayed in the wallet. 
They can still use ordinalsbot.com to inscribe a transfer inscription and send the transfer inscription out. 

Could we display the balance but instead make sending through the send flow unavailable? Preferably the token is grey'ed out and there is info (it is unsupported when using a hardware device and use the [ordinalsbot guide ](https://leather.gitbook.io/guides/bitcoin/brc-20-guide-to-transfer-via-ordinalsbot.com-and-leather) instead)

**Comment by markmhendrickson** [comment]
@alter-eggo @kyranjamie I presume we can display balances just fine, just can't support sending, correct?

If that's the case, let's just simply not show BRC-20 tokens in the list of tokens for sending if the user is using Ledger.

**Comment by alter-eggo** [comment]
> If that's the case, let's just simply not show BRC-20 tokens in the list of tokens for sending if the user is using Ledger.

balances are already not shown, you mean show but disable send?

**Comment by markmhendrickson** [comment]
Right, I mean let's not show BRC-20 tokens in the _send_ flow itself. 

We can keep showing the BRC-20 tokens on the home screen for Ledger users, but we can remove those same tokens from the token picker of the send flow, effectively disabling their send without requiring extra design guidance (e.g. by graying out or similar) since we're going to redesign the send UX entirely soon anyway (and can best incorporate new design then for how to handle cases in which certain assets aren't sendable).

**Comment by alter-eggo** [comment]
Close, as BRC-20 tokens are shown in ledger mode with disabled send
