### ISSUE TITLE
Virtual lists broken

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#5149]
We use virtuoso for performance reasons, so we don't render too much content at once, causing performance issues with the main thread being blocked. 

Some recent changes have broken this. See https://github.com/leather-wallet/extension/pull/5148 which demonstrates the issue. We render all items in the list, causing the thread to be blocked while we render the stacks accounts in the list.

https://github.com/leather-wallet/extension/assets/1618764/bc17fb57-609b-4468-8c58-70ff91d45867

Notice the delays, and lack of hover animations, that don't work while the thread is blocked.

**Comment by pete-watters** [comment]
I can take a look at this as I may have introduced it with some recent changes fixing bugs

**Comment by pete-watters** [comment]
I did some investigation on this today and from what I can see, we have never been using `Virtuoso` to load only what's visible in the viewport. I went back a fair few versions, to `v6.20` and even to Hiro Wallet in `v6.0.0`. 

We always render the full amount of available accounts in this list. 

I dug deeper into the code and cross referenced their example code and I think the issue lies in how we are setting the height of Virtuoso. I didn't go back further than `v6.0.0` but in there we are setting the list height with this code:
```
<Virtuoso
        initialTopMostItemIndex={currentAccountIndex}
        height="72px"
        style={{ paddingTop: '24px', height: '70vh' }}
        
```

I took a look at their[ sample code](https://virtuoso.dev/hello/) and added it to the APP. That worked and it relates to them specifying the height in this format:
```
 <Virtuoso
      style={{ height: 400 }}
     
```

If I change our lists to use that format then I can see them only loading whats in the viewport. Here's a video to demonstrate: 

https://github.com/leather-wallet/extension/assets/2938440/9a904d8e-bc81-45f2-996f-74ac6233172f

We are using `Virtuoso` in 3 places right now. In the past we had a lot of bugs related to height and accounts being cut off from view. I added fixes for those issues but I think the underlying issue was us not using the height correctly. 

I'll work on a fix to those issues now.

**Comment by kyranjamie** [comment]
> We always render the full amount of available accounts in this list.

Nope. See this PR from years ago that fixes render perf issues https://github.com/leather-wallet/extension/pull/2078 

In your example, all the account fit in the view, so it renders them all. In video below, 3c9c0f8cb9, with hundreds of accounts, we log the index when the item mounts. Each item renders only when it appears in view.

https://github.com/leather-wallet/extension/assets/1618764/67d0a142-4662-442e-8f74-3ce1e2cac6f9

It looks like it broke in 6262267ff1, where running the same code, we see it render them all. Perhaps to do with the change to dialog?

https://github.com/leather-wallet/extension/assets/1618764/27eceef5-16cd-40a4-9ec6-afc1bd3956eb

**Comment by pete-watters** [comment]
> > We always render the full amount of available accounts in this list.
> 
> Nope. See this PR from years ago that fixes render perf issues #2078
> 
> In your example, all the account fit in the view, so it renders them all. In video below, [3c9c0f8](https://github.com/leather-wallet/extension/commit/3c9c0f8cb9418398198ee406210c7fe91d84b2f5), with hundreds of accounts, we log the index when the item mounts. Each item renders only when it appears in view.
> 
>  2024-04-03-000151.mp4 
> It looks like it broke in [6262267](https://github.com/leather-wallet/extension/commit/6262267ff11fdeaa3f0d995fb5f286debcbbfd17), where running the same code, we see it render them all. Perhaps to do with the change to dialog?
> 
>  2024-04-03-000152.mp4

OK thanks, let me investigate more. I still think we aren't using it properly as in my example, only 4 Virtuoso items get logged which is what is visible but we are logging 13 even though only 9 are visible.

**Comment by pete-watters** [comment]
I had indeed broken this and implemented a fix https://github.com/leather-wallet/extension/pull/5170 that reduces the impact of the bug. 

Visually it's not perfect though so I will keep working on it to finish it off in https://github.com/leather-wallet/extension/pull/5171

**Comment by pete-watters** [comment]
My workaround means that sometimes the last entry in the list is cut off: 

![Screenshot 2024-04-09 at 10 37 06](https://github.com/leather-wallet/extension/assets/2938440/cfc874c7-5dbc-4b9a-979a-440aac16f499)

I'll fix this ASAP

**Comment by pete-watters** [comment]
The problem with loading all the data was fixed but there is a UI bug I will fix https://github.com/leather-wallet/extension/issues/5242

**Comment by pete-watters** [comment]
Closing this as I have fixed the issue in https://github.com/leather-wallet/extension/issues/5242. Pending code review
