### ISSUE TITLE
Adding custom testnet with stacks details, defaults with mainnet details for bitcoin API's

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5228]
![image](https://github.com/leather-wallet/extension/assets/33360391/87f76c40-1b9e-49a7-8fe3-fd886c93056a)

A dropdown menu button is shown but no way to select anything else. I am not sure if this should have been released without the testnet option there too.

**Comment by 314159265359879** [comment]
![image](https://github.com/leather-wallet/extension/assets/33360391/2aa92e28-c331-4663-8e0b-31714b55ffd4)

**Comment by pete-watters** [comment]
Hi @314159265359879 ,

Can you please check this is still an issue? I think it could have been fixed by https://github.com/leather-io/extension/issues/5132. 

Either that or I amn't understanding the problem. I added a new Stacks network and I am able to change the Bitcoin network 


https://github.com/leather-io/extension/assets/2938440/b7cac1dc-77f3-4d4a-9669-0b0b27a3d886

**Comment by markmhendrickson** [comment]
cc @314159265359879 for when you can confirm

**Comment by markmhendrickson** [comment]
nudge @314159265359879

**Comment by 314159265359879** [comment]
This is a non-issue with fix you named. And if anyone does default to the mainnet API for bitcoin while looking at a Stacks testnet, they can easily change it after this addition: https://github.com/leather-io/extension/issues/5124#issuecomment-2021019201
