### ISSUE TITLE
[Runes] Asset list UI improvements

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/blockstack-app#5246]
- [x]  The caption should say "Runes" not "RUNE"
- [x] If the spaced name is available, show that for the rune name
- [x] Add the currency symbol
- [x] Handle decimals in balance

**Comment by kyranjamie** [comment]
What tests can we write to ensure Runes functionality works?

**Comment by 314159265359879** [comment]
I am not sure we should add currency symbol, or we should be mindful of where we show it. I forse some issues. Firstly confusion if placed to the right of the amount because we're already placing symbols there to show thousands, millions. And secondly because I see options to add emoji's as symbols, will those get displayed properly? 

The Currency symbol should be placed to the left of the amount as to not confuse it with the K, M, B, T, we use for thousands and millions etc. Or perhaps in the sphere where the rune logo is now. Keeping it black with white symbol could still help users identify it as rune?

Runes will go up to ~3.4*10^38th max supply our wallet only uses shorthand upto T(rillion) then it displays the number. 
![image](https://github.com/leather-wallet/extension/assets/33360391/d30a00c2-29bd-4750-a1e2-8168050a081e)

t 100 instead of 100 t in case of The Best Rune AAB example:
![image](https://github.com/leather-wallet/extension/assets/33360391/5355e4ef-6303-4638-89dc-2e6296f248ea)
