### ISSUE TITLE
Several Stacks NFTs not showing in wallet

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5302]
I have several examples of Stacks NFTs not displaying at all in Leather. These all seem to be related to Hiro's API, so we would probably need to work with them resolve it. But since they are not displaying in our wallet, wanted to capture the issue here.

All of them produce Console errors like this:
`non-fungible-token-metadata.query.ts:40 GET https://api.hiro.so/metadata/v1/nft/SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys/2 404 (Not Found)`

Examples of more Collectibles that do not display:
SPQ5CEHETP8K4Q2FSNNK9ANMPAVBSA9NN86YSN59.stxstone
SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys
SP25W1B7YX3F20S598J4EXEE9HZ0XHY6PNVTT6FA3.trajan-endorse-v0_1_0

**Comment by brandonmarshall-tm** [comment]
Adding that the Pizza Ninjas and STXSTONES do display in Gamma:
https://stacks.gamma.io/collections/pizza-ninjas-on-sothebys/2
https://stacks.gamma.io/collections/stxstone/5326

**Comment by DeeList** [comment]
Issue reported to Hiro https://github.com/hirosystems/explorer/issues/1591

**Comment by 314159265359879** [comment]
![image](https://github.com/leather-wallet/extension/assets/33360391/128d5d9f-d794-42f4-9b74-1e254225ff0e)

These are not loading in the wallet. 

Among them is the recently popular majo NFT's
https://api.hiro.so/metadata/v1/nft/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.mojo/135 

![image](https://github.com/leather-wallet/extension/assets/33360391/35c456c0-98f8-4b53-abc7-f2538327d3c9)

**Comment by DeeList** [comment]
https://github.com/hirosystems/explorer/issues/1591#issuecomment-2093829686

**Comment by 314159265359879** [comment]
Another report of NFT's not being displayed in Leather, while other wallets (and stacks.gamma.io) do display them
https://stacks.gamma.io/SP30ND6RAZT4K2S8NQKYFTQ4GXT2WX4VMCQPHS24T?tab=collected 

relevant contracts:
SP229HYJZF8F2R6BYGJZENTY2MB8W1HRYKXTA9RZR.runedom
and
SPQ3TT36JN77TSPVXC70RZ4STZF4Y0PWT6VPJE82.fehudom

**Comment by brandonmarshall-tm** [comment]
Here is another user report, basically none of these are displaying in Leather and also not displaying correctly in Hiro (but do display correctly on Gamma)

https://explorer.hiro.so/address/SP2QP89JZACDW214Q5H2N3WJWXV5N5GKMA7HNPZ41?chain=mainnet
https://stacks.gamma.io/fortnakamoto.btc

**Comment by brandonmarshall-tm** [comment]
Created a Stacks-specific issue for this: https://github.com/hirosystems/explorer/issues/1634

**Comment by 314159265359879** [comment]
Related, possible solution in case we can't show an image: https://github.com/leather-wallet/extension/issues/3290

**Comment by markmhendrickson** [comment]
@brandonmarshall-tm it's perhaps best to post your issue above in the metadata API repo?

**Comment by brandonmarshall-tm** [comment]
Done: https://github.com/hirosystems/token-metadata-api/issues/218

**Comment by brandonmarshall-tm** [comment]
This issue can be resolved! The only NFTs not showing are ones not following SIP-016 standard, but the main ones that were previously missing (like Nakamojo and Project Indigo) are displaying now.

**Comment by DeeList** [comment]
There are some older NFTs and newer like the Stacks original Nakamojo NFT <https://explorer.hiro.so/txid/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.mojo?chain=mainnet> and Stacking DAO NFT <https://explorer.hiro.so/txid/SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.stacking-dao-genesis-nft?chain=mainnet> that do not display in Leather but show in Gamma.

<img width="258" alt="nfts" src="https://github.com/leather-wallet/extension/assets/132958967/84519ef2-cca9-4b5a-b300-5a5347c5a082">

<img width="362" alt="nft2" src="https://github.com/leather-wallet/extension/assets/132958967/c788f7ab-92f1-40ec-a70b-15e261b99dbb">

**Comment by 314159265359879** [comment]
I do not see Mojo loading either. And a couple more:
https://explorer.hiro.so/token/SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.megapont-ape-club-nft?chain=mainnet
https://explorer.hiro.so/token/SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ.boom-nfts?chain=mainnet 
https://explorer.hiro.so/token/SPGGAEQWA7Y9HRZY5T0XJCEYEZ28J6RKCCC1HP9M.chicken-and-mayo-music-nft?chain=mainnet
https://explorer.hiro.so/token/SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-pops?chain=mainnet
https://explorer.hiro.so/token/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.monkey-coin?chain=mainnet

These show up but they show with the image the contract was deployed with (placeholder, the same for every NFT in the contract) instead of the revealed images per NFT: https://explorer.hiro.so/token/SP2BE8TZATXEVPGZ8HAFZYE5GKZ02X0YDKAN7ZTGW.arties?chain=mainnet

**Comment by markmhendrickson** [comment]
@DeeList @314159265359879 has the Mojo issue been reported to Hiro, and if not, mind creating an issue in their API repo and cross-linking here to keep track?

In general, I'd recommend that we keep this extension-specific issue closed unless we uncover a problem with its code per se. Otherwise, it's not entirely clear whether we need to fix something with the extension on our end.

**Comment by DeeList** [comment]
[1591](https://github.com/hirosystems/explorer/issues/1591) also added comment [Mojo and Stacking DAO NFTs]( https://github.com/hirosystems/explorer/issues/1591#issuecomment-2146529912)

[New issue opened Stacks-Blockchain-API](https://github.com/hirosystems/token-metadata-api/issues/222)
