### ISSUE TITLE
Ledger not compatible with Runes

### ISSUE THREAD

**Issue by brandonmarshall-tm** [blockstack/blockstack-app#5312]
Got a user report that Ledger does not seem to be compatible with Runes. When interfacing with MagicEden and UniSat, they get an error when trying to list:
![image](https://github.com/leather-wallet/extension/assets/122313287/be7d621d-4989-412c-aeaa-2800edeb3361)

FWIW they are also having this issue on Xverse with Ledger, and are unable to even Transfer Runes to another wallet from there. So it looks to be a more Ledger-specific issue.

I just wanted to put this issue in for tracking purposes, and hopefully we can triage with Ledger.

**Comment by 314159265359879** [comment]
Possibly related to https://github.com/leather-wallet/extension/issues/4619

**Comment by brandonmarshall-tm** [comment]
Looks like Ledger is aware and working on it: https://twitter.com/Ledger_Support/status/1783794256894644246

**Comment by 314159265359879** [comment]
Ledger has resolved the issue, their update of the Bitcoin app to version 2.2.3 (or higher) will allow users to 
Sign minting Runes with Leather connected to a Ledger device
Sign Etching runes                                "
Sign transferring runes                          "
When you use Luminex.io for example. 

Listing Runes on ME is still broken, likely due to #4619 and fails with "the operation on device was rejected".
