### ISSUE TITLE
Prevent user accidentally paying too much in fee by showing a warning when triggering a PSBT

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#5346]
Ticket describing the issue: https://github.com/leather-wallet/extension/issues/5335

The wallet should help users understand when they are spending too much money on fees to avoid situation like the above. We discussed implementing alerts in the PSBT to notify users when they are spending a high amount on fees over a certain value.

To be defined:
- Should the value be absolute? If so, how much?
- Or Should the value be customizable?

cc @kyranjamie @fabric-8

**Comment by 314159265359879** [comment]
I think the UX should be aimed at preventing the user from accidentally paying a high fee. I think it should not prevent the user from doing so if they want to. Let them confirm by clicking a check mark for example?

In the example a transfer of 26000 sats is made and the fee is many multiples of the amount being transferred. I think it is safe to warn users when the fee is in access of 10% of the sats being transferred. Perhaps the warning should be more prominent when it is in access 50%? 

In case of a simple ordinal transfer, this may not work as well because ordinals are often in small UTXO's such as 500 sat UTXO. Even if fee rates are low (10 sats/vB) it will still cost 2000 sats to transfer such an ordinal (fee:total transfer ratio would be 1:4 (20%) although in this case that would be fine. 

Perhaps if you want to limit the amount of warnings (and increase the impact when they are shown) there could be a percentage limit fee compared to total spend. But with a minimum in absolute terms to not bother users with warnings when the absolute fee is relatively low such as those for a normal transfer (140 or 200 vB and moderate fee upto 50 sats/vB?...) we could refrain from showing warnings when absolute fees are 10000 sats or lower for example. Instead of that fixed absolute amount it would be even better to adapt it based on average medium fees on the network, in that case we could multiply: "normal transaction size", lets say 200 vB, * medium fee rate" in that case the minimum amount in which no warning is shown adapts based on fee market conditions.

**Comment by markmhendrickson** [comment]
@mica000 @314159265359879 let's capture input on this warning case [here](https://www.notion.so/trustmachines/Fee-is-unusually-high-add170c8724f4833a53fc8278b224ed1) instead of an issue since presumably this doesn't require a new feature per se but rather just an enhancement to the linked warning case (or addition of other warning variants)?
