### ISSUE TITLE
Send UI sometimes "flashes" address is not valid for a second

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/blockstack-app#5440]
Steps to reproduce
1. Click send
2. Select a SIP010 token
3. add amount
4. select an address from other accounts in the wallet
5. select low fee
6. click continue and see the error
![image](https://github.com/leather-wallet/extension/assets/33360391/9445a480-54b6-4285-b6a5-4c2db7ce47aa)

https://github.com/leather-wallet/extension/assets/33360391/70baaaf6-0599-4b51-bc3a-ec632fd2614a

7. you can still proceed with the transaction after that. 

The error does not pop up when I put my cursor in the memo input box before selecting low fee and continuing. I assume some issue with the address box validation and/or when it triggers.

**Comment by fbwoolf** [comment]
Confirming, I saw this today on every send.

**Comment by fbwoolf** [comment]
@kyranjamie I tracked this yesterday to when we added the `complianceValidator` (I think), if I comment out that code on the recipient validation, the bug is fixed. I can't quite determine yet why that validation is causing this, so if anything jumps out at you from working on it, let me know. It might be about the chain order of the validation using yup `concat`, but not sure yet.

**Comment by fbwoolf** [comment]
This appears to have surfaced bc of the async validation, and the fact that our recipient field defaults to an empty string.
