### ISSUE TITLE
UI fix: Center align title - Title on the header of send ordinals is moving to the left

### ISSUE THREAD

**Issue by mica000** [blockstack/blockstack-app#5470]
<img width="392" alt="image" src="https://github.com/leather-wallet/extension/assets/119523541/c4b0d1a7-386a-4783-9248-99e0c3a87d5b">

PS: On swap I believe the tile was gone but now that the feature is disabled I cant see anymore.

**Comment by pete-watters** [comment]
Thanks @mica000 👍  This bug was improved in https://github.com/leather-wallet/extension/pull/5456 

![Screenshot 2024-05-31 at 10 04 51](https://github.com/leather-wallet/extension/assets/2938440/dc1f1dcd-acc7-4215-929e-203478026342)

I'm not sure if it's 100% right yet though. Maybe we still need to give a left margin to the text the same width as the `X`? 

![Screenshot 2024-05-31 at 10 07 03](https://github.com/leather-wallet/extension/assets/2938440/455e4ff5-7fc4-41a6-b303-a3667d9554c5)

**Comment by mica000** [comment]
@pete-watters would absolute position on the parent work for this case?

**Comment by markmhendrickson** [comment]
Following up here – it does look like the title is still too far left and needs centering in the middle of the overall container. @pete-watters can we not simply position absolutely so that the side options don't affect it's alignment, I believe as @mica000 recommends?

<img width="410" alt="image" src="https://github.com/leather-wallet/extension/assets/28991/0a0e91fe-351f-45de-b2b0-e87da29bf039">

**Comment by pete-watters** [comment]
> Following up here – it does look like the title is still too far left and needs centering in the middle of the overall container. @pete-watters can we not simply position absolutely so that the side options don't affect it's alignment, I believe as @mica000 recommends?
> 
> <img alt="image" width="410" src="https://private-user-images.githubusercontent.com/28991/340616392-0a0e91fe-351f-45de-b2b0-e87da29bf039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDQ5NTQsIm5iZiI6MTcxODcwNDY1NCwicGF0aCI6Ii8yODk5MS8zNDA2MTYzOTItMGEwZTkxZmUtMzUxZi00NWRlLWIyYjAtZTg3ZGEyOWJmMDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA5NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZjUyYjUyMWU1NWE0YmFjZjMxNjU0MTE1Mzc0OWQzNjY0YWRhNzNkODMxNmQwZWMwYzM2M2Q2ZWM0NTA4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ChtwI6DmzMz8KF_20J_WRnSw7P7X-R1GQ4Dgn3uwvTs">

Yes we can do it, it's just a matter of when and we haven't been focused on it. I'll add it to my TODO's

**Comment by pete-watters** [comment]
@cbadawi kindly took this off my TODOs, thanks! It's merged and will be included in the next release

**Comment by pete-watters** [comment]
The original fix applied here introduced a bug with the main header buttons so I have done some re-work to separate the dialog and header and fix it: https://trustmachines.slack.com/archives/C05LAP952E7/p1719595558414679

![Screenshot 2024-06-28 at 12 25 39 PM](https://github.com/leather-io/extension/assets/2938440/6bb2e543-1926-45c4-80a3-7d7e1d8f02a6)
