### ISSUE TITLE
Add option to manage tokens shown or hidden by default

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#5643]

**Comment by 314159265359879** [comment]
Last time we discussed this, we landed on prioritizing finishing this (manage tokens) PR instead: https://github.com/leather-io/extension/pull/5568, is that still the case?

Rather than: https://github.com/leather-io/extension/issues/5404
or adding other tokens to be displayed, such as the one requested today: https://stxtools.io/tokens/SP3BRXZ9Y7P5YP28PSR8YJT39RT51ZZBSECTCADGR.skullcoin-stxcity

**Comment by markmhendrickson** [comment]
Ah that's true, I've moved back into the backlog for prioritization of its finalization work.
