### ISSUE TITLE
STX Transfer Displays Amount in µSTX using Multisig

### ISSUE THREAD

**Issue by alexp3y** [blockstack/blockstack-app#5941]
When sending an STX transfer using [Asigna's multisig wallet](https://stx.asigna.io), the confirmation screen displays the actual transfer amount divided by 10^6.

We seem to be incorrectly interpreting the transfer amount as µSTX instead of STX (actual amount in screenshot is 1 STX). When confirmed the transaction does send the actual amount (1 STX), so the issue seems to be limited to the confirmation UI itself.

![Image](https://github.com/user-attachments/assets/be06d383-2a6a-4418-8edc-d2157b830547)

**Comment by 314159265359879** [comment]
This issue was resolved before in March, looks like
https://github.com/leather-io/extension/issues/4819

I thought maybe it was resolved by Asigna back then because that issue doesn't have a fix linked. Checking with the dev and Mark if they remember ([slack](https://trustmachines.slack.com/archives/C06RADSM2TX/p1731095681890079?thread_ts=1730581514.660509&cid=C06RADSM2TX)).

**Comment by 314159265359879** [comment]
Asigna confirmed this was not fixed by them last time, transaction is actually transmitted with the correct settings and only displayed this way in the confirm screen. From the Discord conversation it looks like this was fixed by @kyranjamie last time. Do you remember? and perhaps how this was reintroduced.

**Comment by 314159265359879** [comment]
tested 5955, that fixes this issue.
